// Code generated by gen; DO NOT EDIT.

package gpu

import (
	"runtime"
	"sync"

	"github.com/Tnze/go-webgpu/webgpu"
)

// ---------------------------------------------------------------------------
// Blocking wait: pump AllowProcessEvents callbacks until a result arrives.
//
// The webgpu package owns the cgo/syscall callback plumbing; this file only
// provides the Go-side pump and the error folding used by the wrappers.
// ---------------------------------------------------------------------------

var (
	instanceMu    sync.Mutex
	liveInstances []*Instance
)

// registerInstance makes an instance eligible for event pumping.
func registerInstance(i *Instance) {
	instanceMu.Lock()
	liveInstances = append(liveInstances, i)
	instanceMu.Unlock()
}

func unregisterInstance(i *Instance) {
	instanceMu.Lock()
	for j, x := range liveInstances {
		if x == i {
			liveInstances = append(liveInstances[:j], liveInstances[j+1:]...)
			break
		}
	}
	instanceMu.Unlock()
}

func pumpEvents() {
	instanceMu.Lock()
	insts := make([]*Instance, len(liveInstances))
	copy(insts, liveInstances)
	instanceMu.Unlock()
	for _, in := range insts {
		if in != nil && in.h != nil {
			webgpu.InstanceProcessEvents(in.h)
		}
	}
}

// waitRecv blocks until a value arrives on ch, pumping WebGPU events so
// AllowProcessEvents completion callbacks can run on this goroutine.
func waitRecv[T any](ch <-chan T) T {
	for {
		select {
		case v := <-ch:
			return v
		default:
			pumpEvents()
			runtime.Gosched()
		}
	}
}

// ---------------------------------------------------------------------------
// Errors folded from WGPUErrorType + message.
// ---------------------------------------------------------------------------

type ValidationError struct{ Message string }

func (e *ValidationError) Error() string {
	if e.Message != "" {
		return "webgpu: validation: " + e.Message
	}
	return "webgpu: validation"
}

type OutOfMemoryError struct{ Message string }

func (e *OutOfMemoryError) Error() string {
	if e.Message != "" {
		return "webgpu: out of memory: " + e.Message
	}
	return "webgpu: out of memory"
}

type InternalError struct{ Message string }

func (e *InternalError) Error() string {
	if e.Message != "" {
		return "webgpu: internal: " + e.Message
	}
	return "webgpu: internal"
}

type UnknownError struct{ Message string }

func (e *UnknownError) Error() string {
	if e.Message != "" {
		return "webgpu: unknown: " + e.Message
	}
	return "webgpu: unknown"
}

// errorFromErrorType creates the typed error for a WGPUErrorType value.
// Returns nil for ErrorTypeNoError.
func errorFromErrorType(t webgpu.ErrorType, message string) error {
	switch t {
	case webgpu.ErrorTypeValidation:
		return &ValidationError{Message: message}
	case webgpu.ErrorTypeOutOfMemory:
		return &OutOfMemoryError{Message: message}
	case webgpu.ErrorTypeInternal:
		return &InternalError{Message: message}
	case webgpu.ErrorTypeUnknown:
		return &UnknownError{Message: message}
	}
	return nil
}
