// Code generated by gen; DO NOT EDIT.
//go:build cgo && !(windows && webgpu_dynload)

package webgpu

/*
#cgo CFLAGS: -I${SRCDIR}/../third_party/webgpu-headers
#include "webgpu.h"
#include <stdlib.h>
extern void goBufferMapCB(WGPUMapAsyncStatus status, WGPUStringView message, void* userdata1, void* userdata2);
extern void goCompilationInfoCB(WGPUCompilationInfoRequestStatus status, WGPUCompilationInfo* compilation_info, void* userdata1, void* userdata2);
extern void goCreateComputePipelineAsyncCB(WGPUCreatePipelineAsyncStatus status, WGPUComputePipeline pipeline, WGPUStringView message, void* userdata1, void* userdata2);
extern void goCreateRenderPipelineAsyncCB(WGPUCreatePipelineAsyncStatus status, WGPURenderPipeline pipeline, WGPUStringView message, void* userdata1, void* userdata2);
extern void goDeviceLostCB(WGPUDevice device, WGPUDeviceLostReason reason, WGPUStringView message, void* userdata1, void* userdata2);
extern void goPopErrorScopeCB(WGPUPopErrorScopeStatus status, WGPUErrorType type, WGPUStringView message, void* userdata1, void* userdata2);
extern void goQueueWorkDoneCB(WGPUQueueWorkDoneStatus status, WGPUStringView message, void* userdata1, void* userdata2);
extern void goRequestAdapterCB(WGPURequestAdapterStatus status, WGPUAdapter adapter, WGPUStringView message, void* userdata1, void* userdata2);
extern void goRequestDeviceCB(WGPURequestDeviceStatus status, WGPUDevice device, WGPUStringView message, void* userdata1, void* userdata2);
extern void goUncapturedErrorCB(WGPUDevice device, WGPUErrorType type, WGPUStringView message, void* userdata1, void* userdata2);
*/
import "C"

import (
	"runtime"
	"unsafe"
)

// cgoStringView converts a Go string to a C WGPUStringView input value.
func cgoStringView(s string, pinner *runtime.Pinner) C.WGPUStringView {
	var v C.WGPUStringView
	if len(s) > 0 {
		p := (*C.char)(unsafe.Pointer(unsafe.StringData(s)))
		pinner.Pin(unsafe.StringData(s))
		v.data = p
		v.length = C.size_t(len(s))
	}
	return v
}

// goStringView converts a callback WGPUStringView argument to a Go string.
func goStringView(v C.WGPUStringView) string {
	if v.data == nil || v.length == 0 {
		return ""
	}
	return C.GoStringN(v.data, C.int(v.length))
}

// cbPtr* are the raw C callback entry points used by NewXxxCallbackInfo.

var cbPtrBufferMap = uintptr(unsafe.Pointer(C.WGPUBufferMapCallback(C.goBufferMapCB)))

//export goBufferMapCB
func goBufferMapCB(c_status C.WGPUMapAsyncStatus, c_message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	r_status := MapAsyncStatus(c_status)
	r_message := goStringView(c_message)
	if fn, ok := takeCBThunk(uintptr(userdata1)).(BufferMapFn); ok && fn != nil {
		fn(r_status, r_message)
	}
}

var cbPtrCompilationInfo = uintptr(unsafe.Pointer(C.WGPUCompilationInfoCallback(C.goCompilationInfoCB)))

//export goCompilationInfoCB
func goCompilationInfoCB(c_status C.WGPUCompilationInfoRequestStatus, c_compilationInfo *C.WGPUCompilationInfo, userdata1, userdata2 unsafe.Pointer) {
	r_status := CompilationInfoRequestStatus(c_status)
	var r_compilationInfo *CompilationInfo
	if c_compilationInfo != nil {
		r_compilationInfo = (*CompilationInfo)(unsafe.Pointer(c_compilationInfo))
	}
	if fn, ok := takeCBThunk(uintptr(userdata1)).(CompilationInfoFn); ok && fn != nil {
		fn(r_status, r_compilationInfo)
	}
}

var cbPtrCreateComputePipelineAsync = uintptr(unsafe.Pointer(C.WGPUCreateComputePipelineAsyncCallback(C.goCreateComputePipelineAsyncCB)))

//export goCreateComputePipelineAsyncCB
func goCreateComputePipelineAsyncCB(c_status C.WGPUCreatePipelineAsyncStatus, c_pipeline C.WGPUComputePipeline, c_message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	r_status := CreatePipelineAsyncStatus(c_status)
	r_pipeline := ComputePipeline(unsafe.Pointer(c_pipeline))
	r_message := goStringView(c_message)
	if fn, ok := takeCBThunk(uintptr(userdata1)).(CreateComputePipelineAsyncFn); ok && fn != nil {
		fn(r_status, r_pipeline, r_message)
	}
}

var cbPtrCreateRenderPipelineAsync = uintptr(unsafe.Pointer(C.WGPUCreateRenderPipelineAsyncCallback(C.goCreateRenderPipelineAsyncCB)))

//export goCreateRenderPipelineAsyncCB
func goCreateRenderPipelineAsyncCB(c_status C.WGPUCreatePipelineAsyncStatus, c_pipeline C.WGPURenderPipeline, c_message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	r_status := CreatePipelineAsyncStatus(c_status)
	r_pipeline := RenderPipeline(unsafe.Pointer(c_pipeline))
	r_message := goStringView(c_message)
	if fn, ok := takeCBThunk(uintptr(userdata1)).(CreateRenderPipelineAsyncFn); ok && fn != nil {
		fn(r_status, r_pipeline, r_message)
	}
}

var cbPtrDeviceLost = uintptr(unsafe.Pointer(C.WGPUDeviceLostCallback(C.goDeviceLostCB)))

//export goDeviceLostCB
func goDeviceLostCB(c_device C.WGPUDevice, c_reason C.WGPUDeviceLostReason, c_message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	r_device := Device(unsafe.Pointer(c_device))
	r_reason := DeviceLostReason(c_reason)
	r_message := goStringView(c_message)
	if fn, ok := takeCBThunk(uintptr(userdata1)).(DeviceLostFn); ok && fn != nil {
		fn(r_device, r_reason, r_message)
	}
}

var cbPtrPopErrorScope = uintptr(unsafe.Pointer(C.WGPUPopErrorScopeCallback(C.goPopErrorScopeCB)))

//export goPopErrorScopeCB
func goPopErrorScopeCB(c_status C.WGPUPopErrorScopeStatus, c_typeVal C.WGPUErrorType, c_message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	r_status := PopErrorScopeStatus(c_status)
	r_err := ErrorType(c_typeVal)
	r_message := goStringView(c_message)
	if fn, ok := takeCBThunk(uintptr(userdata1)).(PopErrorScopeFn); ok && fn != nil {
		fn(r_status, r_err, r_message)
	}
}

var cbPtrQueueWorkDone = uintptr(unsafe.Pointer(C.WGPUQueueWorkDoneCallback(C.goQueueWorkDoneCB)))

//export goQueueWorkDoneCB
func goQueueWorkDoneCB(c_status C.WGPUQueueWorkDoneStatus, c_message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	r_status := QueueWorkDoneStatus(c_status)
	r_message := goStringView(c_message)
	if fn, ok := takeCBThunk(uintptr(userdata1)).(QueueWorkDoneFn); ok && fn != nil {
		fn(r_status, r_message)
	}
}

var cbPtrRequestAdapter = uintptr(unsafe.Pointer(C.WGPURequestAdapterCallback(C.goRequestAdapterCB)))

//export goRequestAdapterCB
func goRequestAdapterCB(c_status C.WGPURequestAdapterStatus, c_adapter C.WGPUAdapter, c_message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	r_status := RequestAdapterStatus(c_status)
	r_adapter := Adapter(unsafe.Pointer(c_adapter))
	r_message := goStringView(c_message)
	if fn, ok := takeCBThunk(uintptr(userdata1)).(RequestAdapterFn); ok && fn != nil {
		fn(r_status, r_adapter, r_message)
	}
}

var cbPtrRequestDevice = uintptr(unsafe.Pointer(C.WGPURequestDeviceCallback(C.goRequestDeviceCB)))

//export goRequestDeviceCB
func goRequestDeviceCB(c_status C.WGPURequestDeviceStatus, c_device C.WGPUDevice, c_message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	r_status := RequestDeviceStatus(c_status)
	r_device := Device(unsafe.Pointer(c_device))
	r_message := goStringView(c_message)
	if fn, ok := takeCBThunk(uintptr(userdata1)).(RequestDeviceFn); ok && fn != nil {
		fn(r_status, r_device, r_message)
	}
}

var cbPtrUncapturedError = uintptr(unsafe.Pointer(C.WGPUUncapturedErrorCallback(C.goUncapturedErrorCB)))

//export goUncapturedErrorCB
func goUncapturedErrorCB(c_device C.WGPUDevice, c_typeVal C.WGPUErrorType, c_message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	r_device := Device(unsafe.Pointer(c_device))
	r_err := ErrorType(c_typeVal)
	r_message := goStringView(c_message)
	if fn, ok := loadCBThunk(uintptr(userdata1)).(UncapturedErrorFn); ok && fn != nil {
		fn(r_device, r_err, r_message)
	}
}

func releaseAdapter(p unsafe.Pointer) {
	C.wgpuAdapterRelease((C.WGPUAdapter)(p))
}

func releaseBindGroup(p unsafe.Pointer) {
	C.wgpuBindGroupRelease((C.WGPUBindGroup)(p))
}

func releaseBindGroupLayout(p unsafe.Pointer) {
	C.wgpuBindGroupLayoutRelease((C.WGPUBindGroupLayout)(p))
}

func releaseBuffer(p unsafe.Pointer) {
	C.wgpuBufferRelease((C.WGPUBuffer)(p))
}

func releaseCommandBuffer(p unsafe.Pointer) {
	C.wgpuCommandBufferRelease((C.WGPUCommandBuffer)(p))
}

func releaseCommandEncoder(p unsafe.Pointer) {
	C.wgpuCommandEncoderRelease((C.WGPUCommandEncoder)(p))
}

func releaseComputePassEncoder(p unsafe.Pointer) {
	C.wgpuComputePassEncoderRelease((C.WGPUComputePassEncoder)(p))
}

func releaseComputePipeline(p unsafe.Pointer) {
	C.wgpuComputePipelineRelease((C.WGPUComputePipeline)(p))
}

func releaseDevice(p unsafe.Pointer) {
	C.wgpuDeviceRelease((C.WGPUDevice)(p))
}

func releaseExternalTexture(p unsafe.Pointer) {
	C.wgpuExternalTextureRelease((C.WGPUExternalTexture)(p))
}

func releaseInstance(p unsafe.Pointer) {
	C.wgpuInstanceRelease((C.WGPUInstance)(p))
}

func releasePipelineLayout(p unsafe.Pointer) {
	C.wgpuPipelineLayoutRelease((C.WGPUPipelineLayout)(p))
}

func releaseQuerySet(p unsafe.Pointer) {
	C.wgpuQuerySetRelease((C.WGPUQuerySet)(p))
}

func releaseQueue(p unsafe.Pointer) {
	C.wgpuQueueRelease((C.WGPUQueue)(p))
}

func releaseRenderBundle(p unsafe.Pointer) {
	C.wgpuRenderBundleRelease((C.WGPURenderBundle)(p))
}

func releaseRenderBundleEncoder(p unsafe.Pointer) {
	C.wgpuRenderBundleEncoderRelease((C.WGPURenderBundleEncoder)(p))
}

func releaseRenderPassEncoder(p unsafe.Pointer) {
	C.wgpuRenderPassEncoderRelease((C.WGPURenderPassEncoder)(p))
}

func releaseRenderPipeline(p unsafe.Pointer) {
	C.wgpuRenderPipelineRelease((C.WGPURenderPipeline)(p))
}

func releaseSampler(p unsafe.Pointer) {
	C.wgpuSamplerRelease((C.WGPUSampler)(p))
}

func releaseShaderModule(p unsafe.Pointer) {
	C.wgpuShaderModuleRelease((C.WGPUShaderModule)(p))
}

func releaseSurface(p unsafe.Pointer) {
	C.wgpuSurfaceRelease((C.WGPUSurface)(p))
}

func releaseTexture(p unsafe.Pointer) {
	C.wgpuTextureRelease((C.WGPUTexture)(p))
}

func releaseTextureView(p unsafe.Pointer) {
	C.wgpuTextureViewRelease((C.WGPUTextureView)(p))
}

// AdapterInfoFreeMembers frees memory allocated by the API inside value.
func AdapterInfoFreeMembers(value *AdapterInfo) {
	if value != nil {
		C.wgpuAdapterInfoFreeMembers(*(*C.WGPUAdapterInfo)(unsafe.Pointer(value)))
	}
}

// SupportedFeaturesFreeMembers frees memory allocated by the API inside value.
func SupportedFeaturesFreeMembers(value *SupportedFeatures) {
	if value != nil {
		C.wgpuSupportedFeaturesFreeMembers(*(*C.WGPUSupportedFeatures)(unsafe.Pointer(value)))
	}
}

// SupportedInstanceFeaturesFreeMembers frees memory allocated by the API inside value.
func SupportedInstanceFeaturesFreeMembers(value *SupportedInstanceFeatures) {
	if value != nil {
		C.wgpuSupportedInstanceFeaturesFreeMembers(*(*C.WGPUSupportedInstanceFeatures)(unsafe.Pointer(value)))
	}
}

// SupportedWGSLLanguageFeaturesFreeMembers frees memory allocated by the API inside value.
func SupportedWGSLLanguageFeaturesFreeMembers(value *SupportedWGSLLanguageFeatures) {
	if value != nil {
		C.wgpuSupportedWGSLLanguageFeaturesFreeMembers(*(*C.WGPUSupportedWGSLLanguageFeatures)(unsafe.Pointer(value)))
	}
}

// SurfaceCapabilitiesFreeMembers frees memory allocated by the API inside value.
func SurfaceCapabilitiesFreeMembers(value *SurfaceCapabilities) {
	if value != nil {
		C.wgpuSurfaceCapabilitiesFreeMembers(*(*C.WGPUSurfaceCapabilities)(unsafe.Pointer(value)))
	}
}

// Create a WGPUInstance

func CreateInstance(descriptor *InstanceDescriptor) Instance {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if descriptor.RequiredLimits != nil {
			pinner.Pin(descriptor.RequiredLimits)
		}
		if descriptor.RequiredFeatures != nil {
			pinner.Pin(descriptor.RequiredFeatures)
		}
	}
	c_descriptor := (*C.WGPUInstanceDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuCreateInstance(c_descriptor)
	return Instance(unsafe.Pointer(c_result))
}

// Get the list of @ref WGPUInstanceFeatureName values supported by the instance.

func GetInstanceFeatures(features *SupportedInstanceFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if features != nil {
		pinner.Pin(features)
		if features.Features != nil {
			pinner.Pin(features.Features)
		}
	}
	c_features := (*C.WGPUSupportedInstanceFeatures)(unsafe.Pointer(features))
	C.wgpuGetInstanceFeatures(c_features)
}

// Get the limits supported by the instance.

func GetInstanceLimits(limits *InstanceLimits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if limits != nil {
		pinner.Pin(limits)
		if limits.NextInChain != nil {
			pinner.Pin(limits.NextInChain)
		}
	}
	c_limits := (*C.WGPUInstanceLimits)(unsafe.Pointer(limits))
	c_result := C.wgpuGetInstanceLimits(c_limits)
	return Status(c_result)
}

// Check whether a particular @ref WGPUInstanceFeatureName is supported by the instance.

func HasInstanceFeature(feature InstanceFeatureName) Bool {
	c_feature := (C.WGPUInstanceFeatureName)(feature)
	c_result := C.wgpuHasInstanceFeature(c_feature)
	return Bool(c_result)
}

func AdapterGetLimits(a Adapter, limits *Limits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if limits != nil {
		pinner.Pin(limits)
		if limits.NextInChain != nil {
			pinner.Pin(limits.NextInChain)
		}
	}
	c_a := (C.WGPUAdapter)(unsafe.Pointer(a))
	c_limits := (*C.WGPULimits)(unsafe.Pointer(limits))
	c_result := C.wgpuAdapterGetLimits(c_a, c_limits)
	return Status(c_result)
}

func AdapterHasFeature(a Adapter, feature FeatureName) Bool {
	c_a := (C.WGPUAdapter)(unsafe.Pointer(a))
	c_feature := (C.WGPUFeatureName)(feature)
	c_result := C.wgpuAdapterHasFeature(c_a, c_feature)
	return Bool(c_result)
}

// Get the list of @ref WGPUFeatureName values supported by the adapter.

func AdapterGetFeatures(a Adapter, features *SupportedFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if features != nil {
		pinner.Pin(features)
		if features.Features != nil {
			pinner.Pin(features.Features)
		}
	}
	c_a := (C.WGPUAdapter)(unsafe.Pointer(a))
	c_features := (*C.WGPUSupportedFeatures)(unsafe.Pointer(features))
	C.wgpuAdapterGetFeatures(c_a, c_features)
}

func AdapterGetInfo(a Adapter, info *AdapterInfo) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if info != nil {
		pinner.Pin(info)
		if info.NextInChain != nil {
			pinner.Pin(info.NextInChain)
		}
		if len(info.Vendor) > 0 {
			pinner.Pin(unsafe.StringData(info.Vendor))
		}
		if len(info.Architecture) > 0 {
			pinner.Pin(unsafe.StringData(info.Architecture))
		}
		if len(info.Device) > 0 {
			pinner.Pin(unsafe.StringData(info.Device))
		}
		if len(info.Description) > 0 {
			pinner.Pin(unsafe.StringData(info.Description))
		}
	}
	c_a := (C.WGPUAdapter)(unsafe.Pointer(a))
	c_info := (*C.WGPUAdapterInfo)(unsafe.Pointer(info))
	c_result := C.wgpuAdapterGetInfo(c_a, c_info)
	return Status(c_result)
}

func AdapterRequestDevice(a Adapter, descriptor *DeviceDescriptor, callbackInfo RequestDeviceCallbackInfo) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if len(descriptor.DefaultQueue.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.DefaultQueue.Label))
		}
		if descriptor.RequiredLimits != nil {
			pinner.Pin(descriptor.RequiredLimits)
		}
		if descriptor.RequiredFeatures != nil {
			pinner.Pin(descriptor.RequiredFeatures)
		}
	}
	pinner.Pin(&callbackInfo)
	c_a := (C.WGPUAdapter)(unsafe.Pointer(a))
	c_descriptor := (*C.WGPUDeviceDescriptor)(unsafe.Pointer(descriptor))
	c_callbackInfo := *(*C.WGPURequestDeviceCallbackInfo)(unsafe.Pointer(&callbackInfo))
	c_result := C.wgpuAdapterRequestDevice(c_a, c_descriptor, c_callbackInfo)
	return Future{Id: uint64(c_result.id)}
}

// AdapterRelease calls wgpuAdapterRelease.
func AdapterRelease(a Adapter) {
	releaseAdapter(unsafe.Pointer(a))
}

func BindGroupSetLabel(b BindGroup, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_b := (C.WGPUBindGroup)(unsafe.Pointer(b))
	C.wgpuBindGroupSetLabel(c_b, c_label)
}

// BindGroupRelease calls wgpuBindGroupRelease.
func BindGroupRelease(b BindGroup) {
	releaseBindGroup(unsafe.Pointer(b))
}

func BindGroupLayoutSetLabel(b BindGroupLayout, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_b := (C.WGPUBindGroupLayout)(unsafe.Pointer(b))
	C.wgpuBindGroupLayoutSetLabel(c_b, c_label)
}

// BindGroupLayoutRelease calls wgpuBindGroupLayoutRelease.
func BindGroupLayoutRelease(b BindGroupLayout) {
	releaseBindGroupLayout(unsafe.Pointer(b))
}

func BufferMapAsync(b Buffer, mode MapMode, offset uintptr, size uintptr, callbackInfo BufferMapCallbackInfo) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&callbackInfo)
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	c_mode := (C.WGPUMapMode)(mode)
	c_offset := (C.size_t)(offset)
	c_size := (C.size_t)(size)
	c_callbackInfo := *(*C.WGPUBufferMapCallbackInfo)(unsafe.Pointer(&callbackInfo))
	c_result := C.wgpuBufferMapAsync(c_b, c_mode, c_offset, c_size, c_callbackInfo)
	return Future{Id: uint64(c_result.id)}
}

// Returns a mutable pointer to beginning of the mapped range.
// See @ref MappedRangeBehavior for error conditions and guarantees.
// This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).
//
// In Wasm, if `memcpy`ing into this range, prefer using @ref wgpuBufferWriteMappedRange
// instead for better performance.

func BufferGetMappedRange(b Buffer, offset uintptr, size uintptr) unsafe.Pointer {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	c_offset := (C.size_t)(offset)
	c_size := (C.size_t)(size)
	c_result := C.wgpuBufferGetMappedRange(c_b, c_offset, c_size)
	return unsafe.Pointer(c_result)
}

// Returns a const pointer to beginning of the mapped range.
// It must not be written; writing to this range causes undefined behavior.
// See @ref MappedRangeBehavior for error conditions and guarantees.
// This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).
//
// In Wasm, if `memcpy`ing from this range, prefer using @ref wgpuBufferReadMappedRange
// instead for better performance.

func BufferGetConstMappedRange(b Buffer, offset uintptr, size uintptr) unsafe.Pointer {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	c_offset := (C.size_t)(offset)
	c_size := (C.size_t)(size)
	c_result := C.wgpuBufferGetConstMappedRange(c_b, c_offset, c_size)
	return unsafe.Pointer(c_result)
}

// Copies a range of data from the buffer mapping into the provided destination pointer.
// See @ref MappedRangeBehavior for error conditions and guarantees.
// This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).
//
// In Wasm, this is more efficient than copying from a mapped range into a `malloc`'d range.

func BufferReadMappedRange(b Buffer, offset uintptr, data unsafe.Pointer, size uintptr) Status {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	c_offset := (C.size_t)(offset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	c_result := C.wgpuBufferReadMappedRange(c_b, c_offset, c_data, c_size)
	return Status(c_result)
}

// Copies a range of data from the provided source pointer into the buffer mapping.
// See @ref MappedRangeBehavior for error conditions and guarantees.
// This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).
//
// In Wasm, this is more efficient than copying from a `malloc`'d range into a mapped range.

func BufferWriteMappedRange(b Buffer, offset uintptr, data unsafe.Pointer, size uintptr) Status {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	c_offset := (C.size_t)(offset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	c_result := C.wgpuBufferWriteMappedRange(c_b, c_offset, c_data, c_size)
	return Status(c_result)
}

func BufferSetLabel(b Buffer, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	C.wgpuBufferSetLabel(c_b, c_label)
}

func BufferGetUsage(b Buffer) BufferUsage {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	c_result := C.wgpuBufferGetUsage(c_b)
	return (BufferUsage)(c_result)
}

func BufferGetSize(b Buffer) uint64 {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	c_result := C.wgpuBufferGetSize(c_b)
	return (uint64)(c_result)
}

func BufferGetMapState(b Buffer) BufferMapState {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	c_result := C.wgpuBufferGetMapState(c_b)
	return (BufferMapState)(c_result)
}

func BufferUnmap(b Buffer) {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	C.wgpuBufferUnmap(c_b)
}

func BufferDestroy(b Buffer) {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b))
	C.wgpuBufferDestroy(c_b)
}

// BufferRelease calls wgpuBufferRelease.
func BufferRelease(b Buffer) {
	releaseBuffer(unsafe.Pointer(b))
}

func CommandBufferSetLabel(c CommandBuffer, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_c := (C.WGPUCommandBuffer)(unsafe.Pointer(c))
	C.wgpuCommandBufferSetLabel(c_c, c_label)
}

// CommandBufferRelease calls wgpuCommandBufferRelease.
func CommandBufferRelease(c CommandBuffer) {
	releaseCommandBuffer(unsafe.Pointer(c))
}

func CommandEncoderFinish(c CommandEncoder, descriptor *CommandBufferDescriptor) CommandBuffer {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	c_descriptor := (*C.WGPUCommandBufferDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuCommandEncoderFinish(c_c, c_descriptor)
	return CommandBuffer(unsafe.Pointer(c_result))
}

func CommandEncoderBeginComputePass(c CommandEncoder, descriptor *ComputePassDescriptor) ComputePassEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.TimestampWrites != nil {
			pinner.Pin(descriptor.TimestampWrites)
		}
	}
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	c_descriptor := (*C.WGPUComputePassDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuCommandEncoderBeginComputePass(c_c, c_descriptor)
	return ComputePassEncoder(unsafe.Pointer(c_result))
}

func CommandEncoderBeginRenderPass(c CommandEncoder, descriptor *RenderPassDescriptor) RenderPassEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.DepthStencilAttachment != nil {
			pinner.Pin(descriptor.DepthStencilAttachment)
		}
		if descriptor.TimestampWrites != nil {
			pinner.Pin(descriptor.TimestampWrites)
		}
		if descriptor.ColorAttachments != nil {
			pinner.Pin(descriptor.ColorAttachments)
		}
	}
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	c_descriptor := (*C.WGPURenderPassDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuCommandEncoderBeginRenderPass(c_c, c_descriptor)
	return RenderPassEncoder(unsafe.Pointer(c_result))
}

func CommandEncoderCopyBufferToBuffer(c CommandEncoder, source Buffer, sourceOffset uint64, destination Buffer, destinationOffset uint64, size uint64) {
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	c_source := (C.WGPUBuffer)(unsafe.Pointer(source))
	c_sourceOffset := (C.uint64_t)(sourceOffset)
	c_destination := (C.WGPUBuffer)(unsafe.Pointer(destination))
	c_destinationOffset := (C.uint64_t)(destinationOffset)
	c_size := (C.uint64_t)(size)
	C.wgpuCommandEncoderCopyBufferToBuffer(c_c, c_source, c_sourceOffset, c_destination, c_destinationOffset, c_size)
}

func CommandEncoderCopyBufferToTexture(c CommandEncoder, source *TexelCopyBufferInfo, destination *TexelCopyTextureInfo, copySize *Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if source != nil {
		pinner.Pin(source)
	}
	if destination != nil {
		pinner.Pin(destination)
	}
	if copySize != nil {
		pinner.Pin(copySize)
	}
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	c_source := (*C.WGPUTexelCopyBufferInfo)(unsafe.Pointer(source))
	c_destination := (*C.WGPUTexelCopyTextureInfo)(unsafe.Pointer(destination))
	c_copySize := (*C.WGPUExtent3D)(unsafe.Pointer(copySize))
	C.wgpuCommandEncoderCopyBufferToTexture(c_c, c_source, c_destination, c_copySize)
}

func CommandEncoderCopyTextureToBuffer(c CommandEncoder, source *TexelCopyTextureInfo, destination *TexelCopyBufferInfo, copySize *Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if source != nil {
		pinner.Pin(source)
	}
	if destination != nil {
		pinner.Pin(destination)
	}
	if copySize != nil {
		pinner.Pin(copySize)
	}
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	c_source := (*C.WGPUTexelCopyTextureInfo)(unsafe.Pointer(source))
	c_destination := (*C.WGPUTexelCopyBufferInfo)(unsafe.Pointer(destination))
	c_copySize := (*C.WGPUExtent3D)(unsafe.Pointer(copySize))
	C.wgpuCommandEncoderCopyTextureToBuffer(c_c, c_source, c_destination, c_copySize)
}

func CommandEncoderCopyTextureToTexture(c CommandEncoder, source *TexelCopyTextureInfo, destination *TexelCopyTextureInfo, copySize *Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if source != nil {
		pinner.Pin(source)
	}
	if destination != nil {
		pinner.Pin(destination)
	}
	if copySize != nil {
		pinner.Pin(copySize)
	}
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	c_source := (*C.WGPUTexelCopyTextureInfo)(unsafe.Pointer(source))
	c_destination := (*C.WGPUTexelCopyTextureInfo)(unsafe.Pointer(destination))
	c_copySize := (*C.WGPUExtent3D)(unsafe.Pointer(copySize))
	C.wgpuCommandEncoderCopyTextureToTexture(c_c, c_source, c_destination, c_copySize)
}

func CommandEncoderClearBuffer(c CommandEncoder, buffer Buffer, offset uint64, size uint64) {
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer))
	c_offset := (C.uint64_t)(offset)
	c_size := (C.uint64_t)(size)
	C.wgpuCommandEncoderClearBuffer(c_c, c_buffer, c_offset, c_size)
}

func CommandEncoderInsertDebugMarker(c CommandEncoder, markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_markerLabel := cgoStringView(markerLabel, &pinner)
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	C.wgpuCommandEncoderInsertDebugMarker(c_c, c_markerLabel)
}

func CommandEncoderPopDebugGroup(c CommandEncoder) {
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	C.wgpuCommandEncoderPopDebugGroup(c_c)
}

func CommandEncoderPushDebugGroup(c CommandEncoder, groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_groupLabel := cgoStringView(groupLabel, &pinner)
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	C.wgpuCommandEncoderPushDebugGroup(c_c, c_groupLabel)
}

func CommandEncoderResolveQuerySet(c CommandEncoder, querySet QuerySet, firstQuery uint32, queryCount uint32, destination Buffer, destinationOffset uint64) {
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	c_querySet := (C.WGPUQuerySet)(unsafe.Pointer(querySet))
	c_firstQuery := (C.uint32_t)(firstQuery)
	c_queryCount := (C.uint32_t)(queryCount)
	c_destination := (C.WGPUBuffer)(unsafe.Pointer(destination))
	c_destinationOffset := (C.uint64_t)(destinationOffset)
	C.wgpuCommandEncoderResolveQuerySet(c_c, c_querySet, c_firstQuery, c_queryCount, c_destination, c_destinationOffset)
}

func CommandEncoderWriteTimestamp(c CommandEncoder, querySet QuerySet, queryIndex uint32) {
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	c_querySet := (C.WGPUQuerySet)(unsafe.Pointer(querySet))
	c_queryIndex := (C.uint32_t)(queryIndex)
	C.wgpuCommandEncoderWriteTimestamp(c_c, c_querySet, c_queryIndex)
}

func CommandEncoderSetLabel(c CommandEncoder, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c))
	C.wgpuCommandEncoderSetLabel(c_c, c_label)
}

// CommandEncoderRelease calls wgpuCommandEncoderRelease.
func CommandEncoderRelease(c CommandEncoder) {
	releaseCommandEncoder(unsafe.Pointer(c))
}

func ComputePassEncoderInsertDebugMarker(c ComputePassEncoder, markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_markerLabel := cgoStringView(markerLabel, &pinner)
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c))
	C.wgpuComputePassEncoderInsertDebugMarker(c_c, c_markerLabel)
}

func ComputePassEncoderPopDebugGroup(c ComputePassEncoder) {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c))
	C.wgpuComputePassEncoderPopDebugGroup(c_c)
}

func ComputePassEncoderPushDebugGroup(c ComputePassEncoder, groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_groupLabel := cgoStringView(groupLabel, &pinner)
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c))
	C.wgpuComputePassEncoderPushDebugGroup(c_c, c_groupLabel)
}

func ComputePassEncoderSetPipeline(c ComputePassEncoder, pipeline ComputePipeline) {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c))
	c_pipeline := (C.WGPUComputePipeline)(unsafe.Pointer(pipeline))
	C.wgpuComputePassEncoderSetPipeline(c_c, c_pipeline)
}

func ComputePassEncoderSetBindGroup(c ComputePassEncoder, groupIndex uint32, group BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c))
	c_groupIndex := (C.uint32_t)(groupIndex)
	c_group := (C.WGPUBindGroup)(unsafe.Pointer(group))
	var c_dynamicOffsets_ptr *C.uint32_t
	if len(dynamicOffsets) > 0 {
		c_dynamicOffsets_ptr = (*C.uint32_t)(unsafe.Pointer(&dynamicOffsets[0]))
	}
	c_dynamicOffsets_count := (C.size_t)(len(dynamicOffsets))
	C.wgpuComputePassEncoderSetBindGroup(c_c, c_groupIndex, c_group, c_dynamicOffsets_count, c_dynamicOffsets_ptr)
}

func ComputePassEncoderSetImmediates(c ComputePassEncoder, offset uint32, data unsafe.Pointer, size uintptr) {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c))
	c_offset := (C.uint32_t)(offset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	C.wgpuComputePassEncoderSetImmediates(c_c, c_offset, c_data, c_size)
}

func ComputePassEncoderDispatchWorkgroups(c ComputePassEncoder, workgroupCountX uint32, workgroupCountY uint32, workgroupCountZ uint32) {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c))
	c_workgroupCountX := (C.uint32_t)(workgroupCountX)
	c_workgroupCountY := (C.uint32_t)(workgroupCountY)
	c_workgroupCountZ := (C.uint32_t)(workgroupCountZ)
	C.wgpuComputePassEncoderDispatchWorkgroups(c_c, c_workgroupCountX, c_workgroupCountY, c_workgroupCountZ)
}

func ComputePassEncoderDispatchWorkgroupsIndirect(c ComputePassEncoder, indirectBuffer Buffer, indirectOffset uint64) {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c))
	c_indirectBuffer := (C.WGPUBuffer)(unsafe.Pointer(indirectBuffer))
	c_indirectOffset := (C.uint64_t)(indirectOffset)
	C.wgpuComputePassEncoderDispatchWorkgroupsIndirect(c_c, c_indirectBuffer, c_indirectOffset)
}

func ComputePassEncoderEnd(c ComputePassEncoder) {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c))
	C.wgpuComputePassEncoderEnd(c_c)
}

func ComputePassEncoderSetLabel(c ComputePassEncoder, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c))
	C.wgpuComputePassEncoderSetLabel(c_c, c_label)
}

// ComputePassEncoderRelease calls wgpuComputePassEncoderRelease.
func ComputePassEncoderRelease(c ComputePassEncoder) {
	releaseComputePassEncoder(unsafe.Pointer(c))
}

func ComputePipelineGetBindGroupLayout(c ComputePipeline, groupIndex uint32) BindGroupLayout {
	c_c := (C.WGPUComputePipeline)(unsafe.Pointer(c))
	c_groupIndex := (C.uint32_t)(groupIndex)
	c_result := C.wgpuComputePipelineGetBindGroupLayout(c_c, c_groupIndex)
	return BindGroupLayout(unsafe.Pointer(c_result))
}

func ComputePipelineSetLabel(c ComputePipeline, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_c := (C.WGPUComputePipeline)(unsafe.Pointer(c))
	C.wgpuComputePipelineSetLabel(c_c, c_label)
}

// ComputePipelineRelease calls wgpuComputePipelineRelease.
func ComputePipelineRelease(c ComputePipeline) {
	releaseComputePipeline(unsafe.Pointer(c))
}

func DeviceCreateBindGroup(d Device, descriptor *BindGroupDescriptor) BindGroup {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.Entries != nil {
			pinner.Pin(descriptor.Entries)
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUBindGroupDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateBindGroup(c_d, c_descriptor)
	return BindGroup(unsafe.Pointer(c_result))
}

func DeviceCreateBindGroupLayout(d Device, descriptor *BindGroupLayoutDescriptor) BindGroupLayout {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.Entries != nil {
			pinner.Pin(descriptor.Entries)
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUBindGroupLayoutDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateBindGroupLayout(c_d, c_descriptor)
	return BindGroupLayout(unsafe.Pointer(c_result))
}

// TODO
//
// If @ref WGPUBufferDescriptor::mappedAtCreation is `true` and the mapping allocation fails,
// returns `NULL`.

func DeviceCreateBuffer(d Device, descriptor *BufferDescriptor) Buffer {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUBufferDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateBuffer(c_d, c_descriptor)
	return Buffer(unsafe.Pointer(c_result))
}

func DeviceCreateCommandEncoder(d Device, descriptor *CommandEncoderDescriptor) CommandEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUCommandEncoderDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateCommandEncoder(c_d, c_descriptor)
	return CommandEncoder(unsafe.Pointer(c_result))
}

func DeviceCreateComputePipeline(d Device, descriptor *ComputePipelineDescriptor) ComputePipeline {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if len(descriptor.Compute.EntryPoint) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Compute.EntryPoint))
		}
		if descriptor.Compute.Constants != nil {
			pinner.Pin(descriptor.Compute.Constants)
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUComputePipelineDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateComputePipeline(c_d, c_descriptor)
	return ComputePipeline(unsafe.Pointer(c_result))
}

func DeviceCreateComputePipelineAsync(d Device, descriptor *ComputePipelineDescriptor, callbackInfo CreateComputePipelineAsyncCallbackInfo) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if len(descriptor.Compute.EntryPoint) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Compute.EntryPoint))
		}
		if descriptor.Compute.Constants != nil {
			pinner.Pin(descriptor.Compute.Constants)
		}
	}
	pinner.Pin(&callbackInfo)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUComputePipelineDescriptor)(unsafe.Pointer(descriptor))
	c_callbackInfo := *(*C.WGPUCreateComputePipelineAsyncCallbackInfo)(unsafe.Pointer(&callbackInfo))
	c_result := C.wgpuDeviceCreateComputePipelineAsync(c_d, c_descriptor, c_callbackInfo)
	return Future{Id: uint64(c_result.id)}
}

func DeviceCreatePipelineLayout(d Device, descriptor *PipelineLayoutDescriptor) PipelineLayout {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.BindGroupLayouts != nil {
			pinner.Pin(descriptor.BindGroupLayouts)
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUPipelineLayoutDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreatePipelineLayout(c_d, c_descriptor)
	return PipelineLayout(unsafe.Pointer(c_result))
}

func DeviceCreateQuerySet(d Device, descriptor *QuerySetDescriptor) QuerySet {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUQuerySetDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateQuerySet(c_d, c_descriptor)
	return QuerySet(unsafe.Pointer(c_result))
}

func DeviceCreateRenderPipelineAsync(d Device, descriptor *RenderPipelineDescriptor, callbackInfo CreateRenderPipelineAsyncCallbackInfo) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if len(descriptor.Vertex.EntryPoint) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Vertex.EntryPoint))
		}
		if descriptor.DepthStencil != nil {
			pinner.Pin(descriptor.DepthStencil)
		}
		if descriptor.Fragment != nil {
			pinner.Pin(descriptor.Fragment)
		}
		if descriptor.Vertex.Constants != nil {
			pinner.Pin(descriptor.Vertex.Constants)
		}
		if descriptor.Vertex.Buffers != nil {
			pinner.Pin(descriptor.Vertex.Buffers)
		}
	}
	pinner.Pin(&callbackInfo)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPURenderPipelineDescriptor)(unsafe.Pointer(descriptor))
	c_callbackInfo := *(*C.WGPUCreateRenderPipelineAsyncCallbackInfo)(unsafe.Pointer(&callbackInfo))
	c_result := C.wgpuDeviceCreateRenderPipelineAsync(c_d, c_descriptor, c_callbackInfo)
	return Future{Id: uint64(c_result.id)}
}

func DeviceCreateRenderBundleEncoder(d Device, descriptor *RenderBundleEncoderDescriptor) RenderBundleEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.ColorFormats != nil {
			pinner.Pin(descriptor.ColorFormats)
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPURenderBundleEncoderDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateRenderBundleEncoder(c_d, c_descriptor)
	return RenderBundleEncoder(unsafe.Pointer(c_result))
}

func DeviceCreateRenderPipeline(d Device, descriptor *RenderPipelineDescriptor) RenderPipeline {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if len(descriptor.Vertex.EntryPoint) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Vertex.EntryPoint))
		}
		if descriptor.DepthStencil != nil {
			pinner.Pin(descriptor.DepthStencil)
		}
		if descriptor.Fragment != nil {
			pinner.Pin(descriptor.Fragment)
		}
		if descriptor.Vertex.Constants != nil {
			pinner.Pin(descriptor.Vertex.Constants)
		}
		if descriptor.Vertex.Buffers != nil {
			pinner.Pin(descriptor.Vertex.Buffers)
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPURenderPipelineDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateRenderPipeline(c_d, c_descriptor)
	return RenderPipeline(unsafe.Pointer(c_result))
}

func DeviceCreateSampler(d Device, descriptor *SamplerDescriptor) Sampler {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUSamplerDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateSampler(c_d, c_descriptor)
	return Sampler(unsafe.Pointer(c_result))
}

func DeviceCreateShaderModule(d Device, descriptor *ShaderModuleDescriptor) ShaderModule {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUShaderModuleDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateShaderModule(c_d, c_descriptor)
	return ShaderModule(unsafe.Pointer(c_result))
}

func DeviceCreateTexture(d Device, descriptor *TextureDescriptor) Texture {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.ViewFormats != nil {
			pinner.Pin(descriptor.ViewFormats)
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_descriptor := (*C.WGPUTextureDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuDeviceCreateTexture(c_d, c_descriptor)
	return Texture(unsafe.Pointer(c_result))
}

func DeviceDestroy(d Device) {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	C.wgpuDeviceDestroy(c_d)
}

func DeviceGetLostFuture(d Device) Future {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_result := C.wgpuDeviceGetLostFuture(c_d)
	return Future{Id: uint64(c_result.id)}
}

func DeviceGetLimits(d Device, limits *Limits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if limits != nil {
		pinner.Pin(limits)
		if limits.NextInChain != nil {
			pinner.Pin(limits.NextInChain)
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_limits := (*C.WGPULimits)(unsafe.Pointer(limits))
	c_result := C.wgpuDeviceGetLimits(c_d, c_limits)
	return Status(c_result)
}

func DeviceHasFeature(d Device, feature FeatureName) Bool {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_feature := (C.WGPUFeatureName)(feature)
	c_result := C.wgpuDeviceHasFeature(c_d, c_feature)
	return Bool(c_result)
}

// Get the list of @ref WGPUFeatureName values supported by the device.

func DeviceGetFeatures(d Device, features *SupportedFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if features != nil {
		pinner.Pin(features)
		if features.Features != nil {
			pinner.Pin(features.Features)
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_features := (*C.WGPUSupportedFeatures)(unsafe.Pointer(features))
	C.wgpuDeviceGetFeatures(c_d, c_features)
}

func DeviceGetAdapterInfo(d Device, adapterInfo *AdapterInfo) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if adapterInfo != nil {
		pinner.Pin(adapterInfo)
		if adapterInfo.NextInChain != nil {
			pinner.Pin(adapterInfo.NextInChain)
		}
		if len(adapterInfo.Vendor) > 0 {
			pinner.Pin(unsafe.StringData(adapterInfo.Vendor))
		}
		if len(adapterInfo.Architecture) > 0 {
			pinner.Pin(unsafe.StringData(adapterInfo.Architecture))
		}
		if len(adapterInfo.Device) > 0 {
			pinner.Pin(unsafe.StringData(adapterInfo.Device))
		}
		if len(adapterInfo.Description) > 0 {
			pinner.Pin(unsafe.StringData(adapterInfo.Description))
		}
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_adapterInfo := (*C.WGPUAdapterInfo)(unsafe.Pointer(adapterInfo))
	c_result := C.wgpuDeviceGetAdapterInfo(c_d, c_adapterInfo)
	return Status(c_result)
}

func DeviceGetQueue(d Device) Queue {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_result := C.wgpuDeviceGetQueue(c_d)
	return Queue(unsafe.Pointer(c_result))
}

// Pushes an error scope to the current thread's error scope stack.
// See @ref ErrorScopes.

func DevicePushErrorScope(d Device, filter ErrorFilter) {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_filter := (C.WGPUErrorFilter)(filter)
	C.wgpuDevicePushErrorScope(c_d, c_filter)
}

// Pops an error scope to the current thread's error scope stack,
// asynchronously returning the result. See @ref ErrorScopes.

func DevicePopErrorScope(d Device, callbackInfo PopErrorScopeCallbackInfo) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&callbackInfo)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	c_callbackInfo := *(*C.WGPUPopErrorScopeCallbackInfo)(unsafe.Pointer(&callbackInfo))
	c_result := C.wgpuDevicePopErrorScope(c_d, c_callbackInfo)
	return Future{Id: uint64(c_result.id)}
}

func DeviceSetLabel(d Device, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d))
	C.wgpuDeviceSetLabel(c_d, c_label)
}

// DeviceRelease calls wgpuDeviceRelease.
func DeviceRelease(d Device) {
	releaseDevice(unsafe.Pointer(d))
}

func ExternalTextureSetLabel(e ExternalTexture, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_e := (C.WGPUExternalTexture)(unsafe.Pointer(e))
	C.wgpuExternalTextureSetLabel(c_e, c_label)
}

// ExternalTextureRelease calls wgpuExternalTextureRelease.
func ExternalTextureRelease(e ExternalTexture) {
	releaseExternalTexture(unsafe.Pointer(e))
}

// Creates a @ref WGPUSurface, see @ref Surface-Creation for more details.

func InstanceCreateSurface(i Instance, descriptor *SurfaceDescriptor) Surface {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	c_i := (C.WGPUInstance)(unsafe.Pointer(i))
	c_descriptor := (*C.WGPUSurfaceDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuInstanceCreateSurface(c_i, c_descriptor)
	return Surface(unsafe.Pointer(c_result))
}

// Get the list of @ref WGPUWGSLLanguageFeatureName values supported by the instance.

func InstanceGetWGSLLanguageFeatures(i Instance, features *SupportedWGSLLanguageFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if features != nil {
		pinner.Pin(features)
		if features.Features != nil {
			pinner.Pin(features.Features)
		}
	}
	c_i := (C.WGPUInstance)(unsafe.Pointer(i))
	c_features := (*C.WGPUSupportedWGSLLanguageFeatures)(unsafe.Pointer(features))
	C.wgpuInstanceGetWGSLLanguageFeatures(c_i, c_features)
}

func InstanceHasWGSLLanguageFeature(i Instance, feature WGSLLanguageFeatureName) Bool {
	c_i := (C.WGPUInstance)(unsafe.Pointer(i))
	c_feature := (C.WGPUWGSLLanguageFeatureName)(feature)
	c_result := C.wgpuInstanceHasWGSLLanguageFeature(c_i, c_feature)
	return Bool(c_result)
}

// Processes asynchronous events on this `WGPUInstance`, calling any callbacks for asynchronous operations created with @ref WGPUCallbackMode_AllowProcessEvents.
//
// See @ref Process-Events for more information.

func InstanceProcessEvents(i Instance) {
	c_i := (C.WGPUInstance)(unsafe.Pointer(i))
	C.wgpuInstanceProcessEvents(c_i)
}

func InstanceRequestAdapter(i Instance, options *RequestAdapterOptions, callbackInfo RequestAdapterCallbackInfo) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if options != nil {
		pinner.Pin(options)
		if options.NextInChain != nil {
			pinner.Pin(options.NextInChain)
		}
	}
	pinner.Pin(&callbackInfo)
	c_i := (C.WGPUInstance)(unsafe.Pointer(i))
	c_options := (*C.WGPURequestAdapterOptions)(unsafe.Pointer(options))
	c_callbackInfo := *(*C.WGPURequestAdapterCallbackInfo)(unsafe.Pointer(&callbackInfo))
	c_result := C.wgpuInstanceRequestAdapter(c_i, c_options, c_callbackInfo)
	return Future{Id: uint64(c_result.id)}
}

// Wait for at least one WGPUFuture in `futures` to complete, and call callbacks of the respective completed asynchronous operations.
//
// See @ref Wait-Any for more information.

func InstanceWaitAny(i Instance, futureCount uintptr, futures *FutureWaitInfo, timeoutNS uint64) WaitStatus {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if futures != nil {
		pinner.Pin(futures)
	}
	c_i := (C.WGPUInstance)(unsafe.Pointer(i))
	c_futureCount := (C.size_t)(futureCount)
	c_futures := (*C.WGPUFutureWaitInfo)(unsafe.Pointer(futures))
	c_timeoutNS := (C.uint64_t)(timeoutNS)
	c_result := C.wgpuInstanceWaitAny(c_i, c_futureCount, c_futures, c_timeoutNS)
	return WaitStatus(c_result)
}

// InstanceRelease calls wgpuInstanceRelease.
func InstanceRelease(i Instance) {
	releaseInstance(unsafe.Pointer(i))
}

func PipelineLayoutSetLabel(p PipelineLayout, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_p := (C.WGPUPipelineLayout)(unsafe.Pointer(p))
	C.wgpuPipelineLayoutSetLabel(c_p, c_label)
}

// PipelineLayoutRelease calls wgpuPipelineLayoutRelease.
func PipelineLayoutRelease(p PipelineLayout) {
	releasePipelineLayout(unsafe.Pointer(p))
}

func QuerySetSetLabel(q QuerySet, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_q := (C.WGPUQuerySet)(unsafe.Pointer(q))
	C.wgpuQuerySetSetLabel(c_q, c_label)
}

func QuerySetGetType(q QuerySet) QueryType {
	c_q := (C.WGPUQuerySet)(unsafe.Pointer(q))
	c_result := C.wgpuQuerySetGetType(c_q)
	return (QueryType)(c_result)
}

func QuerySetGetCount(q QuerySet) uint32 {
	c_q := (C.WGPUQuerySet)(unsafe.Pointer(q))
	c_result := C.wgpuQuerySetGetCount(c_q)
	return (uint32)(c_result)
}

func QuerySetDestroy(q QuerySet) {
	c_q := (C.WGPUQuerySet)(unsafe.Pointer(q))
	C.wgpuQuerySetDestroy(c_q)
}

// QuerySetRelease calls wgpuQuerySetRelease.
func QuerySetRelease(q QuerySet) {
	releaseQuerySet(unsafe.Pointer(q))
}

func QueueSubmit(q Queue, commands []CommandBuffer) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(commands) > 0 {
		pinner.Pin(&commands[0])
	}
	c_q := (C.WGPUQueue)(unsafe.Pointer(q))
	var c_commands_ptr *C.WGPUCommandBuffer
	if len(commands) > 0 {
		c_commands_ptr = (*C.WGPUCommandBuffer)(unsafe.Pointer(&commands[0]))
	}
	c_commands_count := (C.size_t)(len(commands))
	C.wgpuQueueSubmit(c_q, c_commands_count, c_commands_ptr)
}

func QueueOnSubmittedWorkDone(q Queue, callbackInfo QueueWorkDoneCallbackInfo) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&callbackInfo)
	c_q := (C.WGPUQueue)(unsafe.Pointer(q))
	c_callbackInfo := *(*C.WGPUQueueWorkDoneCallbackInfo)(unsafe.Pointer(&callbackInfo))
	c_result := C.wgpuQueueOnSubmittedWorkDone(c_q, c_callbackInfo)
	return Future{Id: uint64(c_result.id)}
}

// Produces a @ref DeviceError both content-timeline (`size` alignment) and device-timeline
// errors defined by the WebGPU specification.

func QueueWriteBuffer(q Queue, buffer Buffer, bufferOffset uint64, data unsafe.Pointer, size uintptr) {
	c_q := (C.WGPUQueue)(unsafe.Pointer(q))
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer))
	c_bufferOffset := (C.uint64_t)(bufferOffset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	C.wgpuQueueWriteBuffer(c_q, c_buffer, c_bufferOffset, c_data, c_size)
}

func QueueWriteTexture(q Queue, destination *TexelCopyTextureInfo, data unsafe.Pointer, dataSize uintptr, dataLayout *TexelCopyBufferLayout, writeSize *Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if destination != nil {
		pinner.Pin(destination)
	}
	if dataLayout != nil {
		pinner.Pin(dataLayout)
	}
	if writeSize != nil {
		pinner.Pin(writeSize)
	}
	c_q := (C.WGPUQueue)(unsafe.Pointer(q))
	c_destination := (*C.WGPUTexelCopyTextureInfo)(unsafe.Pointer(destination))
	c_data := (unsafe.Pointer)(data)
	c_dataSize := (C.size_t)(dataSize)
	c_dataLayout := (*C.WGPUTexelCopyBufferLayout)(unsafe.Pointer(dataLayout))
	c_writeSize := (*C.WGPUExtent3D)(unsafe.Pointer(writeSize))
	C.wgpuQueueWriteTexture(c_q, c_destination, c_data, c_dataSize, c_dataLayout, c_writeSize)
}

func QueueSetLabel(q Queue, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_q := (C.WGPUQueue)(unsafe.Pointer(q))
	C.wgpuQueueSetLabel(c_q, c_label)
}

// QueueRelease calls wgpuQueueRelease.
func QueueRelease(q Queue) {
	releaseQueue(unsafe.Pointer(q))
}

func RenderBundleSetLabel(r RenderBundle, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_r := (C.WGPURenderBundle)(unsafe.Pointer(r))
	C.wgpuRenderBundleSetLabel(c_r, c_label)
}

// RenderBundleRelease calls wgpuRenderBundleRelease.
func RenderBundleRelease(r RenderBundle) {
	releaseRenderBundle(unsafe.Pointer(r))
}

func RenderBundleEncoderSetPipeline(r RenderBundleEncoder, pipeline RenderPipeline) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	c_pipeline := (C.WGPURenderPipeline)(unsafe.Pointer(pipeline))
	C.wgpuRenderBundleEncoderSetPipeline(c_r, c_pipeline)
}

func RenderBundleEncoderSetBindGroup(r RenderBundleEncoder, groupIndex uint32, group BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	c_groupIndex := (C.uint32_t)(groupIndex)
	c_group := (C.WGPUBindGroup)(unsafe.Pointer(group))
	var c_dynamicOffsets_ptr *C.uint32_t
	if len(dynamicOffsets) > 0 {
		c_dynamicOffsets_ptr = (*C.uint32_t)(unsafe.Pointer(&dynamicOffsets[0]))
	}
	c_dynamicOffsets_count := (C.size_t)(len(dynamicOffsets))
	C.wgpuRenderBundleEncoderSetBindGroup(c_r, c_groupIndex, c_group, c_dynamicOffsets_count, c_dynamicOffsets_ptr)
}

func RenderBundleEncoderSetImmediates(r RenderBundleEncoder, offset uint32, data unsafe.Pointer, size uintptr) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	c_offset := (C.uint32_t)(offset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	C.wgpuRenderBundleEncoderSetImmediates(c_r, c_offset, c_data, c_size)
}

func RenderBundleEncoderDraw(r RenderBundleEncoder, vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	c_vertexCount := (C.uint32_t)(vertexCount)
	c_instanceCount := (C.uint32_t)(instanceCount)
	c_firstVertex := (C.uint32_t)(firstVertex)
	c_firstInstance := (C.uint32_t)(firstInstance)
	C.wgpuRenderBundleEncoderDraw(c_r, c_vertexCount, c_instanceCount, c_firstVertex, c_firstInstance)
}

func RenderBundleEncoderDrawIndexed(r RenderBundleEncoder, indexCount uint32, instanceCount uint32, firstIndex uint32, baseVertex int32, firstInstance uint32) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	c_indexCount := (C.uint32_t)(indexCount)
	c_instanceCount := (C.uint32_t)(instanceCount)
	c_firstIndex := (C.uint32_t)(firstIndex)
	c_baseVertex := (C.int32_t)(baseVertex)
	c_firstInstance := (C.uint32_t)(firstInstance)
	C.wgpuRenderBundleEncoderDrawIndexed(c_r, c_indexCount, c_instanceCount, c_firstIndex, c_baseVertex, c_firstInstance)
}

func RenderBundleEncoderDrawIndirect(r RenderBundleEncoder, indirectBuffer Buffer, indirectOffset uint64) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	c_indirectBuffer := (C.WGPUBuffer)(unsafe.Pointer(indirectBuffer))
	c_indirectOffset := (C.uint64_t)(indirectOffset)
	C.wgpuRenderBundleEncoderDrawIndirect(c_r, c_indirectBuffer, c_indirectOffset)
}

func RenderBundleEncoderDrawIndexedIndirect(r RenderBundleEncoder, indirectBuffer Buffer, indirectOffset uint64) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	c_indirectBuffer := (C.WGPUBuffer)(unsafe.Pointer(indirectBuffer))
	c_indirectOffset := (C.uint64_t)(indirectOffset)
	C.wgpuRenderBundleEncoderDrawIndexedIndirect(c_r, c_indirectBuffer, c_indirectOffset)
}

func RenderBundleEncoderInsertDebugMarker(r RenderBundleEncoder, markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_markerLabel := cgoStringView(markerLabel, &pinner)
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	C.wgpuRenderBundleEncoderInsertDebugMarker(c_r, c_markerLabel)
}

func RenderBundleEncoderPopDebugGroup(r RenderBundleEncoder) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	C.wgpuRenderBundleEncoderPopDebugGroup(c_r)
}

func RenderBundleEncoderPushDebugGroup(r RenderBundleEncoder, groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_groupLabel := cgoStringView(groupLabel, &pinner)
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	C.wgpuRenderBundleEncoderPushDebugGroup(c_r, c_groupLabel)
}

func RenderBundleEncoderSetVertexBuffer(r RenderBundleEncoder, slot uint32, buffer Buffer, offset uint64, size uint64) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	c_slot := (C.uint32_t)(slot)
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer))
	c_offset := (C.uint64_t)(offset)
	c_size := (C.uint64_t)(size)
	C.wgpuRenderBundleEncoderSetVertexBuffer(c_r, c_slot, c_buffer, c_offset, c_size)
}

func RenderBundleEncoderSetIndexBuffer(r RenderBundleEncoder, buffer Buffer, format IndexFormat, offset uint64, size uint64) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer))
	c_format := (C.WGPUIndexFormat)(format)
	c_offset := (C.uint64_t)(offset)
	c_size := (C.uint64_t)(size)
	C.wgpuRenderBundleEncoderSetIndexBuffer(c_r, c_buffer, c_format, c_offset, c_size)
}

func RenderBundleEncoderFinish(r RenderBundleEncoder, descriptor *RenderBundleDescriptor) RenderBundle {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	c_descriptor := (*C.WGPURenderBundleDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuRenderBundleEncoderFinish(c_r, c_descriptor)
	return RenderBundle(unsafe.Pointer(c_result))
}

func RenderBundleEncoderSetLabel(r RenderBundleEncoder, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r))
	C.wgpuRenderBundleEncoderSetLabel(c_r, c_label)
}

// RenderBundleEncoderRelease calls wgpuRenderBundleEncoderRelease.
func RenderBundleEncoderRelease(r RenderBundleEncoder) {
	releaseRenderBundleEncoder(unsafe.Pointer(r))
}

func RenderPassEncoderSetPipeline(r RenderPassEncoder, pipeline RenderPipeline) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_pipeline := (C.WGPURenderPipeline)(unsafe.Pointer(pipeline))
	C.wgpuRenderPassEncoderSetPipeline(c_r, c_pipeline)
}

func RenderPassEncoderSetBindGroup(r RenderPassEncoder, groupIndex uint32, group BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_groupIndex := (C.uint32_t)(groupIndex)
	c_group := (C.WGPUBindGroup)(unsafe.Pointer(group))
	var c_dynamicOffsets_ptr *C.uint32_t
	if len(dynamicOffsets) > 0 {
		c_dynamicOffsets_ptr = (*C.uint32_t)(unsafe.Pointer(&dynamicOffsets[0]))
	}
	c_dynamicOffsets_count := (C.size_t)(len(dynamicOffsets))
	C.wgpuRenderPassEncoderSetBindGroup(c_r, c_groupIndex, c_group, c_dynamicOffsets_count, c_dynamicOffsets_ptr)
}

func RenderPassEncoderSetImmediates(r RenderPassEncoder, offset uint32, data unsafe.Pointer, size uintptr) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_offset := (C.uint32_t)(offset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	C.wgpuRenderPassEncoderSetImmediates(c_r, c_offset, c_data, c_size)
}

func RenderPassEncoderDraw(r RenderPassEncoder, vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_vertexCount := (C.uint32_t)(vertexCount)
	c_instanceCount := (C.uint32_t)(instanceCount)
	c_firstVertex := (C.uint32_t)(firstVertex)
	c_firstInstance := (C.uint32_t)(firstInstance)
	C.wgpuRenderPassEncoderDraw(c_r, c_vertexCount, c_instanceCount, c_firstVertex, c_firstInstance)
}

func RenderPassEncoderDrawIndexed(r RenderPassEncoder, indexCount uint32, instanceCount uint32, firstIndex uint32, baseVertex int32, firstInstance uint32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_indexCount := (C.uint32_t)(indexCount)
	c_instanceCount := (C.uint32_t)(instanceCount)
	c_firstIndex := (C.uint32_t)(firstIndex)
	c_baseVertex := (C.int32_t)(baseVertex)
	c_firstInstance := (C.uint32_t)(firstInstance)
	C.wgpuRenderPassEncoderDrawIndexed(c_r, c_indexCount, c_instanceCount, c_firstIndex, c_baseVertex, c_firstInstance)
}

func RenderPassEncoderDrawIndirect(r RenderPassEncoder, indirectBuffer Buffer, indirectOffset uint64) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_indirectBuffer := (C.WGPUBuffer)(unsafe.Pointer(indirectBuffer))
	c_indirectOffset := (C.uint64_t)(indirectOffset)
	C.wgpuRenderPassEncoderDrawIndirect(c_r, c_indirectBuffer, c_indirectOffset)
}

func RenderPassEncoderDrawIndexedIndirect(r RenderPassEncoder, indirectBuffer Buffer, indirectOffset uint64) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_indirectBuffer := (C.WGPUBuffer)(unsafe.Pointer(indirectBuffer))
	c_indirectOffset := (C.uint64_t)(indirectOffset)
	C.wgpuRenderPassEncoderDrawIndexedIndirect(c_r, c_indirectBuffer, c_indirectOffset)
}

func RenderPassEncoderExecuteBundles(r RenderPassEncoder, bundles []RenderBundle) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(bundles) > 0 {
		pinner.Pin(&bundles[0])
	}
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	var c_bundles_ptr *C.WGPURenderBundle
	if len(bundles) > 0 {
		c_bundles_ptr = (*C.WGPURenderBundle)(unsafe.Pointer(&bundles[0]))
	}
	c_bundles_count := (C.size_t)(len(bundles))
	C.wgpuRenderPassEncoderExecuteBundles(c_r, c_bundles_count, c_bundles_ptr)
}

func RenderPassEncoderInsertDebugMarker(r RenderPassEncoder, markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_markerLabel := cgoStringView(markerLabel, &pinner)
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	C.wgpuRenderPassEncoderInsertDebugMarker(c_r, c_markerLabel)
}

func RenderPassEncoderPopDebugGroup(r RenderPassEncoder) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	C.wgpuRenderPassEncoderPopDebugGroup(c_r)
}

func RenderPassEncoderPushDebugGroup(r RenderPassEncoder, groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_groupLabel := cgoStringView(groupLabel, &pinner)
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	C.wgpuRenderPassEncoderPushDebugGroup(c_r, c_groupLabel)
}

func RenderPassEncoderSetStencilReference(r RenderPassEncoder, reference uint32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_reference := (C.uint32_t)(reference)
	C.wgpuRenderPassEncoderSetStencilReference(c_r, c_reference)
}

func RenderPassEncoderSetBlendConstant(r RenderPassEncoder, color *Color) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if color != nil {
		pinner.Pin(color)
	}
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_color := (*C.WGPUColor)(unsafe.Pointer(color))
	C.wgpuRenderPassEncoderSetBlendConstant(c_r, c_color)
}

// TODO
//
// If any argument is non-finite, produces a @ref NonFiniteFloatValueError.

func RenderPassEncoderSetViewport(r RenderPassEncoder, x float32, y float32, width float32, height float32, minDepth float32, maxDepth float32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_x := (C.float)(x)
	c_y := (C.float)(y)
	c_width := (C.float)(width)
	c_height := (C.float)(height)
	c_minDepth := (C.float)(minDepth)
	c_maxDepth := (C.float)(maxDepth)
	C.wgpuRenderPassEncoderSetViewport(c_r, c_x, c_y, c_width, c_height, c_minDepth, c_maxDepth)
}

func RenderPassEncoderSetScissorRect(r RenderPassEncoder, x uint32, y uint32, width uint32, height uint32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_x := (C.uint32_t)(x)
	c_y := (C.uint32_t)(y)
	c_width := (C.uint32_t)(width)
	c_height := (C.uint32_t)(height)
	C.wgpuRenderPassEncoderSetScissorRect(c_r, c_x, c_y, c_width, c_height)
}

func RenderPassEncoderSetVertexBuffer(r RenderPassEncoder, slot uint32, buffer Buffer, offset uint64, size uint64) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_slot := (C.uint32_t)(slot)
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer))
	c_offset := (C.uint64_t)(offset)
	c_size := (C.uint64_t)(size)
	C.wgpuRenderPassEncoderSetVertexBuffer(c_r, c_slot, c_buffer, c_offset, c_size)
}

func RenderPassEncoderSetIndexBuffer(r RenderPassEncoder, buffer Buffer, format IndexFormat, offset uint64, size uint64) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer))
	c_format := (C.WGPUIndexFormat)(format)
	c_offset := (C.uint64_t)(offset)
	c_size := (C.uint64_t)(size)
	C.wgpuRenderPassEncoderSetIndexBuffer(c_r, c_buffer, c_format, c_offset, c_size)
}

func RenderPassEncoderBeginOcclusionQuery(r RenderPassEncoder, queryIndex uint32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	c_queryIndex := (C.uint32_t)(queryIndex)
	C.wgpuRenderPassEncoderBeginOcclusionQuery(c_r, c_queryIndex)
}

func RenderPassEncoderEndOcclusionQuery(r RenderPassEncoder) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	C.wgpuRenderPassEncoderEndOcclusionQuery(c_r)
}

func RenderPassEncoderEnd(r RenderPassEncoder) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	C.wgpuRenderPassEncoderEnd(c_r)
}

func RenderPassEncoderSetLabel(r RenderPassEncoder, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r))
	C.wgpuRenderPassEncoderSetLabel(c_r, c_label)
}

// RenderPassEncoderRelease calls wgpuRenderPassEncoderRelease.
func RenderPassEncoderRelease(r RenderPassEncoder) {
	releaseRenderPassEncoder(unsafe.Pointer(r))
}

func RenderPipelineGetBindGroupLayout(r RenderPipeline, groupIndex uint32) BindGroupLayout {
	c_r := (C.WGPURenderPipeline)(unsafe.Pointer(r))
	c_groupIndex := (C.uint32_t)(groupIndex)
	c_result := C.wgpuRenderPipelineGetBindGroupLayout(c_r, c_groupIndex)
	return BindGroupLayout(unsafe.Pointer(c_result))
}

func RenderPipelineSetLabel(r RenderPipeline, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_r := (C.WGPURenderPipeline)(unsafe.Pointer(r))
	C.wgpuRenderPipelineSetLabel(c_r, c_label)
}

// RenderPipelineRelease calls wgpuRenderPipelineRelease.
func RenderPipelineRelease(r RenderPipeline) {
	releaseRenderPipeline(unsafe.Pointer(r))
}

func SamplerSetLabel(s Sampler, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_s := (C.WGPUSampler)(unsafe.Pointer(s))
	C.wgpuSamplerSetLabel(c_s, c_label)
}

// SamplerRelease calls wgpuSamplerRelease.
func SamplerRelease(s Sampler) {
	releaseSampler(unsafe.Pointer(s))
}

func ShaderModuleGetCompilationInfo(s ShaderModule, callbackInfo CompilationInfoCallbackInfo) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&callbackInfo)
	c_s := (C.WGPUShaderModule)(unsafe.Pointer(s))
	c_callbackInfo := *(*C.WGPUCompilationInfoCallbackInfo)(unsafe.Pointer(&callbackInfo))
	c_result := C.wgpuShaderModuleGetCompilationInfo(c_s, c_callbackInfo)
	return Future{Id: uint64(c_result.id)}
}

func ShaderModuleSetLabel(s ShaderModule, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_s := (C.WGPUShaderModule)(unsafe.Pointer(s))
	C.wgpuShaderModuleSetLabel(c_s, c_label)
}

// ShaderModuleRelease calls wgpuShaderModuleRelease.
func ShaderModuleRelease(s ShaderModule) {
	releaseShaderModule(unsafe.Pointer(s))
}

// Configures parameters for rendering to `surface`.
// Produces a @ref DeviceError for all content-timeline errors defined by the WebGPU specification.
//
// See @ref Surface-Configuration for more details.

func SurfaceConfigure(s Surface, config *SurfaceConfiguration) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if config != nil {
		pinner.Pin(config)
		if config.NextInChain != nil {
			pinner.Pin(config.NextInChain)
		}
		if config.ViewFormats != nil {
			pinner.Pin(config.ViewFormats)
		}
	}
	c_s := (C.WGPUSurface)(unsafe.Pointer(s))
	c_config := (*C.WGPUSurfaceConfiguration)(unsafe.Pointer(config))
	C.wgpuSurfaceConfigure(c_s, c_config)
}

// Provides information on how `adapter` is able to use `surface`.
// See @ref Surface-Capabilities for more details.

func SurfaceGetCapabilities(s Surface, adapter Adapter, capabilities *SurfaceCapabilities) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if capabilities != nil {
		pinner.Pin(capabilities)
		if capabilities.NextInChain != nil {
			pinner.Pin(capabilities.NextInChain)
		}
		if capabilities.Formats != nil {
			pinner.Pin(capabilities.Formats)
		}
		if capabilities.PresentModes != nil {
			pinner.Pin(capabilities.PresentModes)
		}
		if capabilities.AlphaModes != nil {
			pinner.Pin(capabilities.AlphaModes)
		}
	}
	c_s := (C.WGPUSurface)(unsafe.Pointer(s))
	c_adapter := (C.WGPUAdapter)(unsafe.Pointer(adapter))
	c_capabilities := (*C.WGPUSurfaceCapabilities)(unsafe.Pointer(capabilities))
	c_result := C.wgpuSurfaceGetCapabilities(c_s, c_adapter, c_capabilities)
	return Status(c_result)
}

// Returns the @ref WGPUTexture to render to `surface` this frame along with metadata on the frame.
// Returns `NULL` and @ref WGPUSurfaceGetCurrentTextureStatus_Error if the surface is not configured.
//
// See @ref Surface-Presenting for more details.

func SurfaceGetCurrentTexture(s Surface, surfaceTexture *SurfaceTexture) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if surfaceTexture != nil {
		pinner.Pin(surfaceTexture)
		if surfaceTexture.NextInChain != nil {
			pinner.Pin(surfaceTexture.NextInChain)
		}
	}
	c_s := (C.WGPUSurface)(unsafe.Pointer(s))
	c_surfaceTexture := (*C.WGPUSurfaceTexture)(unsafe.Pointer(surfaceTexture))
	C.wgpuSurfaceGetCurrentTexture(c_s, c_surfaceTexture)
}

// Shows `surface`'s current texture to the user.
// See @ref Surface-Presenting for more details.

func SurfacePresent(s Surface) Status {
	c_s := (C.WGPUSurface)(unsafe.Pointer(s))
	c_result := C.wgpuSurfacePresent(c_s)
	return Status(c_result)
}

// Removes the configuration for `surface`.
// See @ref Surface-Configuration for more details.

func SurfaceUnconfigure(s Surface) {
	c_s := (C.WGPUSurface)(unsafe.Pointer(s))
	C.wgpuSurfaceUnconfigure(c_s)
}

// Modifies the label used to refer to `surface`.

func SurfaceSetLabel(s Surface, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_s := (C.WGPUSurface)(unsafe.Pointer(s))
	C.wgpuSurfaceSetLabel(c_s, c_label)
}

// SurfaceRelease calls wgpuSurfaceRelease.
func SurfaceRelease(s Surface) {
	releaseSurface(unsafe.Pointer(s))
}

func TextureCreateView(t Texture, descriptor *TextureViewDescriptor) TextureView {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	c_descriptor := (*C.WGPUTextureViewDescriptor)(unsafe.Pointer(descriptor))
	c_result := C.wgpuTextureCreateView(c_t, c_descriptor)
	return TextureView(unsafe.Pointer(c_result))
}

func TextureSetLabel(t Texture, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	C.wgpuTextureSetLabel(c_t, c_label)
}

func TextureGetWidth(t Texture) uint32 {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	c_result := C.wgpuTextureGetWidth(c_t)
	return (uint32)(c_result)
}

func TextureGetHeight(t Texture) uint32 {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	c_result := C.wgpuTextureGetHeight(c_t)
	return (uint32)(c_result)
}

func TextureGetDepthOrArrayLayers(t Texture) uint32 {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	c_result := C.wgpuTextureGetDepthOrArrayLayers(c_t)
	return (uint32)(c_result)
}

func TextureGetMipLevelCount(t Texture) uint32 {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	c_result := C.wgpuTextureGetMipLevelCount(c_t)
	return (uint32)(c_result)
}

func TextureGetSampleCount(t Texture) uint32 {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	c_result := C.wgpuTextureGetSampleCount(c_t)
	return (uint32)(c_result)
}

func TextureGetDimension(t Texture) TextureDimension {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	c_result := C.wgpuTextureGetDimension(c_t)
	return (TextureDimension)(c_result)
}

func TextureGetTextureBindingViewDimension(t Texture) TextureViewDimension {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	c_result := C.wgpuTextureGetTextureBindingViewDimension(c_t)
	return (TextureViewDimension)(c_result)
}

func TextureGetFormat(t Texture) TextureFormat {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	c_result := C.wgpuTextureGetFormat(c_t)
	return (TextureFormat)(c_result)
}

func TextureGetUsage(t Texture) TextureUsage {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	c_result := C.wgpuTextureGetUsage(c_t)
	return (TextureUsage)(c_result)
}

func TextureDestroy(t Texture) {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t))
	C.wgpuTextureDestroy(c_t)
}

// TextureRelease calls wgpuTextureRelease.
func TextureRelease(t Texture) {
	releaseTexture(unsafe.Pointer(t))
}

func TextureViewSetLabel(t TextureView, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_label := cgoStringView(label, &pinner)
	c_t := (C.WGPUTextureView)(unsafe.Pointer(t))
	C.wgpuTextureViewSetLabel(c_t, c_label)
}

// TextureViewRelease calls wgpuTextureViewRelease.
func TextureViewRelease(t TextureView) {
	releaseTextureView(unsafe.Pointer(t))
}
