// Code generated by gen; DO NOT EDIT.

package webgpu

func NewBindGroupEntry() BindGroupEntry {
	return BindGroupEntry{
		Size: WholeSize,
	}
}

func NewBindGroupLayoutEntry() BindGroupLayoutEntry {
	return BindGroupLayoutEntry{
		Visibility:     ShaderStageNone,
		Buffer:         BufferBindingLayout{},
		Sampler:        SamplerBindingLayout{},
		Texture:        TextureBindingLayout{},
		StorageTexture: StorageTextureBindingLayout{},
	}
}

func NewBufferBindingLayout() BufferBindingLayout {
	return BufferBindingLayout{
		HasDynamicOffset: False,
		MinBindingSize:   0,
	}
}

func NewBufferDescriptor() BufferDescriptor {
	return BufferDescriptor{
		Usage:            BufferUsageNone,
		MappedAtCreation: False,
	}
}

func NewColorTargetState() ColorTargetState {
	return ColorTargetState{
		WriteMask: ColorWriteMaskAll,
	}
}

func NewCompatibilityModeLimits() CompatibilityModeLimits {
	return CompatibilityModeLimits{
		SType:                             STypeCompatibilityModeLimits,
		MaxStorageBuffersInVertexStage:    LimitU32Undefined,
		MaxStorageTexturesInVertexStage:   LimitU32Undefined,
		MaxStorageBuffersInFragmentStage:  LimitU32Undefined,
		MaxStorageTexturesInFragmentStage: LimitU32Undefined,
	}
}

func NewDepthStencilState() DepthStencilState {
	return DepthStencilState{
		StencilReadMask:     0xFFFFFFFF,
		StencilWriteMask:    0xFFFFFFFF,
		DepthBias:           0,
		DepthBiasSlopeScale: 0,
		DepthBiasClamp:      0,
	}
}

func NewExtent3D() Extent3D {
	return Extent3D{
		Height:             1,
		DepthOrArrayLayers: 1,
	}
}

func NewExternalTextureBindingEntry() ExternalTextureBindingEntry {
	return ExternalTextureBindingEntry{
		SType: STypeExternalTextureBindingEntry,
	}
}

func NewExternalTextureBindingLayout() ExternalTextureBindingLayout {
	return ExternalTextureBindingLayout{
		SType: STypeExternalTextureBindingLayout,
	}
}

func NewLimits() Limits {
	return Limits{
		MaxTextureDimension1D:                     LimitU32Undefined,
		MaxTextureDimension2D:                     LimitU32Undefined,
		MaxTextureDimension3D:                     LimitU32Undefined,
		MaxTextureArrayLayers:                     LimitU32Undefined,
		MaxBindGroups:                             LimitU32Undefined,
		MaxBindGroupsPlusVertexBuffers:            LimitU32Undefined,
		MaxBindingsPerBindGroup:                   LimitU32Undefined,
		MaxDynamicUniformBuffersPerPipelineLayout: LimitU32Undefined,
		MaxDynamicStorageBuffersPerPipelineLayout: LimitU32Undefined,
		MaxSampledTexturesPerShaderStage:          LimitU32Undefined,
		MaxSamplersPerShaderStage:                 LimitU32Undefined,
		MaxStorageBuffersPerShaderStage:           LimitU32Undefined,
		MaxStorageTexturesPerShaderStage:          LimitU32Undefined,
		MaxUniformBuffersPerShaderStage:           LimitU32Undefined,
		MaxUniformBufferBindingSize:               LimitU64Undefined,
		MaxStorageBufferBindingSize:               LimitU64Undefined,
		MinUniformBufferOffsetAlignment:           LimitU32Undefined,
		MinStorageBufferOffsetAlignment:           LimitU32Undefined,
		MaxVertexBuffers:                          LimitU32Undefined,
		MaxBufferSize:                             LimitU64Undefined,
		MaxVertexAttributes:                       LimitU32Undefined,
		MaxVertexBufferArrayStride:                LimitU32Undefined,
		MaxInterStageShaderVariables:              LimitU32Undefined,
		MaxColorAttachments:                       LimitU32Undefined,
		MaxColorAttachmentBytesPerSample:          LimitU32Undefined,
		MaxComputeWorkgroupStorageSize:            LimitU32Undefined,
		MaxComputeInvocationsPerWorkgroup:         LimitU32Undefined,
		MaxComputeWorkgroupSizeX:                  LimitU32Undefined,
		MaxComputeWorkgroupSizeY:                  LimitU32Undefined,
		MaxComputeWorkgroupSizeZ:                  LimitU32Undefined,
		MaxComputeWorkgroupsPerDimension:          LimitU32Undefined,
		MaxImmediateSize:                          LimitU32Undefined,
	}
}

func NewMultisampleState() MultisampleState {
	return MultisampleState{
		Count:                  1,
		Mask:                   0xFFFFFFFF,
		AlphaToCoverageEnabled: False,
	}
}

func NewOrigin3D() Origin3D {
	return Origin3D{
		X: 0,
		Y: 0,
		Z: 0,
	}
}

func NewPassTimestampWrites() PassTimestampWrites {
	return PassTimestampWrites{
		BeginningOfPassWriteIndex: QuerySetIndexUndefined,
		EndOfPassWriteIndex:       QuerySetIndexUndefined,
	}
}

func NewPipelineLayoutDescriptor() PipelineLayoutDescriptor {
	return PipelineLayoutDescriptor{
		ImmediateSize: 0,
	}
}

func NewPrimitiveState() PrimitiveState {
	return PrimitiveState{
		UnclippedDepth: False,
	}
}

func NewRenderBundleEncoderDescriptor() RenderBundleEncoderDescriptor {
	return RenderBundleEncoderDescriptor{
		SampleCount:     1,
		DepthReadOnly:   False,
		StencilReadOnly: False,
	}
}

func NewRenderPassColorAttachment() RenderPassColorAttachment {
	return RenderPassColorAttachment{
		DepthSlice: DepthSliceUndefined,
	}
}

func NewRenderPassDepthStencilAttachment() RenderPassDepthStencilAttachment {
	return RenderPassDepthStencilAttachment{
		DepthClearValue: &DepthClearValueUndefined,
		DepthReadOnly:   False,
		StencilReadOnly: False,
	}
}

func NewRenderPassMaxDrawCount() RenderPassMaxDrawCount {
	return RenderPassMaxDrawCount{
		SType:        STypeRenderPassMaxDrawCount,
		MaxDrawCount: 50000000,
	}
}

func NewRequestAdapterOptions() RequestAdapterOptions {
	return RequestAdapterOptions{
		ForceFallbackAdapter: False,
	}
}

func NewRequestAdapterWebXROptions() RequestAdapterWebXROptions {
	return RequestAdapterWebXROptions{
		SType:        STypeRequestAdapterWebXROptions,
		XrCompatible: False,
	}
}

func NewSamplerDescriptor() SamplerDescriptor {
	return SamplerDescriptor{
		LodMinClamp:   0,
		LodMaxClamp:   32,
		MaxAnisotropy: 1,
	}
}

func NewShaderSourceSPIRV() ShaderSourceSPIRV {
	return ShaderSourceSPIRV{
		SType:    STypeShaderSourceSPIRV,
		CodeSize: 0,
	}
}

func NewShaderSourceWGSL() ShaderSourceWGSL {
	return ShaderSourceWGSL{
		SType: STypeShaderSourceWGSL,
	}
}

func NewSurfaceColorManagement() SurfaceColorManagement {
	return SurfaceColorManagement{
		SType: STypeSurfaceColorManagement,
	}
}

func NewSurfaceConfiguration() SurfaceConfiguration {
	return SurfaceConfiguration{
		Usage:     TextureUsageRenderAttachment,
		AlphaMode: CompositeAlphaModeAuto,
	}
}

func NewSurfaceSourceAndroidNativeWindow() SurfaceSourceAndroidNativeWindow {
	return SurfaceSourceAndroidNativeWindow{
		SType: STypeSurfaceSourceAndroidNativeWindow,
	}
}

func NewSurfaceSourceMetalLayer() SurfaceSourceMetalLayer {
	return SurfaceSourceMetalLayer{
		SType: STypeSurfaceSourceMetalLayer,
	}
}

func NewSurfaceSourceWaylandSurface() SurfaceSourceWaylandSurface {
	return SurfaceSourceWaylandSurface{
		SType: STypeSurfaceSourceWaylandSurface,
	}
}

func NewSurfaceSourceWindowsHWND() SurfaceSourceWindowsHWND {
	return SurfaceSourceWindowsHWND{
		SType: STypeSurfaceSourceWindowsHWND,
	}
}

func NewSurfaceSourceXCBWindow() SurfaceSourceXCBWindow {
	return SurfaceSourceXCBWindow{
		SType: STypeSurfaceSourceXCBWindow,
	}
}

func NewSurfaceSourceXlibWindow() SurfaceSourceXlibWindow {
	return SurfaceSourceXlibWindow{
		SType: STypeSurfaceSourceXlibWindow,
	}
}

func NewTexelCopyBufferLayout() TexelCopyBufferLayout {
	return TexelCopyBufferLayout{
		Offset:       0,
		BytesPerRow:  CopyStrideUndefined,
		RowsPerImage: CopyStrideUndefined,
	}
}

func NewTexelCopyTextureInfo() TexelCopyTextureInfo {
	return TexelCopyTextureInfo{
		MipLevel: 0,
	}
}

func NewTextureBindingLayout() TextureBindingLayout {
	return TextureBindingLayout{
		Multisampled: False,
	}
}

func NewTextureBindingViewDimension() TextureBindingViewDimension {
	return TextureBindingViewDimension{
		SType: STypeTextureBindingViewDimension,
	}
}

func NewTextureComponentSwizzleDescriptor() TextureComponentSwizzleDescriptor {
	return TextureComponentSwizzleDescriptor{
		SType: STypeTextureComponentSwizzleDescriptor,
	}
}

func NewTextureDescriptor() TextureDescriptor {
	return TextureDescriptor{
		Usage:         TextureUsageNone,
		MipLevelCount: 1,
		SampleCount:   1,
	}
}

func NewTextureViewDescriptor() TextureViewDescriptor {
	return TextureViewDescriptor{
		BaseMipLevel:    0,
		MipLevelCount:   MipLevelCountUndefined,
		BaseArrayLayer:  0,
		ArrayLayerCount: ArrayLayerCountUndefined,
		Usage:           TextureUsageNone,
	}
}
