// Code generated by gen; DO NOT EDIT.
//go:build cgo && webgpu_dynload && !windows

// Package webgpu runtime-loading backend for macOS and Linux.
//
// Instead of linking wgpu_native at build time, this file turns on the C
// forwarders in webgpu_shim.c and resolves every wgpu* symbol through dlopen
// at startup. The Go call wrappers are shared with the linker-based backend.
package webgpu

/*
#cgo CFLAGS: -I${SRCDIR}/../third_party/webgpu-headers -DWGPU_DYNLOAD
#cgo linux LDFLAGS: -ldl
#include <stdlib.h>
void wgpuLoadLibrary(const char *path);
*/
import "C"

import (
	"os"
	"path/filepath"
	"runtime"
	"unsafe"
)

// loadLibrary resolves the shared-library path and hands it to the C shim.
func loadLibrary() {
	path := resolveLibraryPath()
	cpath := C.CString(path)
	defer C.free(unsafe.Pointer(cpath))
	C.wgpuLoadLibrary(cpath)
}

// resolveLibraryPath picks the wgpu_native shared library to dlopen.
// Search order: WGPU_NATIVE_DLL, next to the executable, third_party, bare name.
func resolveLibraryPath() string {
	name := "libwgpu_native.so"
	if runtime.GOOS == "darwin" {
		name = "libwgpu_native.dylib"
	}
	if p := os.Getenv("WGPU_NATIVE_DLL"); p != "" {
		return p
	}
	if exe, err := os.Executable(); err == nil {
		if p := filepath.Join(filepath.Dir(exe), name); fileExists(p) {
			return p
		}
	}
	if _, file, _, ok := runtime.Caller(0); ok {
		pattern := filepath.Join(filepath.Dir(file), "..", "third_party", "wgpu-native", runtime.GOOS+"-*", "lib", name)
		if matches, err := filepath.Glob(pattern); err == nil && len(matches) > 0 {
			return matches[0]
		}
	}
	return name
}

func fileExists(p string) bool {
	st, err := os.Stat(p)
	return err == nil && !st.IsDir()
}

func init() {
	loadLibrary()
}
