// Code generated by gen; DO NOT EDIT.
//go:build windows && !cgo

package webgpu

import (
	"runtime"
	"syscall"
	"unsafe"
)

// ---------------------------------------------------------------------------
// DLL and function procs
// ---------------------------------------------------------------------------

var (
	webgpuDLL                                        = syscall.NewLazyDLL("webgpu.dll")
	procCreateInstance                               = webgpuDLL.NewProc("wgpuCreateInstance")
	procGetInstanceFeatures                          = webgpuDLL.NewProc("wgpuGetInstanceFeatures")
	procGetInstanceLimits                            = webgpuDLL.NewProc("wgpuGetInstanceLimits")
	procHasInstanceFeature                           = webgpuDLL.NewProc("wgpuHasInstanceFeature")
	procAdapterGetLimits                             = webgpuDLL.NewProc("wgpuAdapterGetLimits")
	procAdapterHasFeature                            = webgpuDLL.NewProc("wgpuAdapterHasFeature")
	procAdapterGetFeatures                           = webgpuDLL.NewProc("wgpuAdapterGetFeatures")
	procAdapterGetInfo                               = webgpuDLL.NewProc("wgpuAdapterGetInfo")
	procAdapterRequestDevice                         = webgpuDLL.NewProc("wgpuAdapterRequestDevice")
	procBindGroupSetLabel                            = webgpuDLL.NewProc("wgpuBindGroupSetLabel")
	procBindGroupLayoutSetLabel                      = webgpuDLL.NewProc("wgpuBindGroupLayoutSetLabel")
	procBufferMapAsync                               = webgpuDLL.NewProc("wgpuBufferMapAsync")
	procBufferGetMappedRange                         = webgpuDLL.NewProc("wgpuBufferGetMappedRange")
	procBufferGetConstMappedRange                    = webgpuDLL.NewProc("wgpuBufferGetConstMappedRange")
	procBufferReadMappedRange                        = webgpuDLL.NewProc("wgpuBufferReadMappedRange")
	procBufferWriteMappedRange                       = webgpuDLL.NewProc("wgpuBufferWriteMappedRange")
	procBufferSetLabel                               = webgpuDLL.NewProc("wgpuBufferSetLabel")
	procBufferGetUsage                               = webgpuDLL.NewProc("wgpuBufferGetUsage")
	procBufferGetSize                                = webgpuDLL.NewProc("wgpuBufferGetSize")
	procBufferGetMapState                            = webgpuDLL.NewProc("wgpuBufferGetMapState")
	procBufferUnmap                                  = webgpuDLL.NewProc("wgpuBufferUnmap")
	procBufferDestroy                                = webgpuDLL.NewProc("wgpuBufferDestroy")
	procCommandBufferSetLabel                        = webgpuDLL.NewProc("wgpuCommandBufferSetLabel")
	procCommandEncoderFinish                         = webgpuDLL.NewProc("wgpuCommandEncoderFinish")
	procCommandEncoderBeginComputePass               = webgpuDLL.NewProc("wgpuCommandEncoderBeginComputePass")
	procCommandEncoderBeginRenderPass                = webgpuDLL.NewProc("wgpuCommandEncoderBeginRenderPass")
	procCommandEncoderCopyBufferToBuffer             = webgpuDLL.NewProc("wgpuCommandEncoderCopyBufferToBuffer")
	procCommandEncoderCopyBufferToTexture            = webgpuDLL.NewProc("wgpuCommandEncoderCopyBufferToTexture")
	procCommandEncoderCopyTextureToBuffer            = webgpuDLL.NewProc("wgpuCommandEncoderCopyTextureToBuffer")
	procCommandEncoderCopyTextureToTexture           = webgpuDLL.NewProc("wgpuCommandEncoderCopyTextureToTexture")
	procCommandEncoderClearBuffer                    = webgpuDLL.NewProc("wgpuCommandEncoderClearBuffer")
	procCommandEncoderInsertDebugMarker              = webgpuDLL.NewProc("wgpuCommandEncoderInsertDebugMarker")
	procCommandEncoderPopDebugGroup                  = webgpuDLL.NewProc("wgpuCommandEncoderPopDebugGroup")
	procCommandEncoderPushDebugGroup                 = webgpuDLL.NewProc("wgpuCommandEncoderPushDebugGroup")
	procCommandEncoderResolveQuerySet                = webgpuDLL.NewProc("wgpuCommandEncoderResolveQuerySet")
	procCommandEncoderWriteTimestamp                 = webgpuDLL.NewProc("wgpuCommandEncoderWriteTimestamp")
	procCommandEncoderSetLabel                       = webgpuDLL.NewProc("wgpuCommandEncoderSetLabel")
	procComputePassEncoderInsertDebugMarker          = webgpuDLL.NewProc("wgpuComputePassEncoderInsertDebugMarker")
	procComputePassEncoderPopDebugGroup              = webgpuDLL.NewProc("wgpuComputePassEncoderPopDebugGroup")
	procComputePassEncoderPushDebugGroup             = webgpuDLL.NewProc("wgpuComputePassEncoderPushDebugGroup")
	procComputePassEncoderSetPipeline                = webgpuDLL.NewProc("wgpuComputePassEncoderSetPipeline")
	procComputePassEncoderSetBindGroup               = webgpuDLL.NewProc("wgpuComputePassEncoderSetBindGroup")
	procComputePassEncoderSetImmediates              = webgpuDLL.NewProc("wgpuComputePassEncoderSetImmediates")
	procComputePassEncoderDispatchWorkgroups         = webgpuDLL.NewProc("wgpuComputePassEncoderDispatchWorkgroups")
	procComputePassEncoderDispatchWorkgroupsIndirect = webgpuDLL.NewProc("wgpuComputePassEncoderDispatchWorkgroupsIndirect")
	procComputePassEncoderEnd                        = webgpuDLL.NewProc("wgpuComputePassEncoderEnd")
	procComputePassEncoderSetLabel                   = webgpuDLL.NewProc("wgpuComputePassEncoderSetLabel")
	procComputePipelineGetBindGroupLayout            = webgpuDLL.NewProc("wgpuComputePipelineGetBindGroupLayout")
	procComputePipelineSetLabel                      = webgpuDLL.NewProc("wgpuComputePipelineSetLabel")
	procDeviceCreateBindGroup                        = webgpuDLL.NewProc("wgpuDeviceCreateBindGroup")
	procDeviceCreateBindGroupLayout                  = webgpuDLL.NewProc("wgpuDeviceCreateBindGroupLayout")
	procDeviceCreateBuffer                           = webgpuDLL.NewProc("wgpuDeviceCreateBuffer")
	procDeviceCreateCommandEncoder                   = webgpuDLL.NewProc("wgpuDeviceCreateCommandEncoder")
	procDeviceCreateComputePipeline                  = webgpuDLL.NewProc("wgpuDeviceCreateComputePipeline")
	procDeviceCreateComputePipelineAsync             = webgpuDLL.NewProc("wgpuDeviceCreateComputePipelineAsync")
	procDeviceCreatePipelineLayout                   = webgpuDLL.NewProc("wgpuDeviceCreatePipelineLayout")
	procDeviceCreateQuerySet                         = webgpuDLL.NewProc("wgpuDeviceCreateQuerySet")
	procDeviceCreateRenderPipelineAsync              = webgpuDLL.NewProc("wgpuDeviceCreateRenderPipelineAsync")
	procDeviceCreateRenderBundleEncoder              = webgpuDLL.NewProc("wgpuDeviceCreateRenderBundleEncoder")
	procDeviceCreateRenderPipeline                   = webgpuDLL.NewProc("wgpuDeviceCreateRenderPipeline")
	procDeviceCreateSampler                          = webgpuDLL.NewProc("wgpuDeviceCreateSampler")
	procDeviceCreateShaderModule                     = webgpuDLL.NewProc("wgpuDeviceCreateShaderModule")
	procDeviceCreateTexture                          = webgpuDLL.NewProc("wgpuDeviceCreateTexture")
	procDeviceDestroy                                = webgpuDLL.NewProc("wgpuDeviceDestroy")
	procDeviceGetLostFuture                          = webgpuDLL.NewProc("wgpuDeviceGetLostFuture")
	procDeviceGetLimits                              = webgpuDLL.NewProc("wgpuDeviceGetLimits")
	procDeviceHasFeature                             = webgpuDLL.NewProc("wgpuDeviceHasFeature")
	procDeviceGetFeatures                            = webgpuDLL.NewProc("wgpuDeviceGetFeatures")
	procDeviceGetAdapterInfo                         = webgpuDLL.NewProc("wgpuDeviceGetAdapterInfo")
	procDeviceGetQueue                               = webgpuDLL.NewProc("wgpuDeviceGetQueue")
	procDevicePushErrorScope                         = webgpuDLL.NewProc("wgpuDevicePushErrorScope")
	procDevicePopErrorScope                          = webgpuDLL.NewProc("wgpuDevicePopErrorScope")
	procDeviceSetLabel                               = webgpuDLL.NewProc("wgpuDeviceSetLabel")
	procExternalTextureSetLabel                      = webgpuDLL.NewProc("wgpuExternalTextureSetLabel")
	procInstanceCreateSurface                        = webgpuDLL.NewProc("wgpuInstanceCreateSurface")
	procInstanceGetWGSLLanguageFeatures              = webgpuDLL.NewProc("wgpuInstanceGetWGSLLanguageFeatures")
	procInstanceHasWGSLLanguageFeature               = webgpuDLL.NewProc("wgpuInstanceHasWGSLLanguageFeature")
	procInstanceProcessEvents                        = webgpuDLL.NewProc("wgpuInstanceProcessEvents")
	procInstanceRequestAdapter                       = webgpuDLL.NewProc("wgpuInstanceRequestAdapter")
	procInstanceWaitAny                              = webgpuDLL.NewProc("wgpuInstanceWaitAny")
	procPipelineLayoutSetLabel                       = webgpuDLL.NewProc("wgpuPipelineLayoutSetLabel")
	procQuerySetSetLabel                             = webgpuDLL.NewProc("wgpuQuerySetSetLabel")
	procQuerySetGetType                              = webgpuDLL.NewProc("wgpuQuerySetGetType")
	procQuerySetGetCount                             = webgpuDLL.NewProc("wgpuQuerySetGetCount")
	procQuerySetDestroy                              = webgpuDLL.NewProc("wgpuQuerySetDestroy")
	procQueueSubmit                                  = webgpuDLL.NewProc("wgpuQueueSubmit")
	procQueueOnSubmittedWorkDone                     = webgpuDLL.NewProc("wgpuQueueOnSubmittedWorkDone")
	procQueueWriteBuffer                             = webgpuDLL.NewProc("wgpuQueueWriteBuffer")
	procQueueWriteTexture                            = webgpuDLL.NewProc("wgpuQueueWriteTexture")
	procQueueSetLabel                                = webgpuDLL.NewProc("wgpuQueueSetLabel")
	procRenderBundleSetLabel                         = webgpuDLL.NewProc("wgpuRenderBundleSetLabel")
	procRenderBundleEncoderSetPipeline               = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetPipeline")
	procRenderBundleEncoderSetBindGroup              = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetBindGroup")
	procRenderBundleEncoderSetImmediates             = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetImmediates")
	procRenderBundleEncoderDraw                      = webgpuDLL.NewProc("wgpuRenderBundleEncoderDraw")
	procRenderBundleEncoderDrawIndexed               = webgpuDLL.NewProc("wgpuRenderBundleEncoderDrawIndexed")
	procRenderBundleEncoderDrawIndirect              = webgpuDLL.NewProc("wgpuRenderBundleEncoderDrawIndirect")
	procRenderBundleEncoderDrawIndexedIndirect       = webgpuDLL.NewProc("wgpuRenderBundleEncoderDrawIndexedIndirect")
	procRenderBundleEncoderInsertDebugMarker         = webgpuDLL.NewProc("wgpuRenderBundleEncoderInsertDebugMarker")
	procRenderBundleEncoderPopDebugGroup             = webgpuDLL.NewProc("wgpuRenderBundleEncoderPopDebugGroup")
	procRenderBundleEncoderPushDebugGroup            = webgpuDLL.NewProc("wgpuRenderBundleEncoderPushDebugGroup")
	procRenderBundleEncoderSetVertexBuffer           = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetVertexBuffer")
	procRenderBundleEncoderSetIndexBuffer            = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetIndexBuffer")
	procRenderBundleEncoderFinish                    = webgpuDLL.NewProc("wgpuRenderBundleEncoderFinish")
	procRenderBundleEncoderSetLabel                  = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetLabel")
	procRenderPassEncoderSetPipeline                 = webgpuDLL.NewProc("wgpuRenderPassEncoderSetPipeline")
	procRenderPassEncoderSetBindGroup                = webgpuDLL.NewProc("wgpuRenderPassEncoderSetBindGroup")
	procRenderPassEncoderSetImmediates               = webgpuDLL.NewProc("wgpuRenderPassEncoderSetImmediates")
	procRenderPassEncoderDraw                        = webgpuDLL.NewProc("wgpuRenderPassEncoderDraw")
	procRenderPassEncoderDrawIndexed                 = webgpuDLL.NewProc("wgpuRenderPassEncoderDrawIndexed")
	procRenderPassEncoderDrawIndirect                = webgpuDLL.NewProc("wgpuRenderPassEncoderDrawIndirect")
	procRenderPassEncoderDrawIndexedIndirect         = webgpuDLL.NewProc("wgpuRenderPassEncoderDrawIndexedIndirect")
	procRenderPassEncoderExecuteBundles              = webgpuDLL.NewProc("wgpuRenderPassEncoderExecuteBundles")
	procRenderPassEncoderInsertDebugMarker           = webgpuDLL.NewProc("wgpuRenderPassEncoderInsertDebugMarker")
	procRenderPassEncoderPopDebugGroup               = webgpuDLL.NewProc("wgpuRenderPassEncoderPopDebugGroup")
	procRenderPassEncoderPushDebugGroup              = webgpuDLL.NewProc("wgpuRenderPassEncoderPushDebugGroup")
	procRenderPassEncoderSetStencilReference         = webgpuDLL.NewProc("wgpuRenderPassEncoderSetStencilReference")
	procRenderPassEncoderSetBlendConstant            = webgpuDLL.NewProc("wgpuRenderPassEncoderSetBlendConstant")
	procRenderPassEncoderSetViewport                 = webgpuDLL.NewProc("wgpuRenderPassEncoderSetViewport")
	procRenderPassEncoderSetScissorRect              = webgpuDLL.NewProc("wgpuRenderPassEncoderSetScissorRect")
	procRenderPassEncoderSetVertexBuffer             = webgpuDLL.NewProc("wgpuRenderPassEncoderSetVertexBuffer")
	procRenderPassEncoderSetIndexBuffer              = webgpuDLL.NewProc("wgpuRenderPassEncoderSetIndexBuffer")
	procRenderPassEncoderBeginOcclusionQuery         = webgpuDLL.NewProc("wgpuRenderPassEncoderBeginOcclusionQuery")
	procRenderPassEncoderEndOcclusionQuery           = webgpuDLL.NewProc("wgpuRenderPassEncoderEndOcclusionQuery")
	procRenderPassEncoderEnd                         = webgpuDLL.NewProc("wgpuRenderPassEncoderEnd")
	procRenderPassEncoderSetLabel                    = webgpuDLL.NewProc("wgpuRenderPassEncoderSetLabel")
	procRenderPipelineGetBindGroupLayout             = webgpuDLL.NewProc("wgpuRenderPipelineGetBindGroupLayout")
	procRenderPipelineSetLabel                       = webgpuDLL.NewProc("wgpuRenderPipelineSetLabel")
	procSamplerSetLabel                              = webgpuDLL.NewProc("wgpuSamplerSetLabel")
	procShaderModuleGetCompilationInfo               = webgpuDLL.NewProc("wgpuShaderModuleGetCompilationInfo")
	procShaderModuleSetLabel                         = webgpuDLL.NewProc("wgpuShaderModuleSetLabel")
	procSurfaceConfigure                             = webgpuDLL.NewProc("wgpuSurfaceConfigure")
	procSurfaceGetCapabilities                       = webgpuDLL.NewProc("wgpuSurfaceGetCapabilities")
	procSurfaceGetCurrentTexture                     = webgpuDLL.NewProc("wgpuSurfaceGetCurrentTexture")
	procSurfacePresent                               = webgpuDLL.NewProc("wgpuSurfacePresent")
	procSurfaceUnconfigure                           = webgpuDLL.NewProc("wgpuSurfaceUnconfigure")
	procSurfaceSetLabel                              = webgpuDLL.NewProc("wgpuSurfaceSetLabel")
	procTextureCreateView                            = webgpuDLL.NewProc("wgpuTextureCreateView")
	procTextureSetLabel                              = webgpuDLL.NewProc("wgpuTextureSetLabel")
	procTextureGetWidth                              = webgpuDLL.NewProc("wgpuTextureGetWidth")
	procTextureGetHeight                             = webgpuDLL.NewProc("wgpuTextureGetHeight")
	procTextureGetDepthOrArrayLayers                 = webgpuDLL.NewProc("wgpuTextureGetDepthOrArrayLayers")
	procTextureGetMipLevelCount                      = webgpuDLL.NewProc("wgpuTextureGetMipLevelCount")
	procTextureGetSampleCount                        = webgpuDLL.NewProc("wgpuTextureGetSampleCount")
	procTextureGetDimension                          = webgpuDLL.NewProc("wgpuTextureGetDimension")
	procTextureGetTextureBindingViewDimension        = webgpuDLL.NewProc("wgpuTextureGetTextureBindingViewDimension")
	procTextureGetFormat                             = webgpuDLL.NewProc("wgpuTextureGetFormat")
	procTextureGetUsage                              = webgpuDLL.NewProc("wgpuTextureGetUsage")
	procTextureDestroy                               = webgpuDLL.NewProc("wgpuTextureDestroy")
	procTextureViewSetLabel                          = webgpuDLL.NewProc("wgpuTextureViewSetLabel")
)

// ---------------------------------------------------------------------------
// Syscall helpers
// ---------------------------------------------------------------------------

// wgpuStringView matches C.WGPUStringView.
type wgpuStringView struct {
	data   *byte
	length uintptr
}

func syscallStringView(s string, pinner *runtime.Pinner) wgpuStringView {
	var v wgpuStringView
	if len(s) > 0 {
		p := unsafe.StringData(s)
		pinner.Pin(p)
		v.data = p
		v.length = uintptr(len(s))
	}
	return v
}

// ---------------------------------------------------------------------------
// Syscall-based function implementations
// ---------------------------------------------------------------------------

// CreateInstance calls wgpuCreateInstance via syscall.
func CreateInstance(descriptor InstanceDescriptor) *Instance {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.RequiredFeatures != nil {
		pinner.Pin(descriptor.RequiredFeatures)
	}
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procCreateInstance.Call(descriptor_v)
	return &Instance{inner: r1}
}

// GetInstanceFeatures calls wgpuGetInstanceFeatures via syscall.
func GetInstanceFeatures(features SupportedInstanceFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&features)
	if features.Features != nil {
		pinner.Pin(features.Features)
	}
	features_v := uintptr(unsafe.Pointer(&features))
	procGetInstanceFeatures.Call(features_v)
}

// GetInstanceLimits calls wgpuGetInstanceLimits via syscall.
func GetInstanceLimits(limits InstanceLimits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&limits)
	limits_v := uintptr(unsafe.Pointer(&limits))
	r1, _, _ := procGetInstanceLimits.Call(limits_v)
	return (Status)(r1)
}

// HasInstanceFeature calls wgpuHasInstanceFeature via syscall.
func HasInstanceFeature(feature InstanceFeatureName) bool {
	feature_v := uintptr(feature)
	r1, _, _ := procHasInstanceFeature.Call(feature_v)
	return r1 != 0
}

// GetLimits calls wgpuAdapterGetLimits via syscall.
func (a *Adapter) GetLimits(limits Limits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&limits)
	a_v := uintptr(a.inner)
	limits_v := uintptr(unsafe.Pointer(&limits))
	r1, _, _ := procAdapterGetLimits.Call(a_v, limits_v)
	return (Status)(r1)
}

// HasFeature calls wgpuAdapterHasFeature via syscall.
func (a *Adapter) HasFeature(feature FeatureName) bool {
	a_v := uintptr(a.inner)
	feature_v := uintptr(feature)
	r1, _, _ := procAdapterHasFeature.Call(a_v, feature_v)
	return r1 != 0
}

// GetFeatures calls wgpuAdapterGetFeatures via syscall.
func (a *Adapter) GetFeatures(features SupportedFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&features)
	if features.Features != nil {
		pinner.Pin(features.Features)
	}
	a_v := uintptr(a.inner)
	features_v := uintptr(unsafe.Pointer(&features))
	procAdapterGetFeatures.Call(a_v, features_v)
}

// GetInfo calls wgpuAdapterGetInfo via syscall.
func (a *Adapter) GetInfo(info AdapterInfo) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&info)
	a_v := uintptr(a.inner)
	info_v := uintptr(unsafe.Pointer(&info))
	r1, _, _ := procAdapterGetInfo.Call(a_v, info_v)
	return (Status)(r1)
}

// RequestDevice calls wgpuAdapterRequestDevice via syscall.
func (a *Adapter) RequestDevice(descriptor DeviceDescriptor, callback RequestDeviceFn) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.RequiredFeatures != nil {
		pinner.Pin(descriptor.RequiredFeatures)
	}
	a_v := uintptr(a.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	_cbInfo := struct {
		next     uintptr
		mode     uint32
		callback uintptr
		ud1      uintptr
		ud2      uintptr
	}{}
	_cbInfo.mode = uint32(CallbackModeAllowProcessEvents)
	_cbInfo.callback = syscall.NewCallback(func(status, device, msg, ud1, ud2 uintptr) {
		var s string
		if msg != 0 {
			sv := (*wgpuStringView)(unsafe.Pointer(msg))
			if sv.data != nil && sv.length > 0 {
				s = unsafe.String(sv.data, int(sv.length))
			}
		}
		var h *Device
		if device != 0 {
			h = &Device{inner: device}
		}
		if fn := callback; fn != nil {
			fn(RequestDeviceStatus(status), h, s)
		}
	})
	_cbInfo_v := uintptr(unsafe.Pointer(&_cbInfo))
	r1, _, _ := procAdapterRequestDevice.Call(a_v, descriptor_v, _cbInfo_v)
	return Future{Id: uint64(r1)}
}

// SetLabel calls wgpuBindGroupSetLabel via syscall.
func (b *BindGroup) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	b_v := uintptr(b.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procBindGroupSetLabel.Call(b_v, label_v)
}

// SetLabel calls wgpuBindGroupLayoutSetLabel via syscall.
func (b *BindGroupLayout) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	b_v := uintptr(b.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procBindGroupLayoutSetLabel.Call(b_v, label_v)
}

// MapAsync calls wgpuBufferMapAsync via syscall.
func (b *Buffer) MapAsync(mode MapMode, offset uintptr, size uintptr, callback BufferMapFn) Future {
	b_v := uintptr(b.inner)
	mode_v := uintptr(mode)
	offset_v := uintptr(offset)
	size_v := uintptr(size)
	_cbInfo := struct {
		next     uintptr
		mode     uint32
		callback uintptr
		ud1      uintptr
		ud2      uintptr
	}{}
	_cbInfo.mode = uint32(CallbackModeAllowProcessEvents)
	_cbInfo.callback = syscall.NewCallback(func(status, msg, ud1, ud2, ud3 uintptr) {
		var s string
		if msg != 0 {
			sv := (*wgpuStringView)(unsafe.Pointer(msg))
			if sv.data != nil && sv.length > 0 {
				s = unsafe.String(sv.data, int(sv.length))
			}
		}
		if fn := callback; fn != nil {
			fn(MapAsyncStatus(status), s)
		}
	})
	_cbInfo_v := uintptr(unsafe.Pointer(&_cbInfo))
	r1, _, _ := procBufferMapAsync.Call(b_v, mode_v, offset_v, size_v, _cbInfo_v)
	return Future{Id: uint64(r1)}
}

// GetMappedRange calls wgpuBufferGetMappedRange via syscall.
func (b *Buffer) GetMappedRange(offset uintptr, size uintptr) unsafe.Pointer {
	b_v := uintptr(b.inner)
	offset_v := uintptr(offset)
	size_v := uintptr(size)
	r1, _, _ := procBufferGetMappedRange.Call(b_v, offset_v, size_v)
	return (unsafe.Pointer)(r1)
}

// GetConstMappedRange calls wgpuBufferGetConstMappedRange via syscall.
func (b *Buffer) GetConstMappedRange(offset uintptr, size uintptr) unsafe.Pointer {
	b_v := uintptr(b.inner)
	offset_v := uintptr(offset)
	size_v := uintptr(size)
	r1, _, _ := procBufferGetConstMappedRange.Call(b_v, offset_v, size_v)
	return (unsafe.Pointer)(r1)
}

// ReadMappedRange calls wgpuBufferReadMappedRange via syscall.
func (b *Buffer) ReadMappedRange(offset uintptr, data unsafe.Pointer, size uintptr) Status {
	b_v := uintptr(b.inner)
	offset_v := uintptr(offset)
	data_v := uintptr(data)
	size_v := uintptr(size)
	r1, _, _ := procBufferReadMappedRange.Call(b_v, offset_v, data_v, size_v)
	return (Status)(r1)
}

// WriteMappedRange calls wgpuBufferWriteMappedRange via syscall.
func (b *Buffer) WriteMappedRange(offset uintptr, data unsafe.Pointer, size uintptr) Status {
	b_v := uintptr(b.inner)
	offset_v := uintptr(offset)
	data_v := uintptr(data)
	size_v := uintptr(size)
	r1, _, _ := procBufferWriteMappedRange.Call(b_v, offset_v, data_v, size_v)
	return (Status)(r1)
}

// SetLabel calls wgpuBufferSetLabel via syscall.
func (b *Buffer) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	b_v := uintptr(b.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procBufferSetLabel.Call(b_v, label_v)
}

// GetUsage calls wgpuBufferGetUsage via syscall.
func (b *Buffer) GetUsage() BufferUsage {
	b_v := uintptr(b.inner)
	r1, _, _ := procBufferGetUsage.Call(b_v)
	return (BufferUsage)(r1)
}

// GetSize calls wgpuBufferGetSize via syscall.
func (b *Buffer) GetSize() uint64 {
	b_v := uintptr(b.inner)
	r1, _, _ := procBufferGetSize.Call(b_v)
	return (uint64)(r1)
}

// GetMapState calls wgpuBufferGetMapState via syscall.
func (b *Buffer) GetMapState() BufferMapState {
	b_v := uintptr(b.inner)
	r1, _, _ := procBufferGetMapState.Call(b_v)
	return (BufferMapState)(r1)
}

// Unmap calls wgpuBufferUnmap via syscall.
func (b *Buffer) Unmap() {
	b_v := uintptr(b.inner)
	procBufferUnmap.Call(b_v)
}

// Destroy calls wgpuBufferDestroy via syscall.
func (b *Buffer) Destroy() {
	b_v := uintptr(b.inner)
	procBufferDestroy.Call(b_v)
}

// SetLabel calls wgpuCommandBufferSetLabel via syscall.
func (c *CommandBuffer) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_v := uintptr(c.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procCommandBufferSetLabel.Call(c_v, label_v)
}

// Finish calls wgpuCommandEncoderFinish via syscall.
func (c *CommandEncoder) Finish(descriptor CommandBufferDescriptor) *CommandBuffer {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_v := uintptr(c.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procCommandEncoderFinish.Call(c_v, descriptor_v)
	return &CommandBuffer{inner: r1}
}

// BeginComputePass calls wgpuCommandEncoderBeginComputePass via syscall.
func (c *CommandEncoder) BeginComputePass(descriptor ComputePassDescriptor) *ComputePassEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_v := uintptr(c.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procCommandEncoderBeginComputePass.Call(c_v, descriptor_v)
	return &ComputePassEncoder{inner: r1}
}

// BeginRenderPass calls wgpuCommandEncoderBeginRenderPass via syscall.
func (c *CommandEncoder) BeginRenderPass(descriptor RenderPassDescriptor) *RenderPassEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.ColorAttachments != nil {
		pinner.Pin(descriptor.ColorAttachments)
	}
	c_v := uintptr(c.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procCommandEncoderBeginRenderPass.Call(c_v, descriptor_v)
	return &RenderPassEncoder{inner: r1}
}

// CopyBufferToBuffer calls wgpuCommandEncoderCopyBufferToBuffer via syscall.
func (c *CommandEncoder) CopyBufferToBuffer(source *Buffer, sourceOffset uint64, destination *Buffer, destinationOffset uint64, size uint64) {
	c_v := uintptr(c.inner)
	source_v := uintptr(source.inner)
	sourceOffset_v := uintptr(sourceOffset)
	destination_v := uintptr(destination.inner)
	destinationOffset_v := uintptr(destinationOffset)
	size_v := uintptr(size)
	procCommandEncoderCopyBufferToBuffer.Call(c_v, source_v, sourceOffset_v, destination_v, destinationOffset_v, size_v)
}

// CopyBufferToTexture calls wgpuCommandEncoderCopyBufferToTexture via syscall.
func (c *CommandEncoder) CopyBufferToTexture(source TexelCopyBufferInfo, destination TexelCopyTextureInfo, copySize Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&source)
	pinner.Pin(&destination)
	pinner.Pin(&copySize)
	c_v := uintptr(c.inner)
	source_v := uintptr(unsafe.Pointer(&source))
	destination_v := uintptr(unsafe.Pointer(&destination))
	copySize_v := uintptr(unsafe.Pointer(&copySize))
	procCommandEncoderCopyBufferToTexture.Call(c_v, source_v, destination_v, copySize_v)
}

// CopyTextureToBuffer calls wgpuCommandEncoderCopyTextureToBuffer via syscall.
func (c *CommandEncoder) CopyTextureToBuffer(source TexelCopyTextureInfo, destination TexelCopyBufferInfo, copySize Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&source)
	pinner.Pin(&destination)
	pinner.Pin(&copySize)
	c_v := uintptr(c.inner)
	source_v := uintptr(unsafe.Pointer(&source))
	destination_v := uintptr(unsafe.Pointer(&destination))
	copySize_v := uintptr(unsafe.Pointer(&copySize))
	procCommandEncoderCopyTextureToBuffer.Call(c_v, source_v, destination_v, copySize_v)
}

// CopyTextureToTexture calls wgpuCommandEncoderCopyTextureToTexture via syscall.
func (c *CommandEncoder) CopyTextureToTexture(source TexelCopyTextureInfo, destination TexelCopyTextureInfo, copySize Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&source)
	pinner.Pin(&destination)
	pinner.Pin(&copySize)
	c_v := uintptr(c.inner)
	source_v := uintptr(unsafe.Pointer(&source))
	destination_v := uintptr(unsafe.Pointer(&destination))
	copySize_v := uintptr(unsafe.Pointer(&copySize))
	procCommandEncoderCopyTextureToTexture.Call(c_v, source_v, destination_v, copySize_v)
}

// ClearBuffer calls wgpuCommandEncoderClearBuffer via syscall.
func (c *CommandEncoder) ClearBuffer(buffer *Buffer, offset uint64, size uint64) {
	c_v := uintptr(c.inner)
	buffer_v := uintptr(buffer.inner)
	offset_v := uintptr(offset)
	size_v := uintptr(size)
	procCommandEncoderClearBuffer.Call(c_v, buffer_v, offset_v, size_v)
}

// InsertDebugMarker calls wgpuCommandEncoderInsertDebugMarker via syscall.
func (c *CommandEncoder) InsertDebugMarker(markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_v := uintptr(c.inner)
	markerLabel_sv := syscallStringView(markerLabel, &pinner)
	markerLabel_v := uintptr(unsafe.Pointer(&markerLabel_sv))
	procCommandEncoderInsertDebugMarker.Call(c_v, markerLabel_v)
}

// PopDebugGroup calls wgpuCommandEncoderPopDebugGroup via syscall.
func (c *CommandEncoder) PopDebugGroup() {
	c_v := uintptr(c.inner)
	procCommandEncoderPopDebugGroup.Call(c_v)
}

// PushDebugGroup calls wgpuCommandEncoderPushDebugGroup via syscall.
func (c *CommandEncoder) PushDebugGroup(groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_v := uintptr(c.inner)
	groupLabel_sv := syscallStringView(groupLabel, &pinner)
	groupLabel_v := uintptr(unsafe.Pointer(&groupLabel_sv))
	procCommandEncoderPushDebugGroup.Call(c_v, groupLabel_v)
}

// ResolveQuerySet calls wgpuCommandEncoderResolveQuerySet via syscall.
func (c *CommandEncoder) ResolveQuerySet(querySet *QuerySet, firstQuery uint32, queryCount uint32, destination *Buffer, destinationOffset uint64) {
	c_v := uintptr(c.inner)
	querySet_v := uintptr(querySet.inner)
	firstQuery_v := uintptr(firstQuery)
	queryCount_v := uintptr(queryCount)
	destination_v := uintptr(destination.inner)
	destinationOffset_v := uintptr(destinationOffset)
	procCommandEncoderResolveQuerySet.Call(c_v, querySet_v, firstQuery_v, queryCount_v, destination_v, destinationOffset_v)
}

// WriteTimestamp calls wgpuCommandEncoderWriteTimestamp via syscall.
func (c *CommandEncoder) WriteTimestamp(querySet *QuerySet, queryIndex uint32) {
	c_v := uintptr(c.inner)
	querySet_v := uintptr(querySet.inner)
	queryIndex_v := uintptr(queryIndex)
	procCommandEncoderWriteTimestamp.Call(c_v, querySet_v, queryIndex_v)
}

// SetLabel calls wgpuCommandEncoderSetLabel via syscall.
func (c *CommandEncoder) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_v := uintptr(c.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procCommandEncoderSetLabel.Call(c_v, label_v)
}

// InsertDebugMarker calls wgpuComputePassEncoderInsertDebugMarker via syscall.
func (c *ComputePassEncoder) InsertDebugMarker(markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_v := uintptr(c.inner)
	markerLabel_sv := syscallStringView(markerLabel, &pinner)
	markerLabel_v := uintptr(unsafe.Pointer(&markerLabel_sv))
	procComputePassEncoderInsertDebugMarker.Call(c_v, markerLabel_v)
}

// PopDebugGroup calls wgpuComputePassEncoderPopDebugGroup via syscall.
func (c *ComputePassEncoder) PopDebugGroup() {
	c_v := uintptr(c.inner)
	procComputePassEncoderPopDebugGroup.Call(c_v)
}

// PushDebugGroup calls wgpuComputePassEncoderPushDebugGroup via syscall.
func (c *ComputePassEncoder) PushDebugGroup(groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_v := uintptr(c.inner)
	groupLabel_sv := syscallStringView(groupLabel, &pinner)
	groupLabel_v := uintptr(unsafe.Pointer(&groupLabel_sv))
	procComputePassEncoderPushDebugGroup.Call(c_v, groupLabel_v)
}

// SetPipeline calls wgpuComputePassEncoderSetPipeline via syscall.
func (c *ComputePassEncoder) SetPipeline(pipeline *ComputePipeline) {
	c_v := uintptr(c.inner)
	pipeline_v := uintptr(pipeline.inner)
	procComputePassEncoderSetPipeline.Call(c_v, pipeline_v)
}

// SetBindGroup calls wgpuComputePassEncoderSetBindGroup via syscall.
func (c *ComputePassEncoder) SetBindGroup(groupIndex uint32, group *BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	c_v := uintptr(c.inner)
	groupIndex_v := uintptr(groupIndex)
	group_v := uintptr(group.inner)
	var dynamicOffsets_ptr uintptr
	if len(dynamicOffsets) > 0 {
		dynamicOffsets_ptr = uintptr(unsafe.Pointer(&dynamicOffsets[0]))
	}
	dynamicOffsets_count := uintptr(len(dynamicOffsets))
	procComputePassEncoderSetBindGroup.Call(c_v, groupIndex_v, group_v, dynamicOffsets_count, dynamicOffsets_ptr)
}

// SetImmediates calls wgpuComputePassEncoderSetImmediates via syscall.
func (c *ComputePassEncoder) SetImmediates(offset uint32, data unsafe.Pointer, size uintptr) {
	c_v := uintptr(c.inner)
	offset_v := uintptr(offset)
	data_v := uintptr(data)
	size_v := uintptr(size)
	procComputePassEncoderSetImmediates.Call(c_v, offset_v, data_v, size_v)
}

// DispatchWorkgroups calls wgpuComputePassEncoderDispatchWorkgroups via syscall.
func (c *ComputePassEncoder) DispatchWorkgroups(workgroupCountX uint32, workgroupCountY uint32, workgroupCountZ uint32) {
	c_v := uintptr(c.inner)
	workgroupCountX_v := uintptr(workgroupCountX)
	workgroupCountY_v := uintptr(workgroupCountY)
	workgroupCountZ_v := uintptr(workgroupCountZ)
	procComputePassEncoderDispatchWorkgroups.Call(c_v, workgroupCountX_v, workgroupCountY_v, workgroupCountZ_v)
}

// DispatchWorkgroupsIndirect calls wgpuComputePassEncoderDispatchWorkgroupsIndirect via syscall.
func (c *ComputePassEncoder) DispatchWorkgroupsIndirect(indirectBuffer *Buffer, indirectOffset uint64) {
	c_v := uintptr(c.inner)
	indirectBuffer_v := uintptr(indirectBuffer.inner)
	indirectOffset_v := uintptr(indirectOffset)
	procComputePassEncoderDispatchWorkgroupsIndirect.Call(c_v, indirectBuffer_v, indirectOffset_v)
}

// End calls wgpuComputePassEncoderEnd via syscall.
func (c *ComputePassEncoder) End() {
	c_v := uintptr(c.inner)
	procComputePassEncoderEnd.Call(c_v)
}

// SetLabel calls wgpuComputePassEncoderSetLabel via syscall.
func (c *ComputePassEncoder) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_v := uintptr(c.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procComputePassEncoderSetLabel.Call(c_v, label_v)
}

// GetBindGroupLayout calls wgpuComputePipelineGetBindGroupLayout via syscall.
func (c *ComputePipeline) GetBindGroupLayout(groupIndex uint32) *BindGroupLayout {
	c_v := uintptr(c.inner)
	groupIndex_v := uintptr(groupIndex)
	r1, _, _ := procComputePipelineGetBindGroupLayout.Call(c_v, groupIndex_v)
	return &BindGroupLayout{inner: r1}
}

// SetLabel calls wgpuComputePipelineSetLabel via syscall.
func (c *ComputePipeline) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_v := uintptr(c.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procComputePipelineSetLabel.Call(c_v, label_v)
}

// CreateBindGroup calls wgpuDeviceCreateBindGroup via syscall.
func (d *Device) CreateBindGroup(descriptor BindGroupDescriptor) *BindGroup {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.Entries != nil {
		pinner.Pin(descriptor.Entries)
	}
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateBindGroup.Call(d_v, descriptor_v)
	return &BindGroup{inner: r1}
}

// CreateBindGroupLayout calls wgpuDeviceCreateBindGroupLayout via syscall.
func (d *Device) CreateBindGroupLayout(descriptor BindGroupLayoutDescriptor) *BindGroupLayout {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.Entries != nil {
		pinner.Pin(descriptor.Entries)
	}
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateBindGroupLayout.Call(d_v, descriptor_v)
	return &BindGroupLayout{inner: r1}
}

// CreateBuffer calls wgpuDeviceCreateBuffer via syscall.
func (d *Device) CreateBuffer(descriptor BufferDescriptor) *Buffer {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateBuffer.Call(d_v, descriptor_v)
	return &Buffer{inner: r1}
}

// CreateCommandEncoder calls wgpuDeviceCreateCommandEncoder via syscall.
func (d *Device) CreateCommandEncoder(descriptor CommandEncoderDescriptor) *CommandEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateCommandEncoder.Call(d_v, descriptor_v)
	return &CommandEncoder{inner: r1}
}

// CreateComputePipeline calls wgpuDeviceCreateComputePipeline via syscall.
func (d *Device) CreateComputePipeline(descriptor ComputePipelineDescriptor) *ComputePipeline {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateComputePipeline.Call(d_v, descriptor_v)
	return &ComputePipeline{inner: r1}
}

// CreateComputePipelineAsync calls wgpuDeviceCreateComputePipelineAsync via syscall.
func (d *Device) CreateComputePipelineAsync(descriptor ComputePipelineDescriptor, callback CreateComputePipelineAsyncFn) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	_cbInfo := struct {
		next     uintptr
		mode     uint32
		callback uintptr
		ud1      uintptr
		ud2      uintptr
	}{}
	_cbInfo.mode = uint32(CallbackModeAllowProcessEvents)
	_cbInfo_v := uintptr(unsafe.Pointer(&_cbInfo))
	r1, _, _ := procDeviceCreateComputePipelineAsync.Call(d_v, descriptor_v, _cbInfo_v)
	return Future{Id: uint64(r1)}
}

// CreatePipelineLayout calls wgpuDeviceCreatePipelineLayout via syscall.
func (d *Device) CreatePipelineLayout(descriptor PipelineLayoutDescriptor) *PipelineLayout {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.BindGroupLayouts != nil {
		pinner.Pin(descriptor.BindGroupLayouts)
	}
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreatePipelineLayout.Call(d_v, descriptor_v)
	return &PipelineLayout{inner: r1}
}

// CreateQuerySet calls wgpuDeviceCreateQuerySet via syscall.
func (d *Device) CreateQuerySet(descriptor QuerySetDescriptor) *QuerySet {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateQuerySet.Call(d_v, descriptor_v)
	return &QuerySet{inner: r1}
}

// CreateRenderPipelineAsync calls wgpuDeviceCreateRenderPipelineAsync via syscall.
func (d *Device) CreateRenderPipelineAsync(descriptor RenderPipelineDescriptor, callback CreateRenderPipelineAsyncFn) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	_cbInfo := struct {
		next     uintptr
		mode     uint32
		callback uintptr
		ud1      uintptr
		ud2      uintptr
	}{}
	_cbInfo.mode = uint32(CallbackModeAllowProcessEvents)
	_cbInfo_v := uintptr(unsafe.Pointer(&_cbInfo))
	r1, _, _ := procDeviceCreateRenderPipelineAsync.Call(d_v, descriptor_v, _cbInfo_v)
	return Future{Id: uint64(r1)}
}

// CreateRenderBundleEncoder calls wgpuDeviceCreateRenderBundleEncoder via syscall.
func (d *Device) CreateRenderBundleEncoder(descriptor RenderBundleEncoderDescriptor) *RenderBundleEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.ColorFormats != nil {
		pinner.Pin(descriptor.ColorFormats)
	}
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateRenderBundleEncoder.Call(d_v, descriptor_v)
	return &RenderBundleEncoder{inner: r1}
}

// CreateRenderPipeline calls wgpuDeviceCreateRenderPipeline via syscall.
func (d *Device) CreateRenderPipeline(descriptor RenderPipelineDescriptor) *RenderPipeline {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateRenderPipeline.Call(d_v, descriptor_v)
	return &RenderPipeline{inner: r1}
}

// CreateSampler calls wgpuDeviceCreateSampler via syscall.
func (d *Device) CreateSampler(descriptor SamplerDescriptor) *Sampler {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateSampler.Call(d_v, descriptor_v)
	return &Sampler{inner: r1}
}

// CreateShaderModule calls wgpuDeviceCreateShaderModule via syscall.
func (d *Device) CreateShaderModule(descriptor ShaderModuleDescriptor) *ShaderModule {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateShaderModule.Call(d_v, descriptor_v)
	return &ShaderModule{inner: r1}
}

// CreateTexture calls wgpuDeviceCreateTexture via syscall.
func (d *Device) CreateTexture(descriptor TextureDescriptor) *Texture {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.ViewFormats != nil {
		pinner.Pin(descriptor.ViewFormats)
	}
	d_v := uintptr(d.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procDeviceCreateTexture.Call(d_v, descriptor_v)
	return &Texture{inner: r1}
}

// Destroy calls wgpuDeviceDestroy via syscall.
func (d *Device) Destroy() {
	d_v := uintptr(d.inner)
	procDeviceDestroy.Call(d_v)
}

// GetLostFuture calls wgpuDeviceGetLostFuture via syscall.
func (d *Device) GetLostFuture() Future {
	d_v := uintptr(d.inner)
	r1, _, _ := procDeviceGetLostFuture.Call(d_v)
	return Future{Id: uint64(r1)}
}

// GetLimits calls wgpuDeviceGetLimits via syscall.
func (d *Device) GetLimits(limits Limits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&limits)
	d_v := uintptr(d.inner)
	limits_v := uintptr(unsafe.Pointer(&limits))
	r1, _, _ := procDeviceGetLimits.Call(d_v, limits_v)
	return (Status)(r1)
}

// HasFeature calls wgpuDeviceHasFeature via syscall.
func (d *Device) HasFeature(feature FeatureName) bool {
	d_v := uintptr(d.inner)
	feature_v := uintptr(feature)
	r1, _, _ := procDeviceHasFeature.Call(d_v, feature_v)
	return r1 != 0
}

// GetFeatures calls wgpuDeviceGetFeatures via syscall.
func (d *Device) GetFeatures(features SupportedFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&features)
	if features.Features != nil {
		pinner.Pin(features.Features)
	}
	d_v := uintptr(d.inner)
	features_v := uintptr(unsafe.Pointer(&features))
	procDeviceGetFeatures.Call(d_v, features_v)
}

// GetAdapterInfo calls wgpuDeviceGetAdapterInfo via syscall.
func (d *Device) GetAdapterInfo(adapterInfo AdapterInfo) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&adapterInfo)
	d_v := uintptr(d.inner)
	adapterInfo_v := uintptr(unsafe.Pointer(&adapterInfo))
	r1, _, _ := procDeviceGetAdapterInfo.Call(d_v, adapterInfo_v)
	return (Status)(r1)
}

// GetQueue calls wgpuDeviceGetQueue via syscall.
func (d *Device) GetQueue() *Queue {
	d_v := uintptr(d.inner)
	r1, _, _ := procDeviceGetQueue.Call(d_v)
	return &Queue{inner: r1}
}

// PushErrorScope calls wgpuDevicePushErrorScope via syscall.
func (d *Device) PushErrorScope(filter ErrorFilter) {
	d_v := uintptr(d.inner)
	filter_v := uintptr(filter)
	procDevicePushErrorScope.Call(d_v, filter_v)
}

// PopErrorScope calls wgpuDevicePopErrorScope via syscall.
func (d *Device) PopErrorScope(callback PopErrorScopeFn) Future {
	d_v := uintptr(d.inner)
	_cbInfo := struct {
		next     uintptr
		mode     uint32
		callback uintptr
		ud1      uintptr
		ud2      uintptr
	}{}
	_cbInfo.mode = uint32(CallbackModeAllowProcessEvents)
	_cbInfo_v := uintptr(unsafe.Pointer(&_cbInfo))
	r1, _, _ := procDevicePopErrorScope.Call(d_v, _cbInfo_v)
	return Future{Id: uint64(r1)}
}

// SetLabel calls wgpuDeviceSetLabel via syscall.
func (d *Device) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	d_v := uintptr(d.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procDeviceSetLabel.Call(d_v, label_v)
}

// SetLabel calls wgpuExternalTextureSetLabel via syscall.
func (e *ExternalTexture) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	e_v := uintptr(e.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procExternalTextureSetLabel.Call(e_v, label_v)
}

// CreateSurface calls wgpuInstanceCreateSurface via syscall.
func (i *Instance) CreateSurface(descriptor SurfaceDescriptor) *Surface {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	i_v := uintptr(i.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procInstanceCreateSurface.Call(i_v, descriptor_v)
	return &Surface{inner: r1}
}

// GetWGSLLanguageFeatures calls wgpuInstanceGetWGSLLanguageFeatures via syscall.
func (i *Instance) GetWGSLLanguageFeatures(features SupportedWGSLLanguageFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&features)
	if features.Features != nil {
		pinner.Pin(features.Features)
	}
	i_v := uintptr(i.inner)
	features_v := uintptr(unsafe.Pointer(&features))
	procInstanceGetWGSLLanguageFeatures.Call(i_v, features_v)
}

// HasWGSLLanguageFeature calls wgpuInstanceHasWGSLLanguageFeature via syscall.
func (i *Instance) HasWGSLLanguageFeature(feature WGSLLanguageFeatureName) bool {
	i_v := uintptr(i.inner)
	feature_v := uintptr(feature)
	r1, _, _ := procInstanceHasWGSLLanguageFeature.Call(i_v, feature_v)
	return r1 != 0
}

// ProcessEvents calls wgpuInstanceProcessEvents via syscall.
func (i *Instance) ProcessEvents() {
	i_v := uintptr(i.inner)
	procInstanceProcessEvents.Call(i_v)
}

// RequestAdapter calls wgpuInstanceRequestAdapter via syscall.
func (i *Instance) RequestAdapter(options RequestAdapterOptions, callback RequestAdapterFn) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&options)
	i_v := uintptr(i.inner)
	options_v := uintptr(unsafe.Pointer(&options))
	_cbInfo := struct {
		next     uintptr
		mode     uint32
		callback uintptr
		ud1      uintptr
		ud2      uintptr
	}{}
	_cbInfo.mode = uint32(CallbackModeAllowProcessEvents)
	_cbInfo.callback = syscall.NewCallback(func(status, adapter, msg, ud1, ud2 uintptr) {
		var s string
		if msg != 0 {
			sv := (*wgpuStringView)(unsafe.Pointer(msg))
			if sv.data != nil && sv.length > 0 {
				s = unsafe.String(sv.data, int(sv.length))
			}
		}
		var h *Adapter
		if adapter != 0 {
			h = &Adapter{inner: adapter}
		}
		if fn := callback; fn != nil {
			fn(RequestAdapterStatus(status), h, s)
		}
	})
	_cbInfo_v := uintptr(unsafe.Pointer(&_cbInfo))
	r1, _, _ := procInstanceRequestAdapter.Call(i_v, options_v, _cbInfo_v)
	return Future{Id: uint64(r1)}
}

// WaitAny calls wgpuInstanceWaitAny via syscall.
func (i *Instance) WaitAny(futureCount uintptr, futures FutureWaitInfo, timeoutNS uint64) WaitStatus {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&futures)
	i_v := uintptr(i.inner)
	futureCount_v := uintptr(futureCount)
	futures_v := uintptr(unsafe.Pointer(&futures))
	timeoutNS_v := uintptr(timeoutNS)
	r1, _, _ := procInstanceWaitAny.Call(i_v, futureCount_v, futures_v, timeoutNS_v)
	return (WaitStatus)(r1)
}

// SetLabel calls wgpuPipelineLayoutSetLabel via syscall.
func (p *PipelineLayout) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	p_v := uintptr(p.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procPipelineLayoutSetLabel.Call(p_v, label_v)
}

// SetLabel calls wgpuQuerySetSetLabel via syscall.
func (q *QuerySet) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	q_v := uintptr(q.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procQuerySetSetLabel.Call(q_v, label_v)
}

// GetType calls wgpuQuerySetGetType via syscall.
func (q *QuerySet) GetType() QueryType {
	q_v := uintptr(q.inner)
	r1, _, _ := procQuerySetGetType.Call(q_v)
	return (QueryType)(r1)
}

// GetCount calls wgpuQuerySetGetCount via syscall.
func (q *QuerySet) GetCount() uint32 {
	q_v := uintptr(q.inner)
	r1, _, _ := procQuerySetGetCount.Call(q_v)
	return (uint32)(r1)
}

// Destroy calls wgpuQuerySetDestroy via syscall.
func (q *QuerySet) Destroy() {
	q_v := uintptr(q.inner)
	procQuerySetDestroy.Call(q_v)
}

// Submit calls wgpuQueueSubmit via syscall.
func (q *Queue) Submit(commands []*CommandBuffer) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(commands) > 0 {
		pinner.Pin(&commands[0])
	}
	q_v := uintptr(q.inner)
	commands_handles := make([]uintptr, len(commands))
	for i, v := range commands {
		commands_handles[i] = v.inner
	}
	var commands_ptr uintptr
	if len(commands) > 0 {
		commands_ptr = uintptr(unsafe.Pointer(&commands_handles[0]))
	}
	commands_count := uintptr(len(commands))
	procQueueSubmit.Call(q_v, commands_count, commands_ptr)
}

// OnSubmittedWorkDone calls wgpuQueueOnSubmittedWorkDone via syscall.
func (q *Queue) OnSubmittedWorkDone(callback QueueWorkDoneFn) Future {
	q_v := uintptr(q.inner)
	_cbInfo := struct {
		next     uintptr
		mode     uint32
		callback uintptr
		ud1      uintptr
		ud2      uintptr
	}{}
	_cbInfo.mode = uint32(CallbackModeAllowProcessEvents)
	_cbInfo.callback = syscall.NewCallback(func(status, msg, ud1, ud2, ud3 uintptr) {
		var s string
		if msg != 0 {
			sv := (*wgpuStringView)(unsafe.Pointer(msg))
			if sv.data != nil && sv.length > 0 {
				s = unsafe.String(sv.data, int(sv.length))
			}
		}
		if fn := callback; fn != nil {
			fn(QueueWorkDoneStatus(status), s)
		}
	})
	_cbInfo_v := uintptr(unsafe.Pointer(&_cbInfo))
	r1, _, _ := procQueueOnSubmittedWorkDone.Call(q_v, _cbInfo_v)
	return Future{Id: uint64(r1)}
}

// WriteBuffer calls wgpuQueueWriteBuffer via syscall.
func (q *Queue) WriteBuffer(buffer *Buffer, bufferOffset uint64, data unsafe.Pointer, size uintptr) {
	q_v := uintptr(q.inner)
	buffer_v := uintptr(buffer.inner)
	bufferOffset_v := uintptr(bufferOffset)
	data_v := uintptr(data)
	size_v := uintptr(size)
	procQueueWriteBuffer.Call(q_v, buffer_v, bufferOffset_v, data_v, size_v)
}

// WriteTexture calls wgpuQueueWriteTexture via syscall.
func (q *Queue) WriteTexture(destination TexelCopyTextureInfo, data unsafe.Pointer, dataSize uintptr, dataLayout TexelCopyBufferLayout, writeSize Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&destination)
	pinner.Pin(&dataLayout)
	pinner.Pin(&writeSize)
	q_v := uintptr(q.inner)
	destination_v := uintptr(unsafe.Pointer(&destination))
	data_v := uintptr(data)
	dataSize_v := uintptr(dataSize)
	dataLayout_v := uintptr(unsafe.Pointer(&dataLayout))
	writeSize_v := uintptr(unsafe.Pointer(&writeSize))
	procQueueWriteTexture.Call(q_v, destination_v, data_v, dataSize_v, dataLayout_v, writeSize_v)
}

// SetLabel calls wgpuQueueSetLabel via syscall.
func (q *Queue) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	q_v := uintptr(q.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procQueueSetLabel.Call(q_v, label_v)
}

// SetLabel calls wgpuRenderBundleSetLabel via syscall.
func (r *RenderBundle) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	r_v := uintptr(r.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procRenderBundleSetLabel.Call(r_v, label_v)
}

// SetPipeline calls wgpuRenderBundleEncoderSetPipeline via syscall.
func (r *RenderBundleEncoder) SetPipeline(pipeline *RenderPipeline) {
	r_v := uintptr(r.inner)
	pipeline_v := uintptr(pipeline.inner)
	procRenderBundleEncoderSetPipeline.Call(r_v, pipeline_v)
}

// SetBindGroup calls wgpuRenderBundleEncoderSetBindGroup via syscall.
func (r *RenderBundleEncoder) SetBindGroup(groupIndex uint32, group *BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	r_v := uintptr(r.inner)
	groupIndex_v := uintptr(groupIndex)
	group_v := uintptr(group.inner)
	var dynamicOffsets_ptr uintptr
	if len(dynamicOffsets) > 0 {
		dynamicOffsets_ptr = uintptr(unsafe.Pointer(&dynamicOffsets[0]))
	}
	dynamicOffsets_count := uintptr(len(dynamicOffsets))
	procRenderBundleEncoderSetBindGroup.Call(r_v, groupIndex_v, group_v, dynamicOffsets_count, dynamicOffsets_ptr)
}

// SetImmediates calls wgpuRenderBundleEncoderSetImmediates via syscall.
func (r *RenderBundleEncoder) SetImmediates(offset uint32, data unsafe.Pointer, size uintptr) {
	r_v := uintptr(r.inner)
	offset_v := uintptr(offset)
	data_v := uintptr(data)
	size_v := uintptr(size)
	procRenderBundleEncoderSetImmediates.Call(r_v, offset_v, data_v, size_v)
}

// Draw calls wgpuRenderBundleEncoderDraw via syscall.
func (r *RenderBundleEncoder) Draw(vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) {
	r_v := uintptr(r.inner)
	vertexCount_v := uintptr(vertexCount)
	instanceCount_v := uintptr(instanceCount)
	firstVertex_v := uintptr(firstVertex)
	firstInstance_v := uintptr(firstInstance)
	procRenderBundleEncoderDraw.Call(r_v, vertexCount_v, instanceCount_v, firstVertex_v, firstInstance_v)
}

// DrawIndexed calls wgpuRenderBundleEncoderDrawIndexed via syscall.
func (r *RenderBundleEncoder) DrawIndexed(indexCount uint32, instanceCount uint32, firstIndex uint32, baseVertex int32, firstInstance uint32) {
	r_v := uintptr(r.inner)
	indexCount_v := uintptr(indexCount)
	instanceCount_v := uintptr(instanceCount)
	firstIndex_v := uintptr(firstIndex)
	baseVertex_v := uintptr(baseVertex)
	firstInstance_v := uintptr(firstInstance)
	procRenderBundleEncoderDrawIndexed.Call(r_v, indexCount_v, instanceCount_v, firstIndex_v, baseVertex_v, firstInstance_v)
}

// DrawIndirect calls wgpuRenderBundleEncoderDrawIndirect via syscall.
func (r *RenderBundleEncoder) DrawIndirect(indirectBuffer *Buffer, indirectOffset uint64) {
	r_v := uintptr(r.inner)
	indirectBuffer_v := uintptr(indirectBuffer.inner)
	indirectOffset_v := uintptr(indirectOffset)
	procRenderBundleEncoderDrawIndirect.Call(r_v, indirectBuffer_v, indirectOffset_v)
}

// DrawIndexedIndirect calls wgpuRenderBundleEncoderDrawIndexedIndirect via syscall.
func (r *RenderBundleEncoder) DrawIndexedIndirect(indirectBuffer *Buffer, indirectOffset uint64) {
	r_v := uintptr(r.inner)
	indirectBuffer_v := uintptr(indirectBuffer.inner)
	indirectOffset_v := uintptr(indirectOffset)
	procRenderBundleEncoderDrawIndexedIndirect.Call(r_v, indirectBuffer_v, indirectOffset_v)
}

// InsertDebugMarker calls wgpuRenderBundleEncoderInsertDebugMarker via syscall.
func (r *RenderBundleEncoder) InsertDebugMarker(markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	r_v := uintptr(r.inner)
	markerLabel_sv := syscallStringView(markerLabel, &pinner)
	markerLabel_v := uintptr(unsafe.Pointer(&markerLabel_sv))
	procRenderBundleEncoderInsertDebugMarker.Call(r_v, markerLabel_v)
}

// PopDebugGroup calls wgpuRenderBundleEncoderPopDebugGroup via syscall.
func (r *RenderBundleEncoder) PopDebugGroup() {
	r_v := uintptr(r.inner)
	procRenderBundleEncoderPopDebugGroup.Call(r_v)
}

// PushDebugGroup calls wgpuRenderBundleEncoderPushDebugGroup via syscall.
func (r *RenderBundleEncoder) PushDebugGroup(groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	r_v := uintptr(r.inner)
	groupLabel_sv := syscallStringView(groupLabel, &pinner)
	groupLabel_v := uintptr(unsafe.Pointer(&groupLabel_sv))
	procRenderBundleEncoderPushDebugGroup.Call(r_v, groupLabel_v)
}

// SetVertexBuffer calls wgpuRenderBundleEncoderSetVertexBuffer via syscall.
func (r *RenderBundleEncoder) SetVertexBuffer(slot uint32, buffer *Buffer, offset uint64, size uint64) {
	r_v := uintptr(r.inner)
	slot_v := uintptr(slot)
	buffer_v := uintptr(buffer.inner)
	offset_v := uintptr(offset)
	size_v := uintptr(size)
	procRenderBundleEncoderSetVertexBuffer.Call(r_v, slot_v, buffer_v, offset_v, size_v)
}

// SetIndexBuffer calls wgpuRenderBundleEncoderSetIndexBuffer via syscall.
func (r *RenderBundleEncoder) SetIndexBuffer(buffer *Buffer, format IndexFormat, offset uint64, size uint64) {
	r_v := uintptr(r.inner)
	buffer_v := uintptr(buffer.inner)
	format_v := uintptr(format)
	offset_v := uintptr(offset)
	size_v := uintptr(size)
	procRenderBundleEncoderSetIndexBuffer.Call(r_v, buffer_v, format_v, offset_v, size_v)
}

// Finish calls wgpuRenderBundleEncoderFinish via syscall.
func (r *RenderBundleEncoder) Finish(descriptor RenderBundleDescriptor) *RenderBundle {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	r_v := uintptr(r.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procRenderBundleEncoderFinish.Call(r_v, descriptor_v)
	return &RenderBundle{inner: r1}
}

// SetLabel calls wgpuRenderBundleEncoderSetLabel via syscall.
func (r *RenderBundleEncoder) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	r_v := uintptr(r.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procRenderBundleEncoderSetLabel.Call(r_v, label_v)
}

// SetPipeline calls wgpuRenderPassEncoderSetPipeline via syscall.
func (r *RenderPassEncoder) SetPipeline(pipeline *RenderPipeline) {
	r_v := uintptr(r.inner)
	pipeline_v := uintptr(pipeline.inner)
	procRenderPassEncoderSetPipeline.Call(r_v, pipeline_v)
}

// SetBindGroup calls wgpuRenderPassEncoderSetBindGroup via syscall.
func (r *RenderPassEncoder) SetBindGroup(groupIndex uint32, group *BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	r_v := uintptr(r.inner)
	groupIndex_v := uintptr(groupIndex)
	group_v := uintptr(group.inner)
	var dynamicOffsets_ptr uintptr
	if len(dynamicOffsets) > 0 {
		dynamicOffsets_ptr = uintptr(unsafe.Pointer(&dynamicOffsets[0]))
	}
	dynamicOffsets_count := uintptr(len(dynamicOffsets))
	procRenderPassEncoderSetBindGroup.Call(r_v, groupIndex_v, group_v, dynamicOffsets_count, dynamicOffsets_ptr)
}

// SetImmediates calls wgpuRenderPassEncoderSetImmediates via syscall.
func (r *RenderPassEncoder) SetImmediates(offset uint32, data unsafe.Pointer, size uintptr) {
	r_v := uintptr(r.inner)
	offset_v := uintptr(offset)
	data_v := uintptr(data)
	size_v := uintptr(size)
	procRenderPassEncoderSetImmediates.Call(r_v, offset_v, data_v, size_v)
}

// Draw calls wgpuRenderPassEncoderDraw via syscall.
func (r *RenderPassEncoder) Draw(vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) {
	r_v := uintptr(r.inner)
	vertexCount_v := uintptr(vertexCount)
	instanceCount_v := uintptr(instanceCount)
	firstVertex_v := uintptr(firstVertex)
	firstInstance_v := uintptr(firstInstance)
	procRenderPassEncoderDraw.Call(r_v, vertexCount_v, instanceCount_v, firstVertex_v, firstInstance_v)
}

// DrawIndexed calls wgpuRenderPassEncoderDrawIndexed via syscall.
func (r *RenderPassEncoder) DrawIndexed(indexCount uint32, instanceCount uint32, firstIndex uint32, baseVertex int32, firstInstance uint32) {
	r_v := uintptr(r.inner)
	indexCount_v := uintptr(indexCount)
	instanceCount_v := uintptr(instanceCount)
	firstIndex_v := uintptr(firstIndex)
	baseVertex_v := uintptr(baseVertex)
	firstInstance_v := uintptr(firstInstance)
	procRenderPassEncoderDrawIndexed.Call(r_v, indexCount_v, instanceCount_v, firstIndex_v, baseVertex_v, firstInstance_v)
}

// DrawIndirect calls wgpuRenderPassEncoderDrawIndirect via syscall.
func (r *RenderPassEncoder) DrawIndirect(indirectBuffer *Buffer, indirectOffset uint64) {
	r_v := uintptr(r.inner)
	indirectBuffer_v := uintptr(indirectBuffer.inner)
	indirectOffset_v := uintptr(indirectOffset)
	procRenderPassEncoderDrawIndirect.Call(r_v, indirectBuffer_v, indirectOffset_v)
}

// DrawIndexedIndirect calls wgpuRenderPassEncoderDrawIndexedIndirect via syscall.
func (r *RenderPassEncoder) DrawIndexedIndirect(indirectBuffer *Buffer, indirectOffset uint64) {
	r_v := uintptr(r.inner)
	indirectBuffer_v := uintptr(indirectBuffer.inner)
	indirectOffset_v := uintptr(indirectOffset)
	procRenderPassEncoderDrawIndexedIndirect.Call(r_v, indirectBuffer_v, indirectOffset_v)
}

// ExecuteBundles calls wgpuRenderPassEncoderExecuteBundles via syscall.
func (r *RenderPassEncoder) ExecuteBundles(bundles []*RenderBundle) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(bundles) > 0 {
		pinner.Pin(&bundles[0])
	}
	r_v := uintptr(r.inner)
	bundles_handles := make([]uintptr, len(bundles))
	for i, v := range bundles {
		bundles_handles[i] = v.inner
	}
	var bundles_ptr uintptr
	if len(bundles) > 0 {
		bundles_ptr = uintptr(unsafe.Pointer(&bundles_handles[0]))
	}
	bundles_count := uintptr(len(bundles))
	procRenderPassEncoderExecuteBundles.Call(r_v, bundles_count, bundles_ptr)
}

// InsertDebugMarker calls wgpuRenderPassEncoderInsertDebugMarker via syscall.
func (r *RenderPassEncoder) InsertDebugMarker(markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	r_v := uintptr(r.inner)
	markerLabel_sv := syscallStringView(markerLabel, &pinner)
	markerLabel_v := uintptr(unsafe.Pointer(&markerLabel_sv))
	procRenderPassEncoderInsertDebugMarker.Call(r_v, markerLabel_v)
}

// PopDebugGroup calls wgpuRenderPassEncoderPopDebugGroup via syscall.
func (r *RenderPassEncoder) PopDebugGroup() {
	r_v := uintptr(r.inner)
	procRenderPassEncoderPopDebugGroup.Call(r_v)
}

// PushDebugGroup calls wgpuRenderPassEncoderPushDebugGroup via syscall.
func (r *RenderPassEncoder) PushDebugGroup(groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	r_v := uintptr(r.inner)
	groupLabel_sv := syscallStringView(groupLabel, &pinner)
	groupLabel_v := uintptr(unsafe.Pointer(&groupLabel_sv))
	procRenderPassEncoderPushDebugGroup.Call(r_v, groupLabel_v)
}

// SetStencilReference calls wgpuRenderPassEncoderSetStencilReference via syscall.
func (r *RenderPassEncoder) SetStencilReference(reference uint32) {
	r_v := uintptr(r.inner)
	reference_v := uintptr(reference)
	procRenderPassEncoderSetStencilReference.Call(r_v, reference_v)
}

// SetBlendConstant calls wgpuRenderPassEncoderSetBlendConstant via syscall.
func (r *RenderPassEncoder) SetBlendConstant(color Color) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&color)
	r_v := uintptr(r.inner)
	color_v := uintptr(unsafe.Pointer(&color))
	procRenderPassEncoderSetBlendConstant.Call(r_v, color_v)
}

// SetViewport calls wgpuRenderPassEncoderSetViewport via syscall.
func (r *RenderPassEncoder) SetViewport(x float32, y float32, width float32, height float32, minDepth float32, maxDepth float32) {
	r_v := uintptr(r.inner)
	x_v := uintptr(x)
	y_v := uintptr(y)
	width_v := uintptr(width)
	height_v := uintptr(height)
	minDepth_v := uintptr(minDepth)
	maxDepth_v := uintptr(maxDepth)
	procRenderPassEncoderSetViewport.Call(r_v, x_v, y_v, width_v, height_v, minDepth_v, maxDepth_v)
}

// SetScissorRect calls wgpuRenderPassEncoderSetScissorRect via syscall.
func (r *RenderPassEncoder) SetScissorRect(x uint32, y uint32, width uint32, height uint32) {
	r_v := uintptr(r.inner)
	x_v := uintptr(x)
	y_v := uintptr(y)
	width_v := uintptr(width)
	height_v := uintptr(height)
	procRenderPassEncoderSetScissorRect.Call(r_v, x_v, y_v, width_v, height_v)
}

// SetVertexBuffer calls wgpuRenderPassEncoderSetVertexBuffer via syscall.
func (r *RenderPassEncoder) SetVertexBuffer(slot uint32, buffer *Buffer, offset uint64, size uint64) {
	r_v := uintptr(r.inner)
	slot_v := uintptr(slot)
	buffer_v := uintptr(buffer.inner)
	offset_v := uintptr(offset)
	size_v := uintptr(size)
	procRenderPassEncoderSetVertexBuffer.Call(r_v, slot_v, buffer_v, offset_v, size_v)
}

// SetIndexBuffer calls wgpuRenderPassEncoderSetIndexBuffer via syscall.
func (r *RenderPassEncoder) SetIndexBuffer(buffer *Buffer, format IndexFormat, offset uint64, size uint64) {
	r_v := uintptr(r.inner)
	buffer_v := uintptr(buffer.inner)
	format_v := uintptr(format)
	offset_v := uintptr(offset)
	size_v := uintptr(size)
	procRenderPassEncoderSetIndexBuffer.Call(r_v, buffer_v, format_v, offset_v, size_v)
}

// BeginOcclusionQuery calls wgpuRenderPassEncoderBeginOcclusionQuery via syscall.
func (r *RenderPassEncoder) BeginOcclusionQuery(queryIndex uint32) {
	r_v := uintptr(r.inner)
	queryIndex_v := uintptr(queryIndex)
	procRenderPassEncoderBeginOcclusionQuery.Call(r_v, queryIndex_v)
}

// EndOcclusionQuery calls wgpuRenderPassEncoderEndOcclusionQuery via syscall.
func (r *RenderPassEncoder) EndOcclusionQuery() {
	r_v := uintptr(r.inner)
	procRenderPassEncoderEndOcclusionQuery.Call(r_v)
}

// End calls wgpuRenderPassEncoderEnd via syscall.
func (r *RenderPassEncoder) End() {
	r_v := uintptr(r.inner)
	procRenderPassEncoderEnd.Call(r_v)
}

// SetLabel calls wgpuRenderPassEncoderSetLabel via syscall.
func (r *RenderPassEncoder) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	r_v := uintptr(r.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procRenderPassEncoderSetLabel.Call(r_v, label_v)
}

// GetBindGroupLayout calls wgpuRenderPipelineGetBindGroupLayout via syscall.
func (r *RenderPipeline) GetBindGroupLayout(groupIndex uint32) *BindGroupLayout {
	r_v := uintptr(r.inner)
	groupIndex_v := uintptr(groupIndex)
	r1, _, _ := procRenderPipelineGetBindGroupLayout.Call(r_v, groupIndex_v)
	return &BindGroupLayout{inner: r1}
}

// SetLabel calls wgpuRenderPipelineSetLabel via syscall.
func (r *RenderPipeline) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	r_v := uintptr(r.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procRenderPipelineSetLabel.Call(r_v, label_v)
}

// SetLabel calls wgpuSamplerSetLabel via syscall.
func (s *Sampler) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	s_v := uintptr(s.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procSamplerSetLabel.Call(s_v, label_v)
}

// GetCompilationInfo calls wgpuShaderModuleGetCompilationInfo via syscall.
func (s *ShaderModule) GetCompilationInfo(callback CompilationInfoFn) Future {
	s_v := uintptr(s.inner)
	_cbInfo := struct {
		next     uintptr
		mode     uint32
		callback uintptr
		ud1      uintptr
		ud2      uintptr
	}{}
	_cbInfo.mode = uint32(CallbackModeAllowProcessEvents)
	_cbInfo_v := uintptr(unsafe.Pointer(&_cbInfo))
	r1, _, _ := procShaderModuleGetCompilationInfo.Call(s_v, _cbInfo_v)
	return Future{Id: uint64(r1)}
}

// SetLabel calls wgpuShaderModuleSetLabel via syscall.
func (s *ShaderModule) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	s_v := uintptr(s.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procShaderModuleSetLabel.Call(s_v, label_v)
}

// Configure calls wgpuSurfaceConfigure via syscall.
func (s *Surface) Configure(config SurfaceConfiguration) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&config)
	if config.ViewFormats != nil {
		pinner.Pin(config.ViewFormats)
	}
	s_v := uintptr(s.inner)
	config_v := uintptr(unsafe.Pointer(&config))
	procSurfaceConfigure.Call(s_v, config_v)
}

// GetCapabilities calls wgpuSurfaceGetCapabilities via syscall.
func (s *Surface) GetCapabilities(adapter *Adapter, capabilities SurfaceCapabilities) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&capabilities)
	if capabilities.Formats != nil {
		pinner.Pin(capabilities.Formats)
	}
	if capabilities.PresentModes != nil {
		pinner.Pin(capabilities.PresentModes)
	}
	if capabilities.AlphaModes != nil {
		pinner.Pin(capabilities.AlphaModes)
	}
	s_v := uintptr(s.inner)
	adapter_v := uintptr(adapter.inner)
	capabilities_v := uintptr(unsafe.Pointer(&capabilities))
	r1, _, _ := procSurfaceGetCapabilities.Call(s_v, adapter_v, capabilities_v)
	return (Status)(r1)
}

// GetCurrentTexture calls wgpuSurfaceGetCurrentTexture via syscall.
func (s *Surface) GetCurrentTexture(surfaceTexture SurfaceTexture) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&surfaceTexture)
	s_v := uintptr(s.inner)
	surfaceTexture_v := uintptr(unsafe.Pointer(&surfaceTexture))
	procSurfaceGetCurrentTexture.Call(s_v, surfaceTexture_v)
}

// Present calls wgpuSurfacePresent via syscall.
func (s *Surface) Present() Status {
	s_v := uintptr(s.inner)
	r1, _, _ := procSurfacePresent.Call(s_v)
	return (Status)(r1)
}

// Unconfigure calls wgpuSurfaceUnconfigure via syscall.
func (s *Surface) Unconfigure() {
	s_v := uintptr(s.inner)
	procSurfaceUnconfigure.Call(s_v)
}

// SetLabel calls wgpuSurfaceSetLabel via syscall.
func (s *Surface) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	s_v := uintptr(s.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procSurfaceSetLabel.Call(s_v, label_v)
}

// CreateView calls wgpuTextureCreateView via syscall.
func (t *Texture) CreateView(descriptor TextureViewDescriptor) *TextureView {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	t_v := uintptr(t.inner)
	descriptor_v := uintptr(unsafe.Pointer(&descriptor))
	r1, _, _ := procTextureCreateView.Call(t_v, descriptor_v)
	return &TextureView{inner: r1}
}

// SetLabel calls wgpuTextureSetLabel via syscall.
func (t *Texture) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	t_v := uintptr(t.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procTextureSetLabel.Call(t_v, label_v)
}

// GetWidth calls wgpuTextureGetWidth via syscall.
func (t *Texture) GetWidth() uint32 {
	t_v := uintptr(t.inner)
	r1, _, _ := procTextureGetWidth.Call(t_v)
	return (uint32)(r1)
}

// GetHeight calls wgpuTextureGetHeight via syscall.
func (t *Texture) GetHeight() uint32 {
	t_v := uintptr(t.inner)
	r1, _, _ := procTextureGetHeight.Call(t_v)
	return (uint32)(r1)
}

// GetDepthOrArrayLayers calls wgpuTextureGetDepthOrArrayLayers via syscall.
func (t *Texture) GetDepthOrArrayLayers() uint32 {
	t_v := uintptr(t.inner)
	r1, _, _ := procTextureGetDepthOrArrayLayers.Call(t_v)
	return (uint32)(r1)
}

// GetMipLevelCount calls wgpuTextureGetMipLevelCount via syscall.
func (t *Texture) GetMipLevelCount() uint32 {
	t_v := uintptr(t.inner)
	r1, _, _ := procTextureGetMipLevelCount.Call(t_v)
	return (uint32)(r1)
}

// GetSampleCount calls wgpuTextureGetSampleCount via syscall.
func (t *Texture) GetSampleCount() uint32 {
	t_v := uintptr(t.inner)
	r1, _, _ := procTextureGetSampleCount.Call(t_v)
	return (uint32)(r1)
}

// GetDimension calls wgpuTextureGetDimension via syscall.
func (t *Texture) GetDimension() TextureDimension {
	t_v := uintptr(t.inner)
	r1, _, _ := procTextureGetDimension.Call(t_v)
	return (TextureDimension)(r1)
}

// GetTextureBindingViewDimension calls wgpuTextureGetTextureBindingViewDimension via syscall.
func (t *Texture) GetTextureBindingViewDimension() TextureViewDimension {
	t_v := uintptr(t.inner)
	r1, _, _ := procTextureGetTextureBindingViewDimension.Call(t_v)
	return (TextureViewDimension)(r1)
}

// GetFormat calls wgpuTextureGetFormat via syscall.
func (t *Texture) GetFormat() TextureFormat {
	t_v := uintptr(t.inner)
	r1, _, _ := procTextureGetFormat.Call(t_v)
	return (TextureFormat)(r1)
}

// GetUsage calls wgpuTextureGetUsage via syscall.
func (t *Texture) GetUsage() TextureUsage {
	t_v := uintptr(t.inner)
	r1, _, _ := procTextureGetUsage.Call(t_v)
	return (TextureUsage)(r1)
}

// Destroy calls wgpuTextureDestroy via syscall.
func (t *Texture) Destroy() {
	t_v := uintptr(t.inner)
	procTextureDestroy.Call(t_v)
}

// SetLabel calls wgpuTextureViewSetLabel via syscall.
func (t *TextureView) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	t_v := uintptr(t.inner)
	label_sv := syscallStringView(label, &pinner)
	label_v := uintptr(unsafe.Pointer(&label_sv))
	procTextureViewSetLabel.Call(t_v, label_v)
}
