// Code generated by gen; DO NOT EDIT.
//go:build windows && !cgo

package webgpu

import (
	"os"
	"path/filepath"
	"runtime"
	"syscall"
	"unsafe"
)

func loadWebGPUDLL() *syscall.LazyDLL {
	const name = "wgpu_native.dll"
	if p := os.Getenv("WGPU_NATIVE_DLL"); p != "" {
		return syscall.NewLazyDLL(p)
	}
	if exe, err := os.Executable(); err == nil {
		if p := filepath.Join(filepath.Dir(exe), name); fileExists(p) {
			return syscall.NewLazyDLL(p)
		}
	}
	if _, file, _, ok := runtime.Caller(0); ok {
		pattern := filepath.Join(filepath.Dir(file), "..", "third_party", "wgpu-native", "windows-*", "lib", name)
		if matches, err := filepath.Glob(pattern); err == nil && len(matches) > 0 {
			return syscall.NewLazyDLL(matches[0])
		}
	}
	return syscall.NewLazyDLL(name)
}

func fileExists(p string) bool {
	st, err := os.Stat(p)
	return err == nil && !st.IsDir()
}

var (
	webgpuDLL                                        = loadWebGPUDLL()
	procCreateInstance                               = webgpuDLL.NewProc("wgpuCreateInstance")
	procGetInstanceFeatures                          = webgpuDLL.NewProc("wgpuGetInstanceFeatures")
	procGetInstanceLimits                            = webgpuDLL.NewProc("wgpuGetInstanceLimits")
	procHasInstanceFeature                           = webgpuDLL.NewProc("wgpuHasInstanceFeature")
	procAdapterGetLimits                             = webgpuDLL.NewProc("wgpuAdapterGetLimits")
	procAdapterHasFeature                            = webgpuDLL.NewProc("wgpuAdapterHasFeature")
	procAdapterGetFeatures                           = webgpuDLL.NewProc("wgpuAdapterGetFeatures")
	procAdapterGetInfo                               = webgpuDLL.NewProc("wgpuAdapterGetInfo")
	procAdapterRequestDevice                         = webgpuDLL.NewProc("wgpuAdapterRequestDevice")
	procAdapterRelease                               = webgpuDLL.NewProc("wgpuAdapterRelease")
	procBindGroupSetLabel                            = webgpuDLL.NewProc("wgpuBindGroupSetLabel")
	procBindGroupRelease                             = webgpuDLL.NewProc("wgpuBindGroupRelease")
	procBindGroupLayoutSetLabel                      = webgpuDLL.NewProc("wgpuBindGroupLayoutSetLabel")
	procBindGroupLayoutRelease                       = webgpuDLL.NewProc("wgpuBindGroupLayoutRelease")
	procBufferMap                                    = webgpuDLL.NewProc("wgpuBufferMapAsync")
	procBufferGetMappedRange                         = webgpuDLL.NewProc("wgpuBufferGetMappedRange")
	procBufferGetConstMappedRange                    = webgpuDLL.NewProc("wgpuBufferGetConstMappedRange")
	procBufferReadMappedRange                        = webgpuDLL.NewProc("wgpuBufferReadMappedRange")
	procBufferWriteMappedRange                       = webgpuDLL.NewProc("wgpuBufferWriteMappedRange")
	procBufferSetLabel                               = webgpuDLL.NewProc("wgpuBufferSetLabel")
	procBufferGetUsage                               = webgpuDLL.NewProc("wgpuBufferGetUsage")
	procBufferGetSize                                = webgpuDLL.NewProc("wgpuBufferGetSize")
	procBufferGetMapState                            = webgpuDLL.NewProc("wgpuBufferGetMapState")
	procBufferUnmap                                  = webgpuDLL.NewProc("wgpuBufferUnmap")
	procBufferDestroy                                = webgpuDLL.NewProc("wgpuBufferDestroy")
	procBufferRelease                                = webgpuDLL.NewProc("wgpuBufferRelease")
	procCommandBufferSetLabel                        = webgpuDLL.NewProc("wgpuCommandBufferSetLabel")
	procCommandBufferRelease                         = webgpuDLL.NewProc("wgpuCommandBufferRelease")
	procCommandEncoderFinish                         = webgpuDLL.NewProc("wgpuCommandEncoderFinish")
	procCommandEncoderBeginComputePass               = webgpuDLL.NewProc("wgpuCommandEncoderBeginComputePass")
	procCommandEncoderBeginRenderPass                = webgpuDLL.NewProc("wgpuCommandEncoderBeginRenderPass")
	procCommandEncoderCopyBufferToBuffer             = webgpuDLL.NewProc("wgpuCommandEncoderCopyBufferToBuffer")
	procCommandEncoderCopyBufferToTexture            = webgpuDLL.NewProc("wgpuCommandEncoderCopyBufferToTexture")
	procCommandEncoderCopyTextureToBuffer            = webgpuDLL.NewProc("wgpuCommandEncoderCopyTextureToBuffer")
	procCommandEncoderCopyTextureToTexture           = webgpuDLL.NewProc("wgpuCommandEncoderCopyTextureToTexture")
	procCommandEncoderClearBuffer                    = webgpuDLL.NewProc("wgpuCommandEncoderClearBuffer")
	procCommandEncoderInsertDebugMarker              = webgpuDLL.NewProc("wgpuCommandEncoderInsertDebugMarker")
	procCommandEncoderPopDebugGroup                  = webgpuDLL.NewProc("wgpuCommandEncoderPopDebugGroup")
	procCommandEncoderPushDebugGroup                 = webgpuDLL.NewProc("wgpuCommandEncoderPushDebugGroup")
	procCommandEncoderResolveQuerySet                = webgpuDLL.NewProc("wgpuCommandEncoderResolveQuerySet")
	procCommandEncoderWriteTimestamp                 = webgpuDLL.NewProc("wgpuCommandEncoderWriteTimestamp")
	procCommandEncoderSetLabel                       = webgpuDLL.NewProc("wgpuCommandEncoderSetLabel")
	procCommandEncoderRelease                        = webgpuDLL.NewProc("wgpuCommandEncoderRelease")
	procComputePassEncoderInsertDebugMarker          = webgpuDLL.NewProc("wgpuComputePassEncoderInsertDebugMarker")
	procComputePassEncoderPopDebugGroup              = webgpuDLL.NewProc("wgpuComputePassEncoderPopDebugGroup")
	procComputePassEncoderPushDebugGroup             = webgpuDLL.NewProc("wgpuComputePassEncoderPushDebugGroup")
	procComputePassEncoderSetPipeline                = webgpuDLL.NewProc("wgpuComputePassEncoderSetPipeline")
	procComputePassEncoderSetBindGroup               = webgpuDLL.NewProc("wgpuComputePassEncoderSetBindGroup")
	procComputePassEncoderSetImmediates              = webgpuDLL.NewProc("wgpuComputePassEncoderSetImmediates")
	procComputePassEncoderDispatchWorkgroups         = webgpuDLL.NewProc("wgpuComputePassEncoderDispatchWorkgroups")
	procComputePassEncoderDispatchWorkgroupsIndirect = webgpuDLL.NewProc("wgpuComputePassEncoderDispatchWorkgroupsIndirect")
	procComputePassEncoderEnd                        = webgpuDLL.NewProc("wgpuComputePassEncoderEnd")
	procComputePassEncoderSetLabel                   = webgpuDLL.NewProc("wgpuComputePassEncoderSetLabel")
	procComputePassEncoderRelease                    = webgpuDLL.NewProc("wgpuComputePassEncoderRelease")
	procComputePipelineGetBindGroupLayout            = webgpuDLL.NewProc("wgpuComputePipelineGetBindGroupLayout")
	procComputePipelineSetLabel                      = webgpuDLL.NewProc("wgpuComputePipelineSetLabel")
	procComputePipelineRelease                       = webgpuDLL.NewProc("wgpuComputePipelineRelease")
	procDeviceCreateBindGroup                        = webgpuDLL.NewProc("wgpuDeviceCreateBindGroup")
	procDeviceCreateBindGroupLayout                  = webgpuDLL.NewProc("wgpuDeviceCreateBindGroupLayout")
	procDeviceCreateBuffer                           = webgpuDLL.NewProc("wgpuDeviceCreateBuffer")
	procDeviceCreateCommandEncoder                   = webgpuDLL.NewProc("wgpuDeviceCreateCommandEncoder")
	procDeviceCreateComputePipeline                  = webgpuDLL.NewProc("wgpuDeviceCreateComputePipeline")
	procDeviceCreateComputePipelineAsync             = webgpuDLL.NewProc("wgpuDeviceCreateComputePipelineAsync")
	procDeviceCreatePipelineLayout                   = webgpuDLL.NewProc("wgpuDeviceCreatePipelineLayout")
	procDeviceCreateQuerySet                         = webgpuDLL.NewProc("wgpuDeviceCreateQuerySet")
	procDeviceCreateRenderPipelineAsync              = webgpuDLL.NewProc("wgpuDeviceCreateRenderPipelineAsync")
	procDeviceCreateRenderBundleEncoder              = webgpuDLL.NewProc("wgpuDeviceCreateRenderBundleEncoder")
	procDeviceCreateRenderPipeline                   = webgpuDLL.NewProc("wgpuDeviceCreateRenderPipeline")
	procDeviceCreateSampler                          = webgpuDLL.NewProc("wgpuDeviceCreateSampler")
	procDeviceCreateShaderModule                     = webgpuDLL.NewProc("wgpuDeviceCreateShaderModule")
	procDeviceCreateTexture                          = webgpuDLL.NewProc("wgpuDeviceCreateTexture")
	procDeviceDestroy                                = webgpuDLL.NewProc("wgpuDeviceDestroy")
	procDeviceGetLostFuture                          = webgpuDLL.NewProc("wgpuDeviceGetLostFuture")
	procDeviceGetLimits                              = webgpuDLL.NewProc("wgpuDeviceGetLimits")
	procDeviceHasFeature                             = webgpuDLL.NewProc("wgpuDeviceHasFeature")
	procDeviceGetFeatures                            = webgpuDLL.NewProc("wgpuDeviceGetFeatures")
	procDeviceGetAdapterInfo                         = webgpuDLL.NewProc("wgpuDeviceGetAdapterInfo")
	procDeviceGetQueue                               = webgpuDLL.NewProc("wgpuDeviceGetQueue")
	procDevicePushErrorScope                         = webgpuDLL.NewProc("wgpuDevicePushErrorScope")
	procDevicePopErrorScope                          = webgpuDLL.NewProc("wgpuDevicePopErrorScope")
	procDeviceSetLabel                               = webgpuDLL.NewProc("wgpuDeviceSetLabel")
	procDeviceRelease                                = webgpuDLL.NewProc("wgpuDeviceRelease")
	procExternalTextureSetLabel                      = webgpuDLL.NewProc("wgpuExternalTextureSetLabel")
	procExternalTextureRelease                       = webgpuDLL.NewProc("wgpuExternalTextureRelease")
	procInstanceCreateSurface                        = webgpuDLL.NewProc("wgpuInstanceCreateSurface")
	procInstanceGetWGSLLanguageFeatures              = webgpuDLL.NewProc("wgpuInstanceGetWGSLLanguageFeatures")
	procInstanceHasWGSLLanguageFeature               = webgpuDLL.NewProc("wgpuInstanceHasWGSLLanguageFeature")
	procInstanceProcessEvents                        = webgpuDLL.NewProc("wgpuInstanceProcessEvents")
	procInstanceRequestAdapter                       = webgpuDLL.NewProc("wgpuInstanceRequestAdapter")
	procInstanceWaitAny                              = webgpuDLL.NewProc("wgpuInstanceWaitAny")
	procInstanceRelease                              = webgpuDLL.NewProc("wgpuInstanceRelease")
	procPipelineLayoutSetLabel                       = webgpuDLL.NewProc("wgpuPipelineLayoutSetLabel")
	procPipelineLayoutRelease                        = webgpuDLL.NewProc("wgpuPipelineLayoutRelease")
	procQuerySetSetLabel                             = webgpuDLL.NewProc("wgpuQuerySetSetLabel")
	procQuerySetGetType                              = webgpuDLL.NewProc("wgpuQuerySetGetType")
	procQuerySetGetCount                             = webgpuDLL.NewProc("wgpuQuerySetGetCount")
	procQuerySetDestroy                              = webgpuDLL.NewProc("wgpuQuerySetDestroy")
	procQuerySetRelease                              = webgpuDLL.NewProc("wgpuQuerySetRelease")
	procQueueSubmit                                  = webgpuDLL.NewProc("wgpuQueueSubmit")
	procQueueOnSubmittedWorkDone                     = webgpuDLL.NewProc("wgpuQueueOnSubmittedWorkDone")
	procQueueWriteBuffer                             = webgpuDLL.NewProc("wgpuQueueWriteBuffer")
	procQueueWriteTexture                            = webgpuDLL.NewProc("wgpuQueueWriteTexture")
	procQueueSetLabel                                = webgpuDLL.NewProc("wgpuQueueSetLabel")
	procQueueRelease                                 = webgpuDLL.NewProc("wgpuQueueRelease")
	procRenderBundleSetLabel                         = webgpuDLL.NewProc("wgpuRenderBundleSetLabel")
	procRenderBundleRelease                          = webgpuDLL.NewProc("wgpuRenderBundleRelease")
	procRenderBundleEncoderSetPipeline               = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetPipeline")
	procRenderBundleEncoderSetBindGroup              = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetBindGroup")
	procRenderBundleEncoderSetImmediates             = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetImmediates")
	procRenderBundleEncoderDraw                      = webgpuDLL.NewProc("wgpuRenderBundleEncoderDraw")
	procRenderBundleEncoderDrawIndexed               = webgpuDLL.NewProc("wgpuRenderBundleEncoderDrawIndexed")
	procRenderBundleEncoderDrawIndirect              = webgpuDLL.NewProc("wgpuRenderBundleEncoderDrawIndirect")
	procRenderBundleEncoderDrawIndexedIndirect       = webgpuDLL.NewProc("wgpuRenderBundleEncoderDrawIndexedIndirect")
	procRenderBundleEncoderInsertDebugMarker         = webgpuDLL.NewProc("wgpuRenderBundleEncoderInsertDebugMarker")
	procRenderBundleEncoderPopDebugGroup             = webgpuDLL.NewProc("wgpuRenderBundleEncoderPopDebugGroup")
	procRenderBundleEncoderPushDebugGroup            = webgpuDLL.NewProc("wgpuRenderBundleEncoderPushDebugGroup")
	procRenderBundleEncoderSetVertexBuffer           = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetVertexBuffer")
	procRenderBundleEncoderSetIndexBuffer            = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetIndexBuffer")
	procRenderBundleEncoderFinish                    = webgpuDLL.NewProc("wgpuRenderBundleEncoderFinish")
	procRenderBundleEncoderSetLabel                  = webgpuDLL.NewProc("wgpuRenderBundleEncoderSetLabel")
	procRenderBundleEncoderRelease                   = webgpuDLL.NewProc("wgpuRenderBundleEncoderRelease")
	procRenderPassEncoderSetPipeline                 = webgpuDLL.NewProc("wgpuRenderPassEncoderSetPipeline")
	procRenderPassEncoderSetBindGroup                = webgpuDLL.NewProc("wgpuRenderPassEncoderSetBindGroup")
	procRenderPassEncoderSetImmediates               = webgpuDLL.NewProc("wgpuRenderPassEncoderSetImmediates")
	procRenderPassEncoderDraw                        = webgpuDLL.NewProc("wgpuRenderPassEncoderDraw")
	procRenderPassEncoderDrawIndexed                 = webgpuDLL.NewProc("wgpuRenderPassEncoderDrawIndexed")
	procRenderPassEncoderDrawIndirect                = webgpuDLL.NewProc("wgpuRenderPassEncoderDrawIndirect")
	procRenderPassEncoderDrawIndexedIndirect         = webgpuDLL.NewProc("wgpuRenderPassEncoderDrawIndexedIndirect")
	procRenderPassEncoderExecuteBundles              = webgpuDLL.NewProc("wgpuRenderPassEncoderExecuteBundles")
	procRenderPassEncoderInsertDebugMarker           = webgpuDLL.NewProc("wgpuRenderPassEncoderInsertDebugMarker")
	procRenderPassEncoderPopDebugGroup               = webgpuDLL.NewProc("wgpuRenderPassEncoderPopDebugGroup")
	procRenderPassEncoderPushDebugGroup              = webgpuDLL.NewProc("wgpuRenderPassEncoderPushDebugGroup")
	procRenderPassEncoderSetStencilReference         = webgpuDLL.NewProc("wgpuRenderPassEncoderSetStencilReference")
	procRenderPassEncoderSetBlendConstant            = webgpuDLL.NewProc("wgpuRenderPassEncoderSetBlendConstant")
	procRenderPassEncoderSetViewport                 = webgpuDLL.NewProc("wgpuRenderPassEncoderSetViewport")
	procRenderPassEncoderSetScissorRect              = webgpuDLL.NewProc("wgpuRenderPassEncoderSetScissorRect")
	procRenderPassEncoderSetVertexBuffer             = webgpuDLL.NewProc("wgpuRenderPassEncoderSetVertexBuffer")
	procRenderPassEncoderSetIndexBuffer              = webgpuDLL.NewProc("wgpuRenderPassEncoderSetIndexBuffer")
	procRenderPassEncoderBeginOcclusionQuery         = webgpuDLL.NewProc("wgpuRenderPassEncoderBeginOcclusionQuery")
	procRenderPassEncoderEndOcclusionQuery           = webgpuDLL.NewProc("wgpuRenderPassEncoderEndOcclusionQuery")
	procRenderPassEncoderEnd                         = webgpuDLL.NewProc("wgpuRenderPassEncoderEnd")
	procRenderPassEncoderSetLabel                    = webgpuDLL.NewProc("wgpuRenderPassEncoderSetLabel")
	procRenderPassEncoderRelease                     = webgpuDLL.NewProc("wgpuRenderPassEncoderRelease")
	procRenderPipelineGetBindGroupLayout             = webgpuDLL.NewProc("wgpuRenderPipelineGetBindGroupLayout")
	procRenderPipelineSetLabel                       = webgpuDLL.NewProc("wgpuRenderPipelineSetLabel")
	procRenderPipelineRelease                        = webgpuDLL.NewProc("wgpuRenderPipelineRelease")
	procSamplerSetLabel                              = webgpuDLL.NewProc("wgpuSamplerSetLabel")
	procSamplerRelease                               = webgpuDLL.NewProc("wgpuSamplerRelease")
	procShaderModuleGetCompilationInfo               = webgpuDLL.NewProc("wgpuShaderModuleGetCompilationInfo")
	procShaderModuleSetLabel                         = webgpuDLL.NewProc("wgpuShaderModuleSetLabel")
	procShaderModuleRelease                          = webgpuDLL.NewProc("wgpuShaderModuleRelease")
	procSurfaceConfigure                             = webgpuDLL.NewProc("wgpuSurfaceConfigure")
	procSurfaceGetCapabilities                       = webgpuDLL.NewProc("wgpuSurfaceGetCapabilities")
	procSurfaceGetCurrentTexture                     = webgpuDLL.NewProc("wgpuSurfaceGetCurrentTexture")
	procSurfacePresent                               = webgpuDLL.NewProc("wgpuSurfacePresent")
	procSurfaceUnconfigure                           = webgpuDLL.NewProc("wgpuSurfaceUnconfigure")
	procSurfaceSetLabel                              = webgpuDLL.NewProc("wgpuSurfaceSetLabel")
	procSurfaceRelease                               = webgpuDLL.NewProc("wgpuSurfaceRelease")
	procTextureCreateView                            = webgpuDLL.NewProc("wgpuTextureCreateView")
	procTextureSetLabel                              = webgpuDLL.NewProc("wgpuTextureSetLabel")
	procTextureGetWidth                              = webgpuDLL.NewProc("wgpuTextureGetWidth")
	procTextureGetHeight                             = webgpuDLL.NewProc("wgpuTextureGetHeight")
	procTextureGetDepthOrArrayLayers                 = webgpuDLL.NewProc("wgpuTextureGetDepthOrArrayLayers")
	procTextureGetMipLevelCount                      = webgpuDLL.NewProc("wgpuTextureGetMipLevelCount")
	procTextureGetSampleCount                        = webgpuDLL.NewProc("wgpuTextureGetSampleCount")
	procTextureGetDimension                          = webgpuDLL.NewProc("wgpuTextureGetDimension")
	procTextureGetTextureBindingViewDimension        = webgpuDLL.NewProc("wgpuTextureGetTextureBindingViewDimension")
	procTextureGetFormat                             = webgpuDLL.NewProc("wgpuTextureGetFormat")
	procTextureGetUsage                              = webgpuDLL.NewProc("wgpuTextureGetUsage")
	procTextureDestroy                               = webgpuDLL.NewProc("wgpuTextureDestroy")
	procTextureRelease                               = webgpuDLL.NewProc("wgpuTextureRelease")
	procTextureViewSetLabel                          = webgpuDLL.NewProc("wgpuTextureViewSetLabel")
	procTextureViewRelease                           = webgpuDLL.NewProc("wgpuTextureViewRelease")
)

// wgpuStringView matches C.WGPUStringView (passed by reference on win64).
type wgpuStringView struct {
	data   *byte
	length uintptr
}

func syscallStringView(s string, pinner *runtime.Pinner) wgpuStringView {
	var v wgpuStringView
	if len(s) > 0 {
		p := unsafe.StringData(s)
		pinner.Pin(p)
		v.data = p
		v.length = uintptr(len(s))
	}
	return v
}

func goStringFromView(p uintptr) string {
	if p == 0 {
		return ""
	}
	sv := (*wgpuStringView)(unsafe.Pointer(p))
	if sv.data == nil || sv.length == 0 {
		return ""
	}
	return unsafe.String(sv.data, int(sv.length))
}

// cbThunk carries the Go callback through C userdata1.
// One syscall.NewCallback trampoline is created per C callback type.
type cbThunk struct{ fn any }

var cbBufferMap = syscall.NewCallback(func(c_status, c_message, ud1, ud2 uintptr) uintptr {
	status := MapAsyncStatus(c_status)
	message := goStringFromView(c_message)
	if ud1 != 0 {
		if fn, ok := (*cbThunk)(unsafe.Pointer(ud1)).fn.(BufferMapFn); ok && fn != nil {
			fn(status, message)
		}
	}
	return 0
})

var cbCompilationInfo = syscall.NewCallback(func(c_status, c_compilationInfo, ud1, ud2 uintptr) uintptr {
	status := CompilationInfoRequestStatus(c_status)
	var compilationInfo CompilationInfo
	if c_compilationInfo != 0 {
		compilationInfo = *(*CompilationInfo)(unsafe.Pointer(c_compilationInfo))
	}
	if ud1 != 0 {
		if fn, ok := (*cbThunk)(unsafe.Pointer(ud1)).fn.(CompilationInfoFn); ok && fn != nil {
			fn(compilationInfo, status)
		}
	}
	return 0
})

var cbCreateComputePipelineAsync = syscall.NewCallback(func(c_status, c_pipeline, c_message, ud1, ud2 uintptr) uintptr {
	status := CreatePipelineAsyncStatus(c_status)
	pipeline := ComputePipeline(unsafe.Pointer(c_pipeline))
	message := goStringFromView(c_message)
	if ud1 != 0 {
		if fn, ok := (*cbThunk)(unsafe.Pointer(ud1)).fn.(CreateComputePipelineAsyncFn); ok && fn != nil {
			fn(pipeline, status, message)
		}
	}
	return 0
})

var cbCreateRenderPipelineAsync = syscall.NewCallback(func(c_status, c_pipeline, c_message, ud1, ud2 uintptr) uintptr {
	status := CreatePipelineAsyncStatus(c_status)
	pipeline := RenderPipeline(unsafe.Pointer(c_pipeline))
	message := goStringFromView(c_message)
	if ud1 != 0 {
		if fn, ok := (*cbThunk)(unsafe.Pointer(ud1)).fn.(CreateRenderPipelineAsyncFn); ok && fn != nil {
			fn(pipeline, status, message)
		}
	}
	return 0
})

var cbPopErrorScope = syscall.NewCallback(func(c_status, c_typeVal, c_message, ud1, ud2 uintptr) uintptr {
	emsg := goStringFromView(c_message)
	status := PopErrorScopeStatus(c_status)
	err := errorFromErrorType(ErrorType(c_typeVal), emsg)
	if ud1 != 0 {
		if fn, ok := (*cbThunk)(unsafe.Pointer(ud1)).fn.(PopErrorScopeFn); ok && fn != nil {
			fn(err, status)
		}
	}
	return 0
})

var cbQueueWorkDone = syscall.NewCallback(func(c_status, c_message, ud1, ud2 uintptr) uintptr {
	status := QueueWorkDoneStatus(c_status)
	message := goStringFromView(c_message)
	if ud1 != 0 {
		if fn, ok := (*cbThunk)(unsafe.Pointer(ud1)).fn.(QueueWorkDoneFn); ok && fn != nil {
			fn(status, message)
		}
	}
	return 0
})

var cbRequestAdapter = syscall.NewCallback(func(c_status, c_adapter, c_message, ud1, ud2 uintptr) uintptr {
	status := RequestAdapterStatus(c_status)
	adapter := Adapter(unsafe.Pointer(c_adapter))
	message := goStringFromView(c_message)
	if ud1 != 0 {
		if fn, ok := (*cbThunk)(unsafe.Pointer(ud1)).fn.(RequestAdapterFn); ok && fn != nil {
			fn(adapter, status, message)
		}
	}
	return 0
})

var cbRequestDevice = syscall.NewCallback(func(c_status, c_device, c_message, ud1, ud2 uintptr) uintptr {
	status := RequestDeviceStatus(c_status)
	device := Device(unsafe.Pointer(c_device))
	message := goStringFromView(c_message)
	if ud1 != 0 {
		if fn, ok := (*cbThunk)(unsafe.Pointer(ud1)).fn.(RequestDeviceFn); ok && fn != nil {
			fn(device, status, message)
		}
	}
	return 0
})

func releaseAdapter(p unsafe.Pointer) {
	procAdapterRelease.Call(uintptr(p))
}

func releaseBindGroup(p unsafe.Pointer) {
	procBindGroupRelease.Call(uintptr(p))
}

func releaseBindGroupLayout(p unsafe.Pointer) {
	procBindGroupLayoutRelease.Call(uintptr(p))
}

func releaseBuffer(p unsafe.Pointer) {
	procBufferRelease.Call(uintptr(p))
}

func releaseCommandBuffer(p unsafe.Pointer) {
	procCommandBufferRelease.Call(uintptr(p))
}

func releaseCommandEncoder(p unsafe.Pointer) {
	procCommandEncoderRelease.Call(uintptr(p))
}

func releaseComputePassEncoder(p unsafe.Pointer) {
	procComputePassEncoderRelease.Call(uintptr(p))
}

func releaseComputePipeline(p unsafe.Pointer) {
	procComputePipelineRelease.Call(uintptr(p))
}

func releaseDevice(p unsafe.Pointer) {
	procDeviceRelease.Call(uintptr(p))
}

func releaseExternalTexture(p unsafe.Pointer) {
	procExternalTextureRelease.Call(uintptr(p))
}

func releaseInstance(p unsafe.Pointer) {
	procInstanceRelease.Call(uintptr(p))
}

func releasePipelineLayout(p unsafe.Pointer) {
	procPipelineLayoutRelease.Call(uintptr(p))
}

func releaseQuerySet(p unsafe.Pointer) {
	procQuerySetRelease.Call(uintptr(p))
}

func releaseQueue(p unsafe.Pointer) {
	procQueueRelease.Call(uintptr(p))
}

func releaseRenderBundle(p unsafe.Pointer) {
	procRenderBundleRelease.Call(uintptr(p))
}

func releaseRenderBundleEncoder(p unsafe.Pointer) {
	procRenderBundleEncoderRelease.Call(uintptr(p))
}

func releaseRenderPassEncoder(p unsafe.Pointer) {
	procRenderPassEncoderRelease.Call(uintptr(p))
}

func releaseRenderPipeline(p unsafe.Pointer) {
	procRenderPipelineRelease.Call(uintptr(p))
}

func releaseSampler(p unsafe.Pointer) {
	procSamplerRelease.Call(uintptr(p))
}

func releaseShaderModule(p unsafe.Pointer) {
	procShaderModuleRelease.Call(uintptr(p))
}

func releaseSurface(p unsafe.Pointer) {
	procSurfaceRelease.Call(uintptr(p))
}

func releaseTexture(p unsafe.Pointer) {
	procTextureRelease.Call(uintptr(p))
}

func releaseTextureView(p unsafe.Pointer) {
	procTextureViewRelease.Call(uintptr(p))
}

// Create a WGPUInstance

func CreateInstance(descriptor *InstanceDescriptor) Instance {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if descriptor.RequiredLimits != nil {
			pinner.Pin(descriptor.RequiredLimits)
		}
		if descriptor.RequiredFeatures != nil {
			pinner.Pin(descriptor.RequiredFeatures)
		}
	}
	r1, _, _ := procCreateInstance.Call(uintptr(unsafe.Pointer(descriptor)))
	return wrapInstance(unsafe.Pointer(r1))
}

// Get the list of @ref WGPUInstanceFeatureName values supported by the instance.

func GetInstanceFeatures(features *SupportedInstanceFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if features != nil {
		pinner.Pin(features)
		if features.Features != nil {
			pinner.Pin(features.Features)
		}
	}
	procGetInstanceFeatures.Call(uintptr(unsafe.Pointer(features)))
}

// Get the limits supported by the instance.

func GetInstanceLimits(limits *InstanceLimits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if limits != nil {
		pinner.Pin(limits)
		if limits.NextInChain != nil {
			pinner.Pin(limits.NextInChain)
		}
	}
	r1, _, _ := procGetInstanceLimits.Call(uintptr(unsafe.Pointer(limits)))
	return Status(r1)
}

// Check whether a particular @ref WGPUInstanceFeatureName is supported by the instance.

func HasInstanceFeature(feature InstanceFeatureName) Bool {
	r1, _, _ := procHasInstanceFeature.Call(uintptr(feature))
	return Bool(r1)
}

func AdapterGetLimits(a Adapter, limits *Limits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if limits != nil {
		pinner.Pin(limits)
		if limits.NextInChain != nil {
			pinner.Pin(limits.NextInChain)
		}
	}
	r1, _, _ := procAdapterGetLimits.Call(uintptr(unsafe.Pointer(a)), uintptr(unsafe.Pointer(limits)))
	return Status(r1)
}

func AdapterHasFeature(a Adapter, feature FeatureName) Bool {
	r1, _, _ := procAdapterHasFeature.Call(uintptr(unsafe.Pointer(a)), uintptr(feature))
	return Bool(r1)
}

// Get the list of @ref WGPUFeatureName values supported by the adapter.

func AdapterGetFeatures(a Adapter, features *SupportedFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if features != nil {
		pinner.Pin(features)
		if features.Features != nil {
			pinner.Pin(features.Features)
		}
	}
	procAdapterGetFeatures.Call(uintptr(unsafe.Pointer(a)), uintptr(unsafe.Pointer(features)))
}

func AdapterGetInfo(a Adapter, info *AdapterInfo) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if info != nil {
		pinner.Pin(info)
		if info.NextInChain != nil {
			pinner.Pin(info.NextInChain)
		}
		if len(info.Vendor) > 0 {
			pinner.Pin(unsafe.StringData(info.Vendor))
		}
		if len(info.Architecture) > 0 {
			pinner.Pin(unsafe.StringData(info.Architecture))
		}
		if len(info.Device) > 0 {
			pinner.Pin(unsafe.StringData(info.Device))
		}
		if len(info.Description) > 0 {
			pinner.Pin(unsafe.StringData(info.Description))
		}
	}
	r1, _, _ := procAdapterGetInfo.Call(uintptr(unsafe.Pointer(a)), uintptr(unsafe.Pointer(info)))
	return Status(r1)
}

func AdapterRequestDevice(a Adapter, descriptor *DeviceDescriptor) (Device, RequestDeviceStatus, string) {
	type _res struct {
		r0 Device
		r1 RequestDeviceStatus
		r2 string
	}
	_ch := make(chan _res, 1)
	callback := RequestDeviceFn(func(r0 Device, r1 RequestDeviceStatus, r2 string) {
		_ch <- _res{r0, r1, r2}
	})
	_cbThunk := &cbThunk{fn: callback}
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if len(descriptor.DefaultQueue.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.DefaultQueue.Label))
		}
		if descriptor.RequiredLimits != nil {
			pinner.Pin(descriptor.RequiredLimits)
		}
		if descriptor.RequiredFeatures != nil {
			pinner.Pin(descriptor.RequiredFeatures)
		}
	}
	_cbInfo := RequestDeviceCallbackInfo{
		Mode:      CallbackModeAllowProcessEvents,
		Callback:  cbRequestDevice,
		Userdata1: unsafe.Pointer(_cbThunk),
	}
	r1, _, _ := procAdapterRequestDevice.Call(uintptr(unsafe.Pointer(a)), uintptr(unsafe.Pointer(descriptor)), uintptr(unsafe.Pointer(&_cbInfo)))
	_ = r1
	_out := waitRecv(_ch)
	runtime.KeepAlive(_cbThunk)
	return _out.r0, _out.r1, _out.r2
}

func AdapterRelease(a Adapter) {
	if x := a; x != nil {
		releaseAdapter(unsafe.Pointer(x))
	}
}

func BindGroupSetLabel(b BindGroup, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procBindGroupSetLabel.Call(uintptr(unsafe.Pointer(b)), uintptr(unsafe.Pointer(&label_sv)))
}

func BindGroupRelease(b BindGroup) {
	if x := b; x != nil {
		releaseBindGroup(unsafe.Pointer(x))
	}
}

func BindGroupLayoutSetLabel(b BindGroupLayout, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procBindGroupLayoutSetLabel.Call(uintptr(unsafe.Pointer(b)), uintptr(unsafe.Pointer(&label_sv)))
}

func BindGroupLayoutRelease(b BindGroupLayout) {
	if x := b; x != nil {
		releaseBindGroupLayout(unsafe.Pointer(x))
	}
}

func BufferMap(b Buffer, mode MapMode, offset uintptr, size uintptr) (MapAsyncStatus, string) {
	type _res struct {
		r0 MapAsyncStatus
		r1 string
	}
	_ch := make(chan _res, 1)
	callback := BufferMapFn(func(r0 MapAsyncStatus, r1 string) {
		_ch <- _res{r0, r1}
	})
	_cbThunk := &cbThunk{fn: callback}
	_cbInfo := BufferMapCallbackInfo{
		Mode:      CallbackModeAllowProcessEvents,
		Callback:  cbBufferMap,
		Userdata1: unsafe.Pointer(_cbThunk),
	}
	r1, _, _ := procBufferMap.Call(uintptr(unsafe.Pointer(b)), uintptr(mode), uintptr(offset), uintptr(size), uintptr(unsafe.Pointer(&_cbInfo)))
	_ = r1
	_out := waitRecv(_ch)
	runtime.KeepAlive(_cbThunk)
	return _out.r0, _out.r1
}

// Returns a mutable pointer to beginning of the mapped range.
// See @ref MappedRangeBehavior for error conditions and guarantees.
// This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).
//
// In Wasm, if `memcpy`ing into this range, prefer using @ref wgpuBufferWriteMappedRange
// instead for better performance.

func BufferGetMappedRange(b Buffer, offset uintptr, size uintptr) unsafe.Pointer {
	r1, _, _ := procBufferGetMappedRange.Call(uintptr(unsafe.Pointer(b)), uintptr(offset), uintptr(size))
	return unsafe.Pointer(r1)
}

// Returns a const pointer to beginning of the mapped range.
// It must not be written; writing to this range causes undefined behavior.
// See @ref MappedRangeBehavior for error conditions and guarantees.
// This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).
//
// In Wasm, if `memcpy`ing from this range, prefer using @ref wgpuBufferReadMappedRange
// instead for better performance.

func BufferGetConstMappedRange(b Buffer, offset uintptr, size uintptr) unsafe.Pointer {
	r1, _, _ := procBufferGetConstMappedRange.Call(uintptr(unsafe.Pointer(b)), uintptr(offset), uintptr(size))
	return unsafe.Pointer(r1)
}

// Copies a range of data from the buffer mapping into the provided destination pointer.
// See @ref MappedRangeBehavior for error conditions and guarantees.
// This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).
//
// In Wasm, this is more efficient than copying from a mapped range into a `malloc`'d range.

func BufferReadMappedRange(b Buffer, offset uintptr, data unsafe.Pointer, size uintptr) Status {
	r1, _, _ := procBufferReadMappedRange.Call(uintptr(unsafe.Pointer(b)), uintptr(offset), uintptr(data), uintptr(size))
	return Status(r1)
}

// Copies a range of data from the provided source pointer into the buffer mapping.
// See @ref MappedRangeBehavior for error conditions and guarantees.
// This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).
//
// In Wasm, this is more efficient than copying from a `malloc`'d range into a mapped range.

func BufferWriteMappedRange(b Buffer, offset uintptr, data unsafe.Pointer, size uintptr) Status {
	r1, _, _ := procBufferWriteMappedRange.Call(uintptr(unsafe.Pointer(b)), uintptr(offset), uintptr(data), uintptr(size))
	return Status(r1)
}

func BufferSetLabel(b Buffer, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procBufferSetLabel.Call(uintptr(unsafe.Pointer(b)), uintptr(unsafe.Pointer(&label_sv)))
}

func BufferGetUsage(b Buffer) BufferUsage {
	r1, _, _ := procBufferGetUsage.Call(uintptr(unsafe.Pointer(b)))
	return (BufferUsage)(r1)
}

func BufferGetSize(b Buffer) uint64 {
	r1, _, _ := procBufferGetSize.Call(uintptr(unsafe.Pointer(b)))
	return (uint64)(r1)
}

func BufferGetMapState(b Buffer) BufferMapState {
	r1, _, _ := procBufferGetMapState.Call(uintptr(unsafe.Pointer(b)))
	return (BufferMapState)(r1)
}

func BufferUnmap(b Buffer) {
	procBufferUnmap.Call(uintptr(unsafe.Pointer(b)))
}

func BufferDestroy(b Buffer) {
	procBufferDestroy.Call(uintptr(unsafe.Pointer(b)))
}

func BufferRelease(b Buffer) {
	if x := b; x != nil {
		releaseBuffer(unsafe.Pointer(x))
	}
}

func CommandBufferSetLabel(c CommandBuffer, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procCommandBufferSetLabel.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(&label_sv)))
}

func CommandBufferRelease(c CommandBuffer) {
	if x := c; x != nil {
		releaseCommandBuffer(unsafe.Pointer(x))
	}
}

func CommandEncoderFinish(c CommandEncoder, descriptor *CommandBufferDescriptor) CommandBuffer {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	r1, _, _ := procCommandEncoderFinish.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(descriptor)))
	return CommandBuffer(unsafe.Pointer(r1))
}

func CommandEncoderBeginComputePass(c CommandEncoder, descriptor *ComputePassDescriptor) ComputePassEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.TimestampWrites != nil {
			pinner.Pin(descriptor.TimestampWrites)
		}
	}
	r1, _, _ := procCommandEncoderBeginComputePass.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(descriptor)))
	return ComputePassEncoder(unsafe.Pointer(r1))
}

func CommandEncoderBeginRenderPass(c CommandEncoder, descriptor *RenderPassDescriptor) RenderPassEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.DepthStencilAttachment != nil {
			pinner.Pin(descriptor.DepthStencilAttachment)
		}
		if descriptor.TimestampWrites != nil {
			pinner.Pin(descriptor.TimestampWrites)
		}
		if descriptor.ColorAttachments != nil {
			pinner.Pin(descriptor.ColorAttachments)
		}
	}
	r1, _, _ := procCommandEncoderBeginRenderPass.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(descriptor)))
	return RenderPassEncoder(unsafe.Pointer(r1))
}

func CommandEncoderCopyBufferToBuffer(c CommandEncoder, source Buffer, sourceOffset uint64, destination Buffer, destinationOffset uint64, size uint64) {
	procCommandEncoderCopyBufferToBuffer.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(source)), uintptr(sourceOffset), uintptr(unsafe.Pointer(destination)), uintptr(destinationOffset), uintptr(size))
}

func CommandEncoderCopyBufferToTexture(c CommandEncoder, source *TexelCopyBufferInfo, destination *TexelCopyTextureInfo, copySize *Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if source != nil {
		pinner.Pin(source)
	}
	if destination != nil {
		pinner.Pin(destination)
	}
	if copySize != nil {
		pinner.Pin(copySize)
	}
	procCommandEncoderCopyBufferToTexture.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(source)), uintptr(unsafe.Pointer(destination)), uintptr(unsafe.Pointer(copySize)))
}

func CommandEncoderCopyTextureToBuffer(c CommandEncoder, source *TexelCopyTextureInfo, destination *TexelCopyBufferInfo, copySize *Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if source != nil {
		pinner.Pin(source)
	}
	if destination != nil {
		pinner.Pin(destination)
	}
	if copySize != nil {
		pinner.Pin(copySize)
	}
	procCommandEncoderCopyTextureToBuffer.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(source)), uintptr(unsafe.Pointer(destination)), uintptr(unsafe.Pointer(copySize)))
}

func CommandEncoderCopyTextureToTexture(c CommandEncoder, source *TexelCopyTextureInfo, destination *TexelCopyTextureInfo, copySize *Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if source != nil {
		pinner.Pin(source)
	}
	if destination != nil {
		pinner.Pin(destination)
	}
	if copySize != nil {
		pinner.Pin(copySize)
	}
	procCommandEncoderCopyTextureToTexture.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(source)), uintptr(unsafe.Pointer(destination)), uintptr(unsafe.Pointer(copySize)))
}

func CommandEncoderClearBuffer(c CommandEncoder, buffer Buffer, offset uint64, size uint64) {
	procCommandEncoderClearBuffer.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(buffer)), uintptr(offset), uintptr(size))
}

func CommandEncoderInsertDebugMarker(c CommandEncoder, markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	markerLabel_sv := syscallStringView(markerLabel, &pinner)
	procCommandEncoderInsertDebugMarker.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(&markerLabel_sv)))
}

func CommandEncoderPopDebugGroup(c CommandEncoder) {
	procCommandEncoderPopDebugGroup.Call(uintptr(unsafe.Pointer(c)))
}

func CommandEncoderPushDebugGroup(c CommandEncoder, groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	groupLabel_sv := syscallStringView(groupLabel, &pinner)
	procCommandEncoderPushDebugGroup.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(&groupLabel_sv)))
}

func CommandEncoderResolveQuerySet(c CommandEncoder, querySet QuerySet, firstQuery uint32, queryCount uint32, destination Buffer, destinationOffset uint64) {
	procCommandEncoderResolveQuerySet.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(querySet)), uintptr(firstQuery), uintptr(queryCount), uintptr(unsafe.Pointer(destination)), uintptr(destinationOffset))
}

func CommandEncoderWriteTimestamp(c CommandEncoder, querySet QuerySet, queryIndex uint32) {
	procCommandEncoderWriteTimestamp.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(querySet)), uintptr(queryIndex))
}

func CommandEncoderSetLabel(c CommandEncoder, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procCommandEncoderSetLabel.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(&label_sv)))
}

func CommandEncoderRelease(c CommandEncoder) {
	if x := c; x != nil {
		releaseCommandEncoder(unsafe.Pointer(x))
	}
}

func ComputePassEncoderInsertDebugMarker(c ComputePassEncoder, markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	markerLabel_sv := syscallStringView(markerLabel, &pinner)
	procComputePassEncoderInsertDebugMarker.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(&markerLabel_sv)))
}

func ComputePassEncoderPopDebugGroup(c ComputePassEncoder) {
	procComputePassEncoderPopDebugGroup.Call(uintptr(unsafe.Pointer(c)))
}

func ComputePassEncoderPushDebugGroup(c ComputePassEncoder, groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	groupLabel_sv := syscallStringView(groupLabel, &pinner)
	procComputePassEncoderPushDebugGroup.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(&groupLabel_sv)))
}

func ComputePassEncoderSetPipeline(c ComputePassEncoder, pipeline ComputePipeline) {
	procComputePassEncoderSetPipeline.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(pipeline)))
}

func ComputePassEncoderSetBindGroup(c ComputePassEncoder, groupIndex uint32, group BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	procComputePassEncoderSetBindGroup.Call(uintptr(unsafe.Pointer(c)), uintptr(groupIndex), uintptr(unsafe.Pointer(group)), uintptr(len(dynamicOffsets)), uintptr(slicePtr(dynamicOffsets)))
}

func ComputePassEncoderSetImmediates(c ComputePassEncoder, offset uint32, data unsafe.Pointer, size uintptr) {
	procComputePassEncoderSetImmediates.Call(uintptr(unsafe.Pointer(c)), uintptr(offset), uintptr(data), uintptr(size))
}

func ComputePassEncoderDispatchWorkgroups(c ComputePassEncoder, workgroupCountX uint32, workgroupCountY uint32, workgroupCountZ uint32) {
	procComputePassEncoderDispatchWorkgroups.Call(uintptr(unsafe.Pointer(c)), uintptr(workgroupCountX), uintptr(workgroupCountY), uintptr(workgroupCountZ))
}

func ComputePassEncoderDispatchWorkgroupsIndirect(c ComputePassEncoder, indirectBuffer Buffer, indirectOffset uint64) {
	procComputePassEncoderDispatchWorkgroupsIndirect.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(indirectBuffer)), uintptr(indirectOffset))
}

func ComputePassEncoderEnd(c ComputePassEncoder) {
	procComputePassEncoderEnd.Call(uintptr(unsafe.Pointer(c)))
}

func ComputePassEncoderSetLabel(c ComputePassEncoder, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procComputePassEncoderSetLabel.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(&label_sv)))
}

func ComputePassEncoderRelease(c ComputePassEncoder) {
	if x := c; x != nil {
		releaseComputePassEncoder(unsafe.Pointer(x))
	}
}

func ComputePipelineGetBindGroupLayout(c ComputePipeline, groupIndex uint32) BindGroupLayout {
	r1, _, _ := procComputePipelineGetBindGroupLayout.Call(uintptr(unsafe.Pointer(c)), uintptr(groupIndex))
	return BindGroupLayout(unsafe.Pointer(r1))
}

func ComputePipelineSetLabel(c ComputePipeline, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procComputePipelineSetLabel.Call(uintptr(unsafe.Pointer(c)), uintptr(unsafe.Pointer(&label_sv)))
}

func ComputePipelineRelease(c ComputePipeline) {
	if x := c; x != nil {
		releaseComputePipeline(unsafe.Pointer(x))
	}
}

func DeviceCreateBindGroup(d Device, descriptor *BindGroupDescriptor) BindGroup {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.Entries != nil {
			pinner.Pin(descriptor.Entries)
		}
	}
	r1, _, _ := procDeviceCreateBindGroup.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return BindGroup(unsafe.Pointer(r1))
}

func DeviceCreateBindGroupLayout(d Device, descriptor *BindGroupLayoutDescriptor) BindGroupLayout {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.Entries != nil {
			pinner.Pin(descriptor.Entries)
		}
	}
	r1, _, _ := procDeviceCreateBindGroupLayout.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return BindGroupLayout(unsafe.Pointer(r1))
}

// TODO
//
// If @ref WGPUBufferDescriptor::mappedAtCreation is `true` and the mapping allocation fails,
// returns `NULL`.

func DeviceCreateBuffer(d Device, descriptor *BufferDescriptor) Buffer {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	r1, _, _ := procDeviceCreateBuffer.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return Buffer(unsafe.Pointer(r1))
}

func DeviceCreateCommandEncoder(d Device, descriptor *CommandEncoderDescriptor) CommandEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	r1, _, _ := procDeviceCreateCommandEncoder.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return CommandEncoder(unsafe.Pointer(r1))
}

func DeviceCreateComputePipeline(d Device, descriptor *ComputePipelineDescriptor) ComputePipeline {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if len(descriptor.Compute.EntryPoint) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Compute.EntryPoint))
		}
		if descriptor.Compute.Constants != nil {
			pinner.Pin(descriptor.Compute.Constants)
		}
	}
	r1, _, _ := procDeviceCreateComputePipeline.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return ComputePipeline(unsafe.Pointer(r1))
}

func DeviceCreateComputePipelineAsync(d Device, descriptor *ComputePipelineDescriptor) (ComputePipeline, CreatePipelineAsyncStatus, string) {
	type _res struct {
		r0 ComputePipeline
		r1 CreatePipelineAsyncStatus
		r2 string
	}
	_ch := make(chan _res, 1)
	callback := CreateComputePipelineAsyncFn(func(r0 ComputePipeline, r1 CreatePipelineAsyncStatus, r2 string) {
		_ch <- _res{r0, r1, r2}
	})
	_cbThunk := &cbThunk{fn: callback}
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if len(descriptor.Compute.EntryPoint) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Compute.EntryPoint))
		}
		if descriptor.Compute.Constants != nil {
			pinner.Pin(descriptor.Compute.Constants)
		}
	}
	_cbInfo := CreateComputePipelineAsyncCallbackInfo{
		Mode:      CallbackModeAllowProcessEvents,
		Callback:  cbCreateComputePipelineAsync,
		Userdata1: unsafe.Pointer(_cbThunk),
	}
	r1, _, _ := procDeviceCreateComputePipelineAsync.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)), uintptr(unsafe.Pointer(&_cbInfo)))
	_ = r1
	_out := waitRecv(_ch)
	runtime.KeepAlive(_cbThunk)
	return _out.r0, _out.r1, _out.r2
}

func DeviceCreatePipelineLayout(d Device, descriptor *PipelineLayoutDescriptor) PipelineLayout {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.BindGroupLayouts != nil {
			pinner.Pin(descriptor.BindGroupLayouts)
		}
	}
	r1, _, _ := procDeviceCreatePipelineLayout.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return PipelineLayout(unsafe.Pointer(r1))
}

func DeviceCreateQuerySet(d Device, descriptor *QuerySetDescriptor) QuerySet {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	r1, _, _ := procDeviceCreateQuerySet.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return QuerySet(unsafe.Pointer(r1))
}

func DeviceCreateRenderPipelineAsync(d Device, descriptor *RenderPipelineDescriptor) (RenderPipeline, CreatePipelineAsyncStatus, string) {
	type _res struct {
		r0 RenderPipeline
		r1 CreatePipelineAsyncStatus
		r2 string
	}
	_ch := make(chan _res, 1)
	callback := CreateRenderPipelineAsyncFn(func(r0 RenderPipeline, r1 CreatePipelineAsyncStatus, r2 string) {
		_ch <- _res{r0, r1, r2}
	})
	_cbThunk := &cbThunk{fn: callback}
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if len(descriptor.Vertex.EntryPoint) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Vertex.EntryPoint))
		}
		if descriptor.DepthStencil != nil {
			pinner.Pin(descriptor.DepthStencil)
		}
		if descriptor.Fragment != nil {
			pinner.Pin(descriptor.Fragment)
		}
		if descriptor.Vertex.Constants != nil {
			pinner.Pin(descriptor.Vertex.Constants)
		}
		if descriptor.Vertex.Buffers != nil {
			pinner.Pin(descriptor.Vertex.Buffers)
		}
	}
	_cbInfo := CreateRenderPipelineAsyncCallbackInfo{
		Mode:      CallbackModeAllowProcessEvents,
		Callback:  cbCreateRenderPipelineAsync,
		Userdata1: unsafe.Pointer(_cbThunk),
	}
	r1, _, _ := procDeviceCreateRenderPipelineAsync.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)), uintptr(unsafe.Pointer(&_cbInfo)))
	_ = r1
	_out := waitRecv(_ch)
	runtime.KeepAlive(_cbThunk)
	return _out.r0, _out.r1, _out.r2
}

func DeviceCreateRenderBundleEncoder(d Device, descriptor *RenderBundleEncoderDescriptor) RenderBundleEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.ColorFormats != nil {
			pinner.Pin(descriptor.ColorFormats)
		}
	}
	r1, _, _ := procDeviceCreateRenderBundleEncoder.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return RenderBundleEncoder(unsafe.Pointer(r1))
}

func DeviceCreateRenderPipeline(d Device, descriptor *RenderPipelineDescriptor) RenderPipeline {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if len(descriptor.Vertex.EntryPoint) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Vertex.EntryPoint))
		}
		if descriptor.DepthStencil != nil {
			pinner.Pin(descriptor.DepthStencil)
		}
		if descriptor.Fragment != nil {
			pinner.Pin(descriptor.Fragment)
		}
		if descriptor.Vertex.Constants != nil {
			pinner.Pin(descriptor.Vertex.Constants)
		}
		if descriptor.Vertex.Buffers != nil {
			pinner.Pin(descriptor.Vertex.Buffers)
		}
	}
	r1, _, _ := procDeviceCreateRenderPipeline.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return RenderPipeline(unsafe.Pointer(r1))
}

func DeviceCreateSampler(d Device, descriptor *SamplerDescriptor) Sampler {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	r1, _, _ := procDeviceCreateSampler.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return Sampler(unsafe.Pointer(r1))
}

func DeviceCreateShaderModule(d Device, descriptor *ShaderModuleDescriptor) ShaderModule {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	r1, _, _ := procDeviceCreateShaderModule.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return ShaderModule(unsafe.Pointer(r1))
}

func DeviceCreateTexture(d Device, descriptor *TextureDescriptor) Texture {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
		if descriptor.ViewFormats != nil {
			pinner.Pin(descriptor.ViewFormats)
		}
	}
	r1, _, _ := procDeviceCreateTexture.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(descriptor)))
	return Texture(unsafe.Pointer(r1))
}

func DeviceDestroy(d Device) {
	procDeviceDestroy.Call(uintptr(unsafe.Pointer(d)))
}

func DeviceGetLostFuture(d Device) Future {
	r1, _, _ := procDeviceGetLostFuture.Call(uintptr(unsafe.Pointer(d)))
	return Future{Id: uint64(r1)}
}

func DeviceGetLimits(d Device, limits *Limits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if limits != nil {
		pinner.Pin(limits)
		if limits.NextInChain != nil {
			pinner.Pin(limits.NextInChain)
		}
	}
	r1, _, _ := procDeviceGetLimits.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(limits)))
	return Status(r1)
}

func DeviceHasFeature(d Device, feature FeatureName) Bool {
	r1, _, _ := procDeviceHasFeature.Call(uintptr(unsafe.Pointer(d)), uintptr(feature))
	return Bool(r1)
}

// Get the list of @ref WGPUFeatureName values supported by the device.

func DeviceGetFeatures(d Device, features *SupportedFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if features != nil {
		pinner.Pin(features)
		if features.Features != nil {
			pinner.Pin(features.Features)
		}
	}
	procDeviceGetFeatures.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(features)))
}

func DeviceGetAdapterInfo(d Device, adapterInfo *AdapterInfo) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if adapterInfo != nil {
		pinner.Pin(adapterInfo)
		if adapterInfo.NextInChain != nil {
			pinner.Pin(adapterInfo.NextInChain)
		}
		if len(adapterInfo.Vendor) > 0 {
			pinner.Pin(unsafe.StringData(adapterInfo.Vendor))
		}
		if len(adapterInfo.Architecture) > 0 {
			pinner.Pin(unsafe.StringData(adapterInfo.Architecture))
		}
		if len(adapterInfo.Device) > 0 {
			pinner.Pin(unsafe.StringData(adapterInfo.Device))
		}
		if len(adapterInfo.Description) > 0 {
			pinner.Pin(unsafe.StringData(adapterInfo.Description))
		}
	}
	r1, _, _ := procDeviceGetAdapterInfo.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(adapterInfo)))
	return Status(r1)
}

func DeviceGetQueue(d Device) Queue {
	r1, _, _ := procDeviceGetQueue.Call(uintptr(unsafe.Pointer(d)))
	return Queue(unsafe.Pointer(r1))
}

// Pushes an error scope to the current thread's error scope stack.
// See @ref ErrorScopes.

func DevicePushErrorScope(d Device, filter ErrorFilter) {
	procDevicePushErrorScope.Call(uintptr(unsafe.Pointer(d)), uintptr(filter))
}

// Pops an error scope to the current thread's error scope stack,
// asynchronously returning the result. See @ref ErrorScopes.

func DevicePopErrorScope(d Device) (error, PopErrorScopeStatus) {
	type _res struct {
		r0 error
		r1 PopErrorScopeStatus
	}
	_ch := make(chan _res, 1)
	callback := PopErrorScopeFn(func(r0 error, r1 PopErrorScopeStatus) {
		_ch <- _res{r0, r1}
	})
	_cbThunk := &cbThunk{fn: callback}
	_cbInfo := PopErrorScopeCallbackInfo{
		Mode:      CallbackModeAllowProcessEvents,
		Callback:  cbPopErrorScope,
		Userdata1: unsafe.Pointer(_cbThunk),
	}
	r1, _, _ := procDevicePopErrorScope.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(&_cbInfo)))
	_ = r1
	_out := waitRecv(_ch)
	runtime.KeepAlive(_cbThunk)
	return _out.r0, _out.r1
}

func DeviceSetLabel(d Device, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procDeviceSetLabel.Call(uintptr(unsafe.Pointer(d)), uintptr(unsafe.Pointer(&label_sv)))
}

func DeviceRelease(d Device) {
	if x := d; x != nil {
		releaseDevice(unsafe.Pointer(x))
	}
}

func ExternalTextureSetLabel(e ExternalTexture, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procExternalTextureSetLabel.Call(uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(&label_sv)))
}

func ExternalTextureRelease(e ExternalTexture) {
	if x := e; x != nil {
		releaseExternalTexture(unsafe.Pointer(x))
	}
}

// Creates a @ref WGPUSurface, see @ref Surface-Creation for more details.

func InstanceCreateSurface(i Instance, descriptor *SurfaceDescriptor) Surface {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	r1, _, _ := procInstanceCreateSurface.Call(uintptr(unsafe.Pointer(i)), uintptr(unsafe.Pointer(descriptor)))
	return Surface(unsafe.Pointer(r1))
}

// Get the list of @ref WGPUWGSLLanguageFeatureName values supported by the instance.

func InstanceGetWGSLLanguageFeatures(i Instance, features *SupportedWGSLLanguageFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if features != nil {
		pinner.Pin(features)
		if features.Features != nil {
			pinner.Pin(features.Features)
		}
	}
	procInstanceGetWGSLLanguageFeatures.Call(uintptr(unsafe.Pointer(i)), uintptr(unsafe.Pointer(features)))
}

func InstanceHasWGSLLanguageFeature(i Instance, feature WGSLLanguageFeatureName) Bool {
	r1, _, _ := procInstanceHasWGSLLanguageFeature.Call(uintptr(unsafe.Pointer(i)), uintptr(feature))
	return Bool(r1)
}

// Processes asynchronous events on this `WGPUInstance`, calling any callbacks for asynchronous operations created with @ref WGPUCallbackMode_AllowProcessEvents.
//
// See @ref Process-Events for more information.

func InstanceProcessEvents(i Instance) {
	procInstanceProcessEvents.Call(uintptr(unsafe.Pointer(i)))
}

func InstanceRequestAdapter(i Instance, options *RequestAdapterOptions) (Adapter, RequestAdapterStatus, string) {
	type _res struct {
		r0 Adapter
		r1 RequestAdapterStatus
		r2 string
	}
	_ch := make(chan _res, 1)
	callback := RequestAdapterFn(func(r0 Adapter, r1 RequestAdapterStatus, r2 string) {
		_ch <- _res{r0, r1, r2}
	})
	_cbThunk := &cbThunk{fn: callback}
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if options != nil {
		pinner.Pin(options)
		if options.NextInChain != nil {
			pinner.Pin(options.NextInChain)
		}
	}
	_cbInfo := RequestAdapterCallbackInfo{
		Mode:      CallbackModeAllowProcessEvents,
		Callback:  cbRequestAdapter,
		Userdata1: unsafe.Pointer(_cbThunk),
	}
	r1, _, _ := procInstanceRequestAdapter.Call(uintptr(unsafe.Pointer(i)), uintptr(unsafe.Pointer(options)), uintptr(unsafe.Pointer(&_cbInfo)))
	_ = r1
	_out := waitRecv(_ch)
	runtime.KeepAlive(_cbThunk)
	return _out.r0, _out.r1, _out.r2
}

// Wait for at least one WGPUFuture in `futures` to complete, and call callbacks of the respective completed asynchronous operations.
//
// See @ref Wait-Any for more information.

func InstanceWaitAny(i Instance, futureCount uintptr, futures *FutureWaitInfo, timeoutNS uint64) WaitStatus {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if futures != nil {
		pinner.Pin(futures)
	}
	r1, _, _ := procInstanceWaitAny.Call(uintptr(unsafe.Pointer(i)), uintptr(futureCount), uintptr(unsafe.Pointer(futures)), uintptr(timeoutNS))
	return WaitStatus(r1)
}

func InstanceRelease(i Instance) {
	if x := i; x != nil {
		removeInstance(x)
		releaseInstance(unsafe.Pointer(x))
	}
}

func PipelineLayoutSetLabel(p PipelineLayout, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procPipelineLayoutSetLabel.Call(uintptr(unsafe.Pointer(p)), uintptr(unsafe.Pointer(&label_sv)))
}

func PipelineLayoutRelease(p PipelineLayout) {
	if x := p; x != nil {
		releasePipelineLayout(unsafe.Pointer(x))
	}
}

func QuerySetSetLabel(q QuerySet, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procQuerySetSetLabel.Call(uintptr(unsafe.Pointer(q)), uintptr(unsafe.Pointer(&label_sv)))
}

func QuerySetGetType(q QuerySet) QueryType {
	r1, _, _ := procQuerySetGetType.Call(uintptr(unsafe.Pointer(q)))
	return (QueryType)(r1)
}

func QuerySetGetCount(q QuerySet) uint32 {
	r1, _, _ := procQuerySetGetCount.Call(uintptr(unsafe.Pointer(q)))
	return (uint32)(r1)
}

func QuerySetDestroy(q QuerySet) {
	procQuerySetDestroy.Call(uintptr(unsafe.Pointer(q)))
}

func QuerySetRelease(q QuerySet) {
	if x := q; x != nil {
		releaseQuerySet(unsafe.Pointer(x))
	}
}

func QueueSubmit(q Queue, commands []CommandBuffer) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(commands) > 0 {
		pinner.Pin(&commands[0])
	}
	procQueueSubmit.Call(uintptr(unsafe.Pointer(q)), uintptr(len(commands)), uintptr(slicePtr(commands)))
}

func QueueOnSubmittedWorkDone(q Queue) (QueueWorkDoneStatus, string) {
	type _res struct {
		r0 QueueWorkDoneStatus
		r1 string
	}
	_ch := make(chan _res, 1)
	callback := QueueWorkDoneFn(func(r0 QueueWorkDoneStatus, r1 string) {
		_ch <- _res{r0, r1}
	})
	_cbThunk := &cbThunk{fn: callback}
	_cbInfo := QueueWorkDoneCallbackInfo{
		Mode:      CallbackModeAllowProcessEvents,
		Callback:  cbQueueWorkDone,
		Userdata1: unsafe.Pointer(_cbThunk),
	}
	r1, _, _ := procQueueOnSubmittedWorkDone.Call(uintptr(unsafe.Pointer(q)), uintptr(unsafe.Pointer(&_cbInfo)))
	_ = r1
	_out := waitRecv(_ch)
	runtime.KeepAlive(_cbThunk)
	return _out.r0, _out.r1
}

// Produces a @ref DeviceError both content-timeline (`size` alignment) and device-timeline
// errors defined by the WebGPU specification.

func QueueWriteBuffer(q Queue, buffer Buffer, bufferOffset uint64, data unsafe.Pointer, size uintptr) {
	procQueueWriteBuffer.Call(uintptr(unsafe.Pointer(q)), uintptr(unsafe.Pointer(buffer)), uintptr(bufferOffset), uintptr(data), uintptr(size))
}

func QueueWriteTexture(q Queue, destination *TexelCopyTextureInfo, data unsafe.Pointer, dataSize uintptr, dataLayout *TexelCopyBufferLayout, writeSize *Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if destination != nil {
		pinner.Pin(destination)
	}
	if dataLayout != nil {
		pinner.Pin(dataLayout)
	}
	if writeSize != nil {
		pinner.Pin(writeSize)
	}
	procQueueWriteTexture.Call(uintptr(unsafe.Pointer(q)), uintptr(unsafe.Pointer(destination)), uintptr(data), uintptr(dataSize), uintptr(unsafe.Pointer(dataLayout)), uintptr(unsafe.Pointer(writeSize)))
}

func QueueSetLabel(q Queue, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procQueueSetLabel.Call(uintptr(unsafe.Pointer(q)), uintptr(unsafe.Pointer(&label_sv)))
}

func QueueRelease(q Queue) {
	if x := q; x != nil {
		releaseQueue(unsafe.Pointer(x))
	}
}

func RenderBundleSetLabel(r RenderBundle, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procRenderBundleSetLabel.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(&label_sv)))
}

func RenderBundleRelease(r RenderBundle) {
	if x := r; x != nil {
		releaseRenderBundle(unsafe.Pointer(x))
	}
}

func RenderBundleEncoderSetPipeline(r RenderBundleEncoder, pipeline RenderPipeline) {
	procRenderBundleEncoderSetPipeline.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(pipeline)))
}

func RenderBundleEncoderSetBindGroup(r RenderBundleEncoder, groupIndex uint32, group BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	procRenderBundleEncoderSetBindGroup.Call(uintptr(unsafe.Pointer(r)), uintptr(groupIndex), uintptr(unsafe.Pointer(group)), uintptr(len(dynamicOffsets)), uintptr(slicePtr(dynamicOffsets)))
}

func RenderBundleEncoderSetImmediates(r RenderBundleEncoder, offset uint32, data unsafe.Pointer, size uintptr) {
	procRenderBundleEncoderSetImmediates.Call(uintptr(unsafe.Pointer(r)), uintptr(offset), uintptr(data), uintptr(size))
}

func RenderBundleEncoderDraw(r RenderBundleEncoder, vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) {
	procRenderBundleEncoderDraw.Call(uintptr(unsafe.Pointer(r)), uintptr(vertexCount), uintptr(instanceCount), uintptr(firstVertex), uintptr(firstInstance))
}

func RenderBundleEncoderDrawIndexed(r RenderBundleEncoder, indexCount uint32, instanceCount uint32, firstIndex uint32, baseVertex int32, firstInstance uint32) {
	procRenderBundleEncoderDrawIndexed.Call(uintptr(unsafe.Pointer(r)), uintptr(indexCount), uintptr(instanceCount), uintptr(firstIndex), uintptr(baseVertex), uintptr(firstInstance))
}

func RenderBundleEncoderDrawIndirect(r RenderBundleEncoder, indirectBuffer Buffer, indirectOffset uint64) {
	procRenderBundleEncoderDrawIndirect.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(indirectBuffer)), uintptr(indirectOffset))
}

func RenderBundleEncoderDrawIndexedIndirect(r RenderBundleEncoder, indirectBuffer Buffer, indirectOffset uint64) {
	procRenderBundleEncoderDrawIndexedIndirect.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(indirectBuffer)), uintptr(indirectOffset))
}

func RenderBundleEncoderInsertDebugMarker(r RenderBundleEncoder, markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	markerLabel_sv := syscallStringView(markerLabel, &pinner)
	procRenderBundleEncoderInsertDebugMarker.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(&markerLabel_sv)))
}

func RenderBundleEncoderPopDebugGroup(r RenderBundleEncoder) {
	procRenderBundleEncoderPopDebugGroup.Call(uintptr(unsafe.Pointer(r)))
}

func RenderBundleEncoderPushDebugGroup(r RenderBundleEncoder, groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	groupLabel_sv := syscallStringView(groupLabel, &pinner)
	procRenderBundleEncoderPushDebugGroup.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(&groupLabel_sv)))
}

func RenderBundleEncoderSetVertexBuffer(r RenderBundleEncoder, slot uint32, buffer Buffer, offset uint64, size uint64) {
	procRenderBundleEncoderSetVertexBuffer.Call(uintptr(unsafe.Pointer(r)), uintptr(slot), uintptr(unsafe.Pointer(buffer)), uintptr(offset), uintptr(size))
}

func RenderBundleEncoderSetIndexBuffer(r RenderBundleEncoder, buffer Buffer, format IndexFormat, offset uint64, size uint64) {
	procRenderBundleEncoderSetIndexBuffer.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(buffer)), uintptr(format), uintptr(offset), uintptr(size))
}

func RenderBundleEncoderFinish(r RenderBundleEncoder, descriptor *RenderBundleDescriptor) RenderBundle {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	r1, _, _ := procRenderBundleEncoderFinish.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(descriptor)))
	return RenderBundle(unsafe.Pointer(r1))
}

func RenderBundleEncoderSetLabel(r RenderBundleEncoder, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procRenderBundleEncoderSetLabel.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(&label_sv)))
}

func RenderBundleEncoderRelease(r RenderBundleEncoder) {
	if x := r; x != nil {
		releaseRenderBundleEncoder(unsafe.Pointer(x))
	}
}

func RenderPassEncoderSetPipeline(r RenderPassEncoder, pipeline RenderPipeline) {
	procRenderPassEncoderSetPipeline.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(pipeline)))
}

func RenderPassEncoderSetBindGroup(r RenderPassEncoder, groupIndex uint32, group BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	procRenderPassEncoderSetBindGroup.Call(uintptr(unsafe.Pointer(r)), uintptr(groupIndex), uintptr(unsafe.Pointer(group)), uintptr(len(dynamicOffsets)), uintptr(slicePtr(dynamicOffsets)))
}

func RenderPassEncoderSetImmediates(r RenderPassEncoder, offset uint32, data unsafe.Pointer, size uintptr) {
	procRenderPassEncoderSetImmediates.Call(uintptr(unsafe.Pointer(r)), uintptr(offset), uintptr(data), uintptr(size))
}

func RenderPassEncoderDraw(r RenderPassEncoder, vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) {
	procRenderPassEncoderDraw.Call(uintptr(unsafe.Pointer(r)), uintptr(vertexCount), uintptr(instanceCount), uintptr(firstVertex), uintptr(firstInstance))
}

func RenderPassEncoderDrawIndexed(r RenderPassEncoder, indexCount uint32, instanceCount uint32, firstIndex uint32, baseVertex int32, firstInstance uint32) {
	procRenderPassEncoderDrawIndexed.Call(uintptr(unsafe.Pointer(r)), uintptr(indexCount), uintptr(instanceCount), uintptr(firstIndex), uintptr(baseVertex), uintptr(firstInstance))
}

func RenderPassEncoderDrawIndirect(r RenderPassEncoder, indirectBuffer Buffer, indirectOffset uint64) {
	procRenderPassEncoderDrawIndirect.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(indirectBuffer)), uintptr(indirectOffset))
}

func RenderPassEncoderDrawIndexedIndirect(r RenderPassEncoder, indirectBuffer Buffer, indirectOffset uint64) {
	procRenderPassEncoderDrawIndexedIndirect.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(indirectBuffer)), uintptr(indirectOffset))
}

func RenderPassEncoderExecuteBundles(r RenderPassEncoder, bundles []RenderBundle) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(bundles) > 0 {
		pinner.Pin(&bundles[0])
	}
	procRenderPassEncoderExecuteBundles.Call(uintptr(unsafe.Pointer(r)), uintptr(len(bundles)), uintptr(slicePtr(bundles)))
}

func RenderPassEncoderInsertDebugMarker(r RenderPassEncoder, markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	markerLabel_sv := syscallStringView(markerLabel, &pinner)
	procRenderPassEncoderInsertDebugMarker.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(&markerLabel_sv)))
}

func RenderPassEncoderPopDebugGroup(r RenderPassEncoder) {
	procRenderPassEncoderPopDebugGroup.Call(uintptr(unsafe.Pointer(r)))
}

func RenderPassEncoderPushDebugGroup(r RenderPassEncoder, groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	groupLabel_sv := syscallStringView(groupLabel, &pinner)
	procRenderPassEncoderPushDebugGroup.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(&groupLabel_sv)))
}

func RenderPassEncoderSetStencilReference(r RenderPassEncoder, reference uint32) {
	procRenderPassEncoderSetStencilReference.Call(uintptr(unsafe.Pointer(r)), uintptr(reference))
}

func RenderPassEncoderSetBlendConstant(r RenderPassEncoder, color *Color) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if color != nil {
		pinner.Pin(color)
	}
	procRenderPassEncoderSetBlendConstant.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(color)))
}

// TODO
//
// If any argument is non-finite, produces a @ref NonFiniteFloatValueError.

func RenderPassEncoderSetViewport(r RenderPassEncoder, x float32, y float32, width float32, height float32, minDepth float32, maxDepth float32) {
	procRenderPassEncoderSetViewport.Call(uintptr(unsafe.Pointer(r)), uintptr(x), uintptr(y), uintptr(width), uintptr(height), uintptr(minDepth), uintptr(maxDepth))
}

func RenderPassEncoderSetScissorRect(r RenderPassEncoder, x uint32, y uint32, width uint32, height uint32) {
	procRenderPassEncoderSetScissorRect.Call(uintptr(unsafe.Pointer(r)), uintptr(x), uintptr(y), uintptr(width), uintptr(height))
}

func RenderPassEncoderSetVertexBuffer(r RenderPassEncoder, slot uint32, buffer Buffer, offset uint64, size uint64) {
	procRenderPassEncoderSetVertexBuffer.Call(uintptr(unsafe.Pointer(r)), uintptr(slot), uintptr(unsafe.Pointer(buffer)), uintptr(offset), uintptr(size))
}

func RenderPassEncoderSetIndexBuffer(r RenderPassEncoder, buffer Buffer, format IndexFormat, offset uint64, size uint64) {
	procRenderPassEncoderSetIndexBuffer.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(buffer)), uintptr(format), uintptr(offset), uintptr(size))
}

func RenderPassEncoderBeginOcclusionQuery(r RenderPassEncoder, queryIndex uint32) {
	procRenderPassEncoderBeginOcclusionQuery.Call(uintptr(unsafe.Pointer(r)), uintptr(queryIndex))
}

func RenderPassEncoderEndOcclusionQuery(r RenderPassEncoder) {
	procRenderPassEncoderEndOcclusionQuery.Call(uintptr(unsafe.Pointer(r)))
}

func RenderPassEncoderEnd(r RenderPassEncoder) {
	procRenderPassEncoderEnd.Call(uintptr(unsafe.Pointer(r)))
}

func RenderPassEncoderSetLabel(r RenderPassEncoder, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procRenderPassEncoderSetLabel.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(&label_sv)))
}

func RenderPassEncoderRelease(r RenderPassEncoder) {
	if x := r; x != nil {
		releaseRenderPassEncoder(unsafe.Pointer(x))
	}
}

func RenderPipelineGetBindGroupLayout(r RenderPipeline, groupIndex uint32) BindGroupLayout {
	r1, _, _ := procRenderPipelineGetBindGroupLayout.Call(uintptr(unsafe.Pointer(r)), uintptr(groupIndex))
	return BindGroupLayout(unsafe.Pointer(r1))
}

func RenderPipelineSetLabel(r RenderPipeline, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procRenderPipelineSetLabel.Call(uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(&label_sv)))
}

func RenderPipelineRelease(r RenderPipeline) {
	if x := r; x != nil {
		releaseRenderPipeline(unsafe.Pointer(x))
	}
}

func SamplerSetLabel(s Sampler, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procSamplerSetLabel.Call(uintptr(unsafe.Pointer(s)), uintptr(unsafe.Pointer(&label_sv)))
}

func SamplerRelease(s Sampler) {
	if x := s; x != nil {
		releaseSampler(unsafe.Pointer(x))
	}
}

func ShaderModuleGetCompilationInfo(s ShaderModule) (CompilationInfo, CompilationInfoRequestStatus) {
	type _res struct {
		r0 CompilationInfo
		r1 CompilationInfoRequestStatus
	}
	_ch := make(chan _res, 1)
	callback := CompilationInfoFn(func(r0 CompilationInfo, r1 CompilationInfoRequestStatus) {
		_ch <- _res{r0, r1}
	})
	_cbThunk := &cbThunk{fn: callback}
	_cbInfo := CompilationInfoCallbackInfo{
		Mode:      CallbackModeAllowProcessEvents,
		Callback:  cbCompilationInfo,
		Userdata1: unsafe.Pointer(_cbThunk),
	}
	r1, _, _ := procShaderModuleGetCompilationInfo.Call(uintptr(unsafe.Pointer(s)), uintptr(unsafe.Pointer(&_cbInfo)))
	_ = r1
	_out := waitRecv(_ch)
	runtime.KeepAlive(_cbThunk)
	return _out.r0, _out.r1
}

func ShaderModuleSetLabel(s ShaderModule, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procShaderModuleSetLabel.Call(uintptr(unsafe.Pointer(s)), uintptr(unsafe.Pointer(&label_sv)))
}

func ShaderModuleRelease(s ShaderModule) {
	if x := s; x != nil {
		releaseShaderModule(unsafe.Pointer(x))
	}
}

// Configures parameters for rendering to `surface`.
// Produces a @ref DeviceError for all content-timeline errors defined by the WebGPU specification.
//
// See @ref Surface-Configuration for more details.

func SurfaceConfigure(s Surface, config *SurfaceConfiguration) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if config != nil {
		pinner.Pin(config)
		if config.NextInChain != nil {
			pinner.Pin(config.NextInChain)
		}
		if config.ViewFormats != nil {
			pinner.Pin(config.ViewFormats)
		}
	}
	procSurfaceConfigure.Call(uintptr(unsafe.Pointer(s)), uintptr(unsafe.Pointer(config)))
}

// Provides information on how `adapter` is able to use `surface`.
// See @ref Surface-Capabilities for more details.

func SurfaceGetCapabilities(s Surface, adapter Adapter, capabilities *SurfaceCapabilities) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if capabilities != nil {
		pinner.Pin(capabilities)
		if capabilities.NextInChain != nil {
			pinner.Pin(capabilities.NextInChain)
		}
		if capabilities.Formats != nil {
			pinner.Pin(capabilities.Formats)
		}
		if capabilities.PresentModes != nil {
			pinner.Pin(capabilities.PresentModes)
		}
		if capabilities.AlphaModes != nil {
			pinner.Pin(capabilities.AlphaModes)
		}
	}
	r1, _, _ := procSurfaceGetCapabilities.Call(uintptr(unsafe.Pointer(s)), uintptr(unsafe.Pointer(adapter)), uintptr(unsafe.Pointer(capabilities)))
	return Status(r1)
}

// Returns the @ref WGPUTexture to render to `surface` this frame along with metadata on the frame.
// Returns `NULL` and @ref WGPUSurfaceGetCurrentTextureStatus_Error if the surface is not configured.
//
// See @ref Surface-Presenting for more details.

func SurfaceGetCurrentTexture(s Surface, surfaceTexture *SurfaceTexture) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if surfaceTexture != nil {
		pinner.Pin(surfaceTexture)
		if surfaceTexture.NextInChain != nil {
			pinner.Pin(surfaceTexture.NextInChain)
		}
	}
	procSurfaceGetCurrentTexture.Call(uintptr(unsafe.Pointer(s)), uintptr(unsafe.Pointer(surfaceTexture)))
}

// Shows `surface`'s current texture to the user.
// See @ref Surface-Presenting for more details.

func SurfacePresent(s Surface) Status {
	r1, _, _ := procSurfacePresent.Call(uintptr(unsafe.Pointer(s)))
	return Status(r1)
}

// Removes the configuration for `surface`.
// See @ref Surface-Configuration for more details.

func SurfaceUnconfigure(s Surface) {
	procSurfaceUnconfigure.Call(uintptr(unsafe.Pointer(s)))
}

// Modifies the label used to refer to `surface`.

func SurfaceSetLabel(s Surface, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procSurfaceSetLabel.Call(uintptr(unsafe.Pointer(s)), uintptr(unsafe.Pointer(&label_sv)))
}

func SurfaceRelease(s Surface) {
	if x := s; x != nil {
		releaseSurface(unsafe.Pointer(x))
	}
}

func TextureCreateView(t Texture, descriptor *TextureViewDescriptor) TextureView {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if descriptor != nil {
		pinner.Pin(descriptor)
		if descriptor.NextInChain != nil {
			pinner.Pin(descriptor.NextInChain)
		}
		if len(descriptor.Label) > 0 {
			pinner.Pin(unsafe.StringData(descriptor.Label))
		}
	}
	r1, _, _ := procTextureCreateView.Call(uintptr(unsafe.Pointer(t)), uintptr(unsafe.Pointer(descriptor)))
	return TextureView(unsafe.Pointer(r1))
}

func TextureSetLabel(t Texture, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procTextureSetLabel.Call(uintptr(unsafe.Pointer(t)), uintptr(unsafe.Pointer(&label_sv)))
}

func TextureGetWidth(t Texture) uint32 {
	r1, _, _ := procTextureGetWidth.Call(uintptr(unsafe.Pointer(t)))
	return (uint32)(r1)
}

func TextureGetHeight(t Texture) uint32 {
	r1, _, _ := procTextureGetHeight.Call(uintptr(unsafe.Pointer(t)))
	return (uint32)(r1)
}

func TextureGetDepthOrArrayLayers(t Texture) uint32 {
	r1, _, _ := procTextureGetDepthOrArrayLayers.Call(uintptr(unsafe.Pointer(t)))
	return (uint32)(r1)
}

func TextureGetMipLevelCount(t Texture) uint32 {
	r1, _, _ := procTextureGetMipLevelCount.Call(uintptr(unsafe.Pointer(t)))
	return (uint32)(r1)
}

func TextureGetSampleCount(t Texture) uint32 {
	r1, _, _ := procTextureGetSampleCount.Call(uintptr(unsafe.Pointer(t)))
	return (uint32)(r1)
}

func TextureGetDimension(t Texture) TextureDimension {
	r1, _, _ := procTextureGetDimension.Call(uintptr(unsafe.Pointer(t)))
	return (TextureDimension)(r1)
}

func TextureGetTextureBindingViewDimension(t Texture) TextureViewDimension {
	r1, _, _ := procTextureGetTextureBindingViewDimension.Call(uintptr(unsafe.Pointer(t)))
	return (TextureViewDimension)(r1)
}

func TextureGetFormat(t Texture) TextureFormat {
	r1, _, _ := procTextureGetFormat.Call(uintptr(unsafe.Pointer(t)))
	return (TextureFormat)(r1)
}

func TextureGetUsage(t Texture) TextureUsage {
	r1, _, _ := procTextureGetUsage.Call(uintptr(unsafe.Pointer(t)))
	return (TextureUsage)(r1)
}

func TextureDestroy(t Texture) {
	procTextureDestroy.Call(uintptr(unsafe.Pointer(t)))
}

func TextureRelease(t Texture) {
	if x := t; x != nil {
		releaseTexture(unsafe.Pointer(x))
	}
}

func TextureViewSetLabel(t TextureView, label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	label_sv := syscallStringView(label, &pinner)
	procTextureViewSetLabel.Call(uintptr(unsafe.Pointer(t)), uintptr(unsafe.Pointer(&label_sv)))
}

func TextureViewRelease(t TextureView) {
	if x := t; x != nil {
		releaseTextureView(unsafe.Pointer(x))
	}
}

// slicePtr returns a pointer to the first element of s, or nil if empty.
func slicePtr[T any](s []T) unsafe.Pointer {
	if len(s) == 0 {
		return nil
	}
	return unsafe.Pointer(&s[0])
}
