// Code generated by gen; DO NOT EDIT.

package webgpu

// NewBindGroupEntry returns a BindGroupEntry with default values.
func NewBindGroupEntry() BindGroupEntry {
	return BindGroupEntry{
		Size: WholeSize,
	}
}

// NewBindGroupLayoutEntry returns a BindGroupLayoutEntry with default values.
func NewBindGroupLayoutEntry() BindGroupLayoutEntry {
	return BindGroupLayoutEntry{
		Visibility:     ShaderStageNone,
		Buffer:         BufferBindingLayout{},
		Sampler:        SamplerBindingLayout{},
		Texture:        TextureBindingLayout{},
		StorageTexture: StorageTextureBindingLayout{},
	}
}

// NewBufferBindingLayout returns a BufferBindingLayout with default values.
func NewBufferBindingLayout() BufferBindingLayout {
	return BufferBindingLayout{
		HasDynamicOffset: 0,
		MinBindingSize:   0,
	}
}

// NewBufferDescriptor returns a BufferDescriptor with default values.
func NewBufferDescriptor() BufferDescriptor {
	return BufferDescriptor{
		Usage:            BufferUsageNone,
		MappedAtCreation: 0,
	}
}

// NewColorTargetState returns a ColorTargetState with default values.
func NewColorTargetState() ColorTargetState {
	return ColorTargetState{
		WriteMask: ColorWriteMaskAll,
	}
}

// NewCompatibilityModeLimits returns a CompatibilityModeLimits with default values.
func NewCompatibilityModeLimits() CompatibilityModeLimits {
	return CompatibilityModeLimits{
		SType:                             STypeCompatibilityModeLimits,
		MaxStorageBuffersInVertexStage:    LimitU32Undefined,
		MaxStorageTexturesInVertexStage:   LimitU32Undefined,
		MaxStorageBuffersInFragmentStage:  LimitU32Undefined,
		MaxStorageTexturesInFragmentStage: LimitU32Undefined,
	}
}

// NewDepthStencilState returns a DepthStencilState with default values.
func NewDepthStencilState() DepthStencilState {
	return DepthStencilState{
		StencilReadMask:     0xFFFFFFFF,
		StencilWriteMask:    0xFFFFFFFF,
		DepthBias:           0,
		DepthBiasSlopeScale: 0,
		DepthBiasClamp:      0,
	}
}

// NewExtent3D returns a Extent3D with default values.
func NewExtent3D() Extent3D {
	return Extent3D{
		Height:             1,
		DepthOrArrayLayers: 1,
	}
}

// NewExternalTextureBindingEntry returns a ExternalTextureBindingEntry with default values.
func NewExternalTextureBindingEntry() ExternalTextureBindingEntry {
	return ExternalTextureBindingEntry{
		SType: STypeExternalTextureBindingEntry,
	}
}

// NewExternalTextureBindingLayout returns a ExternalTextureBindingLayout with default values.
func NewExternalTextureBindingLayout() ExternalTextureBindingLayout {
	return ExternalTextureBindingLayout{
		SType: STypeExternalTextureBindingLayout,
	}
}

// NewLimits returns a Limits with default values.
func NewLimits() Limits {
	return Limits{
		MaxTextureDimension1D:                     LimitU32Undefined,
		MaxTextureDimension2D:                     LimitU32Undefined,
		MaxTextureDimension3D:                     LimitU32Undefined,
		MaxTextureArrayLayers:                     LimitU32Undefined,
		MaxBindGroups:                             LimitU32Undefined,
		MaxBindGroupsPlusVertexBuffers:            LimitU32Undefined,
		MaxBindingsPerBindGroup:                   LimitU32Undefined,
		MaxDynamicUniformBuffersPerPipelineLayout: LimitU32Undefined,
		MaxDynamicStorageBuffersPerPipelineLayout: LimitU32Undefined,
		MaxSampledTexturesPerShaderStage:          LimitU32Undefined,
		MaxSamplersPerShaderStage:                 LimitU32Undefined,
		MaxStorageBuffersPerShaderStage:           LimitU32Undefined,
		MaxStorageTexturesPerShaderStage:          LimitU32Undefined,
		MaxUniformBuffersPerShaderStage:           LimitU32Undefined,
		MaxUniformBufferBindingSize:               LimitU64Undefined,
		MaxStorageBufferBindingSize:               LimitU64Undefined,
		MinUniformBufferOffsetAlignment:           LimitU32Undefined,
		MinStorageBufferOffsetAlignment:           LimitU32Undefined,
		MaxVertexBuffers:                          LimitU32Undefined,
		MaxBufferSize:                             LimitU64Undefined,
		MaxVertexAttributes:                       LimitU32Undefined,
		MaxVertexBufferArrayStride:                LimitU32Undefined,
		MaxInterStageShaderVariables:              LimitU32Undefined,
		MaxColorAttachments:                       LimitU32Undefined,
		MaxColorAttachmentBytesPerSample:          LimitU32Undefined,
		MaxComputeWorkgroupStorageSize:            LimitU32Undefined,
		MaxComputeInvocationsPerWorkgroup:         LimitU32Undefined,
		MaxComputeWorkgroupSizeX:                  LimitU32Undefined,
		MaxComputeWorkgroupSizeY:                  LimitU32Undefined,
		MaxComputeWorkgroupSizeZ:                  LimitU32Undefined,
		MaxComputeWorkgroupsPerDimension:          LimitU32Undefined,
		MaxImmediateSize:                          LimitU32Undefined,
	}
}

// NewMultisampleState returns a MultisampleState with default values.
func NewMultisampleState() MultisampleState {
	return MultisampleState{
		Count:                  1,
		Mask:                   0xFFFFFFFF,
		AlphaToCoverageEnabled: 0,
	}
}

// NewOrigin3D returns a Origin3D with default values.
func NewOrigin3D() Origin3D {
	return Origin3D{
		X: 0,
		Y: 0,
		Z: 0,
	}
}

// NewPassTimestampWrites returns a PassTimestampWrites with default values.
func NewPassTimestampWrites() PassTimestampWrites {
	return PassTimestampWrites{
		BeginningOfPassWriteIndex: QuerySetIndexUndefined,
		EndOfPassWriteIndex:       QuerySetIndexUndefined,
	}
}

// NewPipelineLayoutDescriptor returns a PipelineLayoutDescriptor with default values.
func NewPipelineLayoutDescriptor() PipelineLayoutDescriptor {
	return PipelineLayoutDescriptor{
		ImmediateSize: 0,
	}
}

// NewPrimitiveState returns a PrimitiveState with default values.
func NewPrimitiveState() PrimitiveState {
	return PrimitiveState{
		UnclippedDepth: 0,
	}
}

// NewRenderBundleEncoderDescriptor returns a RenderBundleEncoderDescriptor with default values.
func NewRenderBundleEncoderDescriptor() RenderBundleEncoderDescriptor {
	return RenderBundleEncoderDescriptor{
		SampleCount:     1,
		DepthReadOnly:   0,
		StencilReadOnly: 0,
	}
}

// NewRenderPassColorAttachment returns a RenderPassColorAttachment with default values.
func NewRenderPassColorAttachment() RenderPassColorAttachment {
	return RenderPassColorAttachment{
		DepthSlice: DepthSliceUndefined,
	}
}

// NewRenderPassDepthStencilAttachment returns a RenderPassDepthStencilAttachment with default values.
func NewRenderPassDepthStencilAttachment() RenderPassDepthStencilAttachment {
	return RenderPassDepthStencilAttachment{
		DepthClearValue: &DepthClearValueUndefined,
		DepthReadOnly:   0,
		StencilReadOnly: 0,
	}
}

// NewRenderPassMaxDrawCount returns a RenderPassMaxDrawCount with default values.
func NewRenderPassMaxDrawCount() RenderPassMaxDrawCount {
	return RenderPassMaxDrawCount{
		SType:        STypeRenderPassMaxDrawCount,
		MaxDrawCount: 50000000,
	}
}

// NewRequestAdapterOptions returns a RequestAdapterOptions with default values.
func NewRequestAdapterOptions() RequestAdapterOptions {
	return RequestAdapterOptions{
		ForceFallbackAdapter: 0,
	}
}

// NewRequestAdapterWebXROptions returns a RequestAdapterWebXROptions with default values.
func NewRequestAdapterWebXROptions() RequestAdapterWebXROptions {
	return RequestAdapterWebXROptions{
		SType:        STypeRequestAdapterWebXROptions,
		XrCompatible: 0,
	}
}

// NewSamplerDescriptor returns a SamplerDescriptor with default values.
func NewSamplerDescriptor() SamplerDescriptor {
	return SamplerDescriptor{
		LodMinClamp:   0,
		LodMaxClamp:   32,
		MaxAnisotropy: 1,
	}
}

// NewShaderSourceSPIRV returns a ShaderSourceSPIRV with default values.
func NewShaderSourceSPIRV() ShaderSourceSPIRV {
	return ShaderSourceSPIRV{
		SType:    STypeShaderSourceSPIRV,
		CodeSize: 0,
	}
}

// NewShaderSourceWGSL returns a ShaderSourceWGSL with default values.
func NewShaderSourceWGSL() ShaderSourceWGSL {
	return ShaderSourceWGSL{
		SType: STypeShaderSourceWGSL,
	}
}

// NewSurfaceColorManagement returns a SurfaceColorManagement with default values.
func NewSurfaceColorManagement() SurfaceColorManagement {
	return SurfaceColorManagement{
		SType: STypeSurfaceColorManagement,
	}
}

// NewSurfaceConfiguration returns a SurfaceConfiguration with default values.
func NewSurfaceConfiguration() SurfaceConfiguration {
	return SurfaceConfiguration{
		Usage:     TextureUsageRenderAttachment,
		AlphaMode: CompositeAlphaModeAuto,
	}
}

// NewSurfaceSourceAndroidNativeWindow returns a SurfaceSourceAndroidNativeWindow with default values.
func NewSurfaceSourceAndroidNativeWindow() SurfaceSourceAndroidNativeWindow {
	return SurfaceSourceAndroidNativeWindow{
		SType: STypeSurfaceSourceAndroidNativeWindow,
	}
}

// NewSurfaceSourceMetalLayer returns a SurfaceSourceMetalLayer with default values.
func NewSurfaceSourceMetalLayer() SurfaceSourceMetalLayer {
	return SurfaceSourceMetalLayer{
		SType: STypeSurfaceSourceMetalLayer,
	}
}

// NewSurfaceSourceWaylandSurface returns a SurfaceSourceWaylandSurface with default values.
func NewSurfaceSourceWaylandSurface() SurfaceSourceWaylandSurface {
	return SurfaceSourceWaylandSurface{
		SType: STypeSurfaceSourceWaylandSurface,
	}
}

// NewSurfaceSourceWindowsHWND returns a SurfaceSourceWindowsHWND with default values.
func NewSurfaceSourceWindowsHWND() SurfaceSourceWindowsHWND {
	return SurfaceSourceWindowsHWND{
		SType: STypeSurfaceSourceWindowsHWND,
	}
}

// NewSurfaceSourceXCBWindow returns a SurfaceSourceXCBWindow with default values.
func NewSurfaceSourceXCBWindow() SurfaceSourceXCBWindow {
	return SurfaceSourceXCBWindow{
		SType: STypeSurfaceSourceXCBWindow,
	}
}

// NewSurfaceSourceXlibWindow returns a SurfaceSourceXlibWindow with default values.
func NewSurfaceSourceXlibWindow() SurfaceSourceXlibWindow {
	return SurfaceSourceXlibWindow{
		SType: STypeSurfaceSourceXlibWindow,
	}
}

// NewTexelCopyBufferLayout returns a TexelCopyBufferLayout with default values.
func NewTexelCopyBufferLayout() TexelCopyBufferLayout {
	return TexelCopyBufferLayout{
		Offset:       0,
		BytesPerRow:  CopyStrideUndefined,
		RowsPerImage: CopyStrideUndefined,
	}
}

// NewTexelCopyTextureInfo returns a TexelCopyTextureInfo with default values.
func NewTexelCopyTextureInfo() TexelCopyTextureInfo {
	return TexelCopyTextureInfo{
		MipLevel: 0,
	}
}

// NewTextureBindingLayout returns a TextureBindingLayout with default values.
func NewTextureBindingLayout() TextureBindingLayout {
	return TextureBindingLayout{
		Multisampled: 0,
	}
}

// NewTextureBindingViewDimension returns a TextureBindingViewDimension with default values.
func NewTextureBindingViewDimension() TextureBindingViewDimension {
	return TextureBindingViewDimension{
		SType: STypeTextureBindingViewDimension,
	}
}

// NewTextureComponentSwizzleDescriptor returns a TextureComponentSwizzleDescriptor with default values.
func NewTextureComponentSwizzleDescriptor() TextureComponentSwizzleDescriptor {
	return TextureComponentSwizzleDescriptor{
		SType: STypeTextureComponentSwizzleDescriptor,
	}
}

// NewTextureDescriptor returns a TextureDescriptor with default values.
func NewTextureDescriptor() TextureDescriptor {
	return TextureDescriptor{
		Usage:         TextureUsageNone,
		MipLevelCount: 1,
		SampleCount:   1,
	}
}

// NewTextureViewDescriptor returns a TextureViewDescriptor with default values.
func NewTextureViewDescriptor() TextureViewDescriptor {
	return TextureViewDescriptor{
		BaseMipLevel:    0,
		MipLevelCount:   MipLevelCountUndefined,
		BaseArrayLayer:  0,
		ArrayLayerCount: ArrayLayerCountUndefined,
		Usage:           TextureUsageNone,
	}
}
