// Code generated by gen; DO NOT EDIT.

package webgpu

import (
	"math"
	"structs"
	"unsafe"
)

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const (
	// Indicates no array layer count is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	ArrayLayerCountUndefined = 0xFFFFFFFF
	// Indicates no copy stride is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	CopyStrideUndefined = 0xFFFFFFFF
	// Indicates no depth slice is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	DepthSliceUndefined = 0xFFFFFFFF
	// For `uint32_t` limits, indicates no limit value is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	LimitU32Undefined = 0xFFFFFFFF
	// For `uint64_t` limits, indicates no limit value is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	LimitU64Undefined = 0xFFFFFFFFFFFFFFFF
	// Indicates no mip level count is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	MipLevelCountUndefined = 0xFFFFFFFF
	// Indicates no query set index is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	QuerySetIndexUndefined = 0xFFFFFFFF
	// Sentinel value used in @ref WGPUStringView to indicate that the pointer
	// is to a null-terminated string, rather than an explicitly-sized string.
	Strlen = 0xFFFFFFFFFFFFFFFF
	// Indicates a size extending to the end of the buffer. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	WholeMapSize = 0xFFFFFFFFFFFFFFFF
	// Indicates a size extending to the end of the buffer. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	WholeSize = 0xFFFFFFFFFFFFFFFF
)

// NaN-based constants (not valid in const blocks).
var (
	// Indicates no depth clear value is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	DepthClearValueUndefined float32 = float32(math.NaN())
)

// ---------------------------------------------------------------------------
// Enum types
// ---------------------------------------------------------------------------

// AdapterType is a WebGPU enum.
type AdapterType uint32

const (
	AdapterTypeDiscreteGPU   AdapterType = 1
	AdapterTypeIntegratedGPU AdapterType = 2
	AdapterTypeCPU           AdapterType = 3
	AdapterTypeUnknown       AdapterType = 4
)

// AddressMode is a WebGPU enum.
type AddressMode uint32

const (
	AddressModeUndefined    AddressMode = 0
	AddressModeClampToEdge  AddressMode = 1
	AddressModeRepeat       AddressMode = 2
	AddressModeMirrorRepeat AddressMode = 3
)

// BackendType is a WebGPU enum.
type BackendType uint32

const (
	BackendTypeUndefined BackendType = 0
	BackendTypeNull      BackendType = 1
	BackendTypeWebGPU    BackendType = 2
	BackendTypeD3D11     BackendType = 3
	BackendTypeD3D12     BackendType = 4
	BackendTypeMetal     BackendType = 5
	BackendTypeVulkan    BackendType = 6
	BackendTypeOpenGL    BackendType = 7
	BackendTypeOpenGLES  BackendType = 8
)

// BlendFactor is a WebGPU enum.
type BlendFactor uint32

const (
	BlendFactorUndefined         BlendFactor = 0
	BlendFactorZero              BlendFactor = 1
	BlendFactorOne               BlendFactor = 2
	BlendFactorSrc               BlendFactor = 3
	BlendFactorOneMinusSrc       BlendFactor = 4
	BlendFactorSrcAlpha          BlendFactor = 5
	BlendFactorOneMinusSrcAlpha  BlendFactor = 6
	BlendFactorDst               BlendFactor = 7
	BlendFactorOneMinusDst       BlendFactor = 8
	BlendFactorDstAlpha          BlendFactor = 9
	BlendFactorOneMinusDstAlpha  BlendFactor = 10
	BlendFactorSrcAlphaSaturated BlendFactor = 11
	BlendFactorConstant          BlendFactor = 12
	BlendFactorOneMinusConstant  BlendFactor = 13
	BlendFactorSrc1              BlendFactor = 14
	BlendFactorOneMinusSrc1      BlendFactor = 15
	BlendFactorSrc1Alpha         BlendFactor = 16
	BlendFactorOneMinusSrc1Alpha BlendFactor = 17
)

// BlendOperation is a WebGPU enum.
type BlendOperation uint32

const (
	BlendOperationUndefined       BlendOperation = 0
	BlendOperationAdd             BlendOperation = 1
	BlendOperationSubtract        BlendOperation = 2
	BlendOperationReverseSubtract BlendOperation = 3
	BlendOperationMin             BlendOperation = 4
	BlendOperationMax             BlendOperation = 5
)

// BufferBindingType is a WebGPU enum.
type BufferBindingType uint32

const (
	BufferBindingTypeBindingNotUsed  BufferBindingType = 0
	BufferBindingTypeUndefined       BufferBindingType = 1
	BufferBindingTypeUniform         BufferBindingType = 2
	BufferBindingTypeStorage         BufferBindingType = 3
	BufferBindingTypeReadOnlyStorage BufferBindingType = 4
)

// BufferMapState is a WebGPU enum.
type BufferMapState uint32

const (
	BufferMapStateUnmapped BufferMapState = 1
	BufferMapStatePending  BufferMapState = 2
	BufferMapStateMapped   BufferMapState = 3
)

// CallbackMode is a WebGPU enum.
type CallbackMode uint32

const (
	CallbackModeWaitAnyOnly        CallbackMode = 1
	CallbackModeAllowProcessEvents CallbackMode = 2
	CallbackModeAllowSpontaneous   CallbackMode = 3
)

// CompareFunction is a WebGPU enum.
type CompareFunction uint32

const (
	CompareFunctionUndefined    CompareFunction = 0
	CompareFunctionNever        CompareFunction = 1
	CompareFunctionLess         CompareFunction = 2
	CompareFunctionEqual        CompareFunction = 3
	CompareFunctionLessEqual    CompareFunction = 4
	CompareFunctionGreater      CompareFunction = 5
	CompareFunctionNotEqual     CompareFunction = 6
	CompareFunctionGreaterEqual CompareFunction = 7
	CompareFunctionAlways       CompareFunction = 8
)

// CompilationInfoRequestStatus is a WebGPU enum.
type CompilationInfoRequestStatus uint32

const (
	CompilationInfoRequestStatusSuccess           CompilationInfoRequestStatus = 1
	CompilationInfoRequestStatusCallbackCancelled CompilationInfoRequestStatus = 2
)

// CompilationMessageType is a WebGPU enum.
type CompilationMessageType uint32

const (
	CompilationMessageTypeError   CompilationMessageType = 1
	CompilationMessageTypeWarning CompilationMessageType = 2
	CompilationMessageTypeInfo    CompilationMessageType = 3
)

// ComponentSwizzle is a WebGPU enum.
type ComponentSwizzle uint32

const (
	ComponentSwizzleUndefined ComponentSwizzle = 0
	ComponentSwizzleZero      ComponentSwizzle = 1
	ComponentSwizzleOne       ComponentSwizzle = 2
	ComponentSwizzleR         ComponentSwizzle = 3
	ComponentSwizzleG         ComponentSwizzle = 4
	ComponentSwizzleB         ComponentSwizzle = 5
	ComponentSwizzleA         ComponentSwizzle = 6
)

// CompositeAlphaMode is a WebGPU enum.
type CompositeAlphaMode uint32

const (
	CompositeAlphaModeAuto            CompositeAlphaMode = 0
	CompositeAlphaModeOpaque          CompositeAlphaMode = 1
	CompositeAlphaModePremultiplied   CompositeAlphaMode = 2
	CompositeAlphaModeUnpremultiplied CompositeAlphaMode = 3
	CompositeAlphaModeInherit         CompositeAlphaMode = 4
)

// CreatePipelineAsyncStatus is a WebGPU enum.
type CreatePipelineAsyncStatus uint32

const (
	CreatePipelineAsyncStatusSuccess           CreatePipelineAsyncStatus = 1
	CreatePipelineAsyncStatusCallbackCancelled CreatePipelineAsyncStatus = 2
	CreatePipelineAsyncStatusValidationError   CreatePipelineAsyncStatus = 3
	CreatePipelineAsyncStatusInternalError     CreatePipelineAsyncStatus = 4
)

// CullMode is a WebGPU enum.
type CullMode uint32

const (
	CullModeUndefined CullMode = 0
	CullModeNone      CullMode = 1
	CullModeFront     CullMode = 2
	CullModeBack      CullMode = 3
)

// DeviceLostReason is a WebGPU enum.
type DeviceLostReason uint32

const (
	DeviceLostReasonUnknown           DeviceLostReason = 1
	DeviceLostReasonDestroyed         DeviceLostReason = 2
	DeviceLostReasonCallbackCancelled DeviceLostReason = 3
	DeviceLostReasonFailedCreation    DeviceLostReason = 4
)

// ErrorFilter is a WebGPU enum.
type ErrorFilter uint32

const (
	ErrorFilterValidation  ErrorFilter = 1
	ErrorFilterOutOfMemory ErrorFilter = 2
	ErrorFilterInternal    ErrorFilter = 3
)

// ErrorType is a WebGPU enum.
type ErrorType uint32

const (
	ErrorTypeNoError     ErrorType = 1
	ErrorTypeValidation  ErrorType = 2
	ErrorTypeOutOfMemory ErrorType = 3
	ErrorTypeInternal    ErrorType = 4
	ErrorTypeUnknown     ErrorType = 5
)

// FeatureLevel is a WebGPU enum.
type FeatureLevel uint32

const (
	FeatureLevelUndefined     FeatureLevel = 0
	FeatureLevelCompatibility FeatureLevel = 1
	FeatureLevelCore          FeatureLevel = 2
)

// FeatureName is a WebGPU enum.
type FeatureName uint32

const (
	FeatureNameCoreFeaturesAndLimits          FeatureName = 1
	FeatureNameDepthClipControl               FeatureName = 2
	FeatureNameDepth32FloatStencil8           FeatureName = 3
	FeatureNameTextureCompressionBC           FeatureName = 4
	FeatureNameTextureCompressionBCSliced3D   FeatureName = 5
	FeatureNameTextureCompressionETC2         FeatureName = 6
	FeatureNameTextureCompressionASTC         FeatureName = 7
	FeatureNameTextureCompressionASTCSliced3D FeatureName = 8
	FeatureNameTimestampQuery                 FeatureName = 9
	FeatureNameIndirectFirstInstance          FeatureName = 10
	FeatureNameShaderF16                      FeatureName = 11
	FeatureNameRG11B10UfloatRenderable        FeatureName = 12
	FeatureNameBGRA8UnormStorage              FeatureName = 13
	FeatureNameFloat32Filterable              FeatureName = 14
	FeatureNameFloat32Blendable               FeatureName = 15
	FeatureNameClipDistances                  FeatureName = 16
	FeatureNameDualSourceBlending             FeatureName = 17
	FeatureNameSubgroups                      FeatureName = 18
	FeatureNameTextureFormatsTier1            FeatureName = 19
	FeatureNameTextureFormatsTier2            FeatureName = 20
	FeatureNamePrimitiveIndex                 FeatureName = 21
	FeatureNameTextureComponentSwizzle        FeatureName = 22
	FeatureNameSubgroupSizeControl            FeatureName = 23
	FeatureNameTextureCompressionUnaligned    FeatureName = 24
)

// FilterMode is a WebGPU enum.
type FilterMode uint32

const (
	FilterModeUndefined FilterMode = 0
	FilterModeNearest   FilterMode = 1
	FilterModeLinear    FilterMode = 2
)

// FrontFace is a WebGPU enum.
type FrontFace uint32

const (
	FrontFaceUndefined FrontFace = 0
	FrontFaceCCW       FrontFace = 1
	FrontFaceCW        FrontFace = 2
)

// IndexFormat is a WebGPU enum.
type IndexFormat uint32

const (
	IndexFormatUndefined IndexFormat = 0
	IndexFormatUint16    IndexFormat = 1
	IndexFormatUint32    IndexFormat = 2
)

// InstanceFeatureName is a WebGPU enum.
type InstanceFeatureName uint32

const (
	InstanceFeatureNameTimedWaitAny              InstanceFeatureName = 1
	InstanceFeatureNameShaderSourceSPIRV         InstanceFeatureName = 2
	InstanceFeatureNameMultipleDevicesPerAdapter InstanceFeatureName = 3
)

// LoadOp is a WebGPU enum.
type LoadOp uint32

const (
	LoadOpUndefined LoadOp = 0
	LoadOpLoad      LoadOp = 1
	LoadOpClear     LoadOp = 2
)

// MapAsyncStatus is a WebGPU enum.
type MapAsyncStatus uint32

const (
	MapAsyncStatusSuccess           MapAsyncStatus = 1
	MapAsyncStatusCallbackCancelled MapAsyncStatus = 2
	MapAsyncStatusError             MapAsyncStatus = 3
	MapAsyncStatusAborted           MapAsyncStatus = 4
)

// MipmapFilterMode is a WebGPU enum.
type MipmapFilterMode uint32

const (
	MipmapFilterModeUndefined MipmapFilterMode = 0
	MipmapFilterModeNearest   MipmapFilterMode = 1
	MipmapFilterModeLinear    MipmapFilterMode = 2
)

// OptionalBool is a WebGPU enum.
type OptionalBool uint32

const (
	OptionalBoolFalse     OptionalBool = 0
	OptionalBoolTrue      OptionalBool = 1
	OptionalBoolUndefined OptionalBool = 2
)

// PopErrorScopeStatus is a WebGPU enum.
type PopErrorScopeStatus uint32

const (
	PopErrorScopeStatusSuccess           PopErrorScopeStatus = 1
	PopErrorScopeStatusCallbackCancelled PopErrorScopeStatus = 2
	PopErrorScopeStatusError             PopErrorScopeStatus = 3
)

// PowerPreference is a WebGPU enum.
type PowerPreference uint32

const (
	PowerPreferenceUndefined       PowerPreference = 0
	PowerPreferenceLowPower        PowerPreference = 1
	PowerPreferenceHighPerformance PowerPreference = 2
)

// PredefinedColorSpace is a WebGPU enum.
type PredefinedColorSpace uint32

const (
	PredefinedColorSpaceSRGB      PredefinedColorSpace = 1
	PredefinedColorSpaceDisplayP3 PredefinedColorSpace = 2
)

// PresentMode is a WebGPU enum.
type PresentMode uint32

const (
	PresentModeUndefined   PresentMode = 0
	PresentModeFifo        PresentMode = 1
	PresentModeFifoRelaxed PresentMode = 2
	PresentModeImmediate   PresentMode = 3
	PresentModeMailbox     PresentMode = 4
)

// PrimitiveTopology is a WebGPU enum.
type PrimitiveTopology uint32

const (
	PrimitiveTopologyUndefined     PrimitiveTopology = 0
	PrimitiveTopologyPointList     PrimitiveTopology = 1
	PrimitiveTopologyLineList      PrimitiveTopology = 2
	PrimitiveTopologyLineStrip     PrimitiveTopology = 3
	PrimitiveTopologyTriangleList  PrimitiveTopology = 4
	PrimitiveTopologyTriangleStrip PrimitiveTopology = 5
)

// QueryType is a WebGPU enum.
type QueryType uint32

const (
	QueryTypeOcclusion QueryType = 1
	QueryTypeTimestamp QueryType = 2
)

// QueueWorkDoneStatus is a WebGPU enum.
type QueueWorkDoneStatus uint32

const (
	QueueWorkDoneStatusSuccess           QueueWorkDoneStatus = 1
	QueueWorkDoneStatusCallbackCancelled QueueWorkDoneStatus = 2
	QueueWorkDoneStatusError             QueueWorkDoneStatus = 3
)

// RequestAdapterStatus is a WebGPU enum.
type RequestAdapterStatus uint32

const (
	RequestAdapterStatusSuccess           RequestAdapterStatus = 1
	RequestAdapterStatusCallbackCancelled RequestAdapterStatus = 2
	RequestAdapterStatusUnavailable       RequestAdapterStatus = 3
	RequestAdapterStatusError             RequestAdapterStatus = 4
)

// RequestDeviceStatus is a WebGPU enum.
type RequestDeviceStatus uint32

const (
	RequestDeviceStatusSuccess           RequestDeviceStatus = 1
	RequestDeviceStatusCallbackCancelled RequestDeviceStatus = 2
	RequestDeviceStatusError             RequestDeviceStatus = 3
)

// SType is a WebGPU enum.
type SType uint32

const (
	STypeShaderSourceSPIRV                 SType = 1
	STypeShaderSourceWGSL                  SType = 2
	STypeRenderPassMaxDrawCount            SType = 3
	STypeSurfaceSourceMetalLayer           SType = 4
	STypeSurfaceSourceWindowsHWND          SType = 5
	STypeSurfaceSourceXlibWindow           SType = 6
	STypeSurfaceSourceWaylandSurface       SType = 7
	STypeSurfaceSourceAndroidNativeWindow  SType = 8
	STypeSurfaceSourceXCBWindow            SType = 9
	STypeSurfaceColorManagement            SType = 10
	STypeRequestAdapterWebXROptions        SType = 11
	STypeTextureComponentSwizzleDescriptor SType = 12
	STypeExternalTextureBindingLayout      SType = 13
	STypeExternalTextureBindingEntry       SType = 14
	STypeCompatibilityModeLimits           SType = 15
	STypeTextureBindingViewDimension       SType = 16
)

// SamplerBindingType is a WebGPU enum.
type SamplerBindingType uint32

const (
	SamplerBindingTypeBindingNotUsed SamplerBindingType = 0
	SamplerBindingTypeUndefined      SamplerBindingType = 1
	SamplerBindingTypeFiltering      SamplerBindingType = 2
	SamplerBindingTypeNonFiltering   SamplerBindingType = 3
	SamplerBindingTypeComparison     SamplerBindingType = 4
)

// Status is a WebGPU enum.
type Status uint32

const (
	StatusSuccess Status = 1
	StatusError   Status = 2
)

// StencilOperation is a WebGPU enum.
type StencilOperation uint32

const (
	StencilOperationUndefined      StencilOperation = 0
	StencilOperationKeep           StencilOperation = 1
	StencilOperationZero           StencilOperation = 2
	StencilOperationReplace        StencilOperation = 3
	StencilOperationInvert         StencilOperation = 4
	StencilOperationIncrementClamp StencilOperation = 5
	StencilOperationDecrementClamp StencilOperation = 6
	StencilOperationIncrementWrap  StencilOperation = 7
	StencilOperationDecrementWrap  StencilOperation = 8
)

// StorageTextureAccess is a WebGPU enum.
type StorageTextureAccess uint32

const (
	StorageTextureAccessBindingNotUsed StorageTextureAccess = 0
	StorageTextureAccessUndefined      StorageTextureAccess = 1
	StorageTextureAccessWriteOnly      StorageTextureAccess = 2
	StorageTextureAccessReadOnly       StorageTextureAccess = 3
	StorageTextureAccessReadWrite      StorageTextureAccess = 4
)

// StoreOp is a WebGPU enum.
type StoreOp uint32

const (
	StoreOpUndefined StoreOp = 0
	StoreOpStore     StoreOp = 1
	StoreOpDiscard   StoreOp = 2
)

// SurfaceGetCurrentTextureStatus is a WebGPU enum.
type SurfaceGetCurrentTextureStatus uint32

const (
	SurfaceGetCurrentTextureStatusSuccessOptimal    SurfaceGetCurrentTextureStatus = 1
	SurfaceGetCurrentTextureStatusSuccessSuboptimal SurfaceGetCurrentTextureStatus = 2
	SurfaceGetCurrentTextureStatusTimeout           SurfaceGetCurrentTextureStatus = 3
	SurfaceGetCurrentTextureStatusOutdated          SurfaceGetCurrentTextureStatus = 4
	SurfaceGetCurrentTextureStatusLost              SurfaceGetCurrentTextureStatus = 5
	SurfaceGetCurrentTextureStatusError             SurfaceGetCurrentTextureStatus = 6
)

// TextureAspect is a WebGPU enum.
type TextureAspect uint32

const (
	TextureAspectUndefined   TextureAspect = 0
	TextureAspectAll         TextureAspect = 1
	TextureAspectStencilOnly TextureAspect = 2
	TextureAspectDepthOnly   TextureAspect = 3
)

// TextureDimension is a WebGPU enum.
type TextureDimension uint32

const (
	TextureDimensionUndefined TextureDimension = 0
	TextureDimension1D        TextureDimension = 1
	TextureDimension2D        TextureDimension = 2
	TextureDimension3D        TextureDimension = 3
)

// TextureFormat is a WebGPU enum.
type TextureFormat uint32

const (
	TextureFormatUndefined            TextureFormat = 0
	TextureFormatR8Unorm              TextureFormat = 1
	TextureFormatR8Snorm              TextureFormat = 2
	TextureFormatR8Uint               TextureFormat = 3
	TextureFormatR8Sint               TextureFormat = 4
	TextureFormatR16Unorm             TextureFormat = 5
	TextureFormatR16Snorm             TextureFormat = 6
	TextureFormatR16Uint              TextureFormat = 7
	TextureFormatR16Sint              TextureFormat = 8
	TextureFormatR16Float             TextureFormat = 9
	TextureFormatRG8Unorm             TextureFormat = 10
	TextureFormatRG8Snorm             TextureFormat = 11
	TextureFormatRG8Uint              TextureFormat = 12
	TextureFormatRG8Sint              TextureFormat = 13
	TextureFormatR32Float             TextureFormat = 14
	TextureFormatR32Uint              TextureFormat = 15
	TextureFormatR32Sint              TextureFormat = 16
	TextureFormatRG16Unorm            TextureFormat = 17
	TextureFormatRG16Snorm            TextureFormat = 18
	TextureFormatRG16Uint             TextureFormat = 19
	TextureFormatRG16Sint             TextureFormat = 20
	TextureFormatRG16Float            TextureFormat = 21
	TextureFormatRGBA8Unorm           TextureFormat = 22
	TextureFormatRGBA8UnormSrgb       TextureFormat = 23
	TextureFormatRGBA8Snorm           TextureFormat = 24
	TextureFormatRGBA8Uint            TextureFormat = 25
	TextureFormatRGBA8Sint            TextureFormat = 26
	TextureFormatBGRA8Unorm           TextureFormat = 27
	TextureFormatBGRA8UnormSrgb       TextureFormat = 28
	TextureFormatRGB10A2Uint          TextureFormat = 29
	TextureFormatRGB10A2Unorm         TextureFormat = 30
	TextureFormatRG11B10Ufloat        TextureFormat = 31
	TextureFormatRGB9E5Ufloat         TextureFormat = 32
	TextureFormatRG32Float            TextureFormat = 33
	TextureFormatRG32Uint             TextureFormat = 34
	TextureFormatRG32Sint             TextureFormat = 35
	TextureFormatRGBA16Unorm          TextureFormat = 36
	TextureFormatRGBA16Snorm          TextureFormat = 37
	TextureFormatRGBA16Uint           TextureFormat = 38
	TextureFormatRGBA16Sint           TextureFormat = 39
	TextureFormatRGBA16Float          TextureFormat = 40
	TextureFormatRGBA32Float          TextureFormat = 41
	TextureFormatRGBA32Uint           TextureFormat = 42
	TextureFormatRGBA32Sint           TextureFormat = 43
	TextureFormatStencil8             TextureFormat = 44
	TextureFormatDepth16Unorm         TextureFormat = 45
	TextureFormatDepth24Plus          TextureFormat = 46
	TextureFormatDepth24PlusStencil8  TextureFormat = 47
	TextureFormatDepth32Float         TextureFormat = 48
	TextureFormatDepth32FloatStencil8 TextureFormat = 49
	TextureFormatBC1RGBAUnorm         TextureFormat = 50
	TextureFormatBC1RGBAUnormSrgb     TextureFormat = 51
	TextureFormatBC2RGBAUnorm         TextureFormat = 52
	TextureFormatBC2RGBAUnormSrgb     TextureFormat = 53
	TextureFormatBC3RGBAUnorm         TextureFormat = 54
	TextureFormatBC3RGBAUnormSrgb     TextureFormat = 55
	TextureFormatBC4RUnorm            TextureFormat = 56
	TextureFormatBC4RSnorm            TextureFormat = 57
	TextureFormatBC5RGUnorm           TextureFormat = 58
	TextureFormatBC5RGSnorm           TextureFormat = 59
	TextureFormatBC6HRGBUfloat        TextureFormat = 60
	TextureFormatBC6HRGBFloat         TextureFormat = 61
	TextureFormatBC7RGBAUnorm         TextureFormat = 62
	TextureFormatBC7RGBAUnormSrgb     TextureFormat = 63
	TextureFormatETC2RGB8Unorm        TextureFormat = 64
	TextureFormatETC2RGB8UnormSrgb    TextureFormat = 65
	TextureFormatETC2RGB8A1Unorm      TextureFormat = 66
	TextureFormatETC2RGB8A1UnormSrgb  TextureFormat = 67
	TextureFormatETC2RGBA8Unorm       TextureFormat = 68
	TextureFormatETC2RGBA8UnormSrgb   TextureFormat = 69
	TextureFormatEACR11Unorm          TextureFormat = 70
	TextureFormatEACR11Snorm          TextureFormat = 71
	TextureFormatEACRG11Unorm         TextureFormat = 72
	TextureFormatEACRG11Snorm         TextureFormat = 73
	TextureFormatASTC4x4Unorm         TextureFormat = 74
	TextureFormatASTC4x4UnormSrgb     TextureFormat = 75
	TextureFormatASTC5x4Unorm         TextureFormat = 76
	TextureFormatASTC5x4UnormSrgb     TextureFormat = 77
	TextureFormatASTC5x5Unorm         TextureFormat = 78
	TextureFormatASTC5x5UnormSrgb     TextureFormat = 79
	TextureFormatASTC6x5Unorm         TextureFormat = 80
	TextureFormatASTC6x5UnormSrgb     TextureFormat = 81
	TextureFormatASTC6x6Unorm         TextureFormat = 82
	TextureFormatASTC6x6UnormSrgb     TextureFormat = 83
	TextureFormatASTC8x5Unorm         TextureFormat = 84
	TextureFormatASTC8x5UnormSrgb     TextureFormat = 85
	TextureFormatASTC8x6Unorm         TextureFormat = 86
	TextureFormatASTC8x6UnormSrgb     TextureFormat = 87
	TextureFormatASTC8x8Unorm         TextureFormat = 88
	TextureFormatASTC8x8UnormSrgb     TextureFormat = 89
	TextureFormatASTC10x5Unorm        TextureFormat = 90
	TextureFormatASTC10x5UnormSrgb    TextureFormat = 91
	TextureFormatASTC10x6Unorm        TextureFormat = 92
	TextureFormatASTC10x6UnormSrgb    TextureFormat = 93
	TextureFormatASTC10x8Unorm        TextureFormat = 94
	TextureFormatASTC10x8UnormSrgb    TextureFormat = 95
	TextureFormatASTC10x10Unorm       TextureFormat = 96
	TextureFormatASTC10x10UnormSrgb   TextureFormat = 97
	TextureFormatASTC12x10Unorm       TextureFormat = 98
	TextureFormatASTC12x10UnormSrgb   TextureFormat = 99
	TextureFormatASTC12x12Unorm       TextureFormat = 100
	TextureFormatASTC12x12UnormSrgb   TextureFormat = 101
)

// TextureSampleType is a WebGPU enum.
type TextureSampleType uint32

const (
	TextureSampleTypeBindingNotUsed    TextureSampleType = 0
	TextureSampleTypeUndefined         TextureSampleType = 1
	TextureSampleTypeFloat             TextureSampleType = 2
	TextureSampleTypeUnfilterableFloat TextureSampleType = 3
	TextureSampleTypeDepth             TextureSampleType = 4
	TextureSampleTypeSint              TextureSampleType = 5
	TextureSampleTypeUint              TextureSampleType = 6
)

// TextureViewDimension is a WebGPU enum.
type TextureViewDimension uint32

const (
	TextureViewDimensionUndefined TextureViewDimension = 0
	TextureViewDimension1D        TextureViewDimension = 1
	TextureViewDimension2D        TextureViewDimension = 2
	TextureViewDimension2DArray   TextureViewDimension = 3
	TextureViewDimensionCube      TextureViewDimension = 4
	TextureViewDimensionCubeArray TextureViewDimension = 5
	TextureViewDimension3D        TextureViewDimension = 6
)

// ToneMappingMode is a WebGPU enum.
type ToneMappingMode uint32

const (
	ToneMappingModeStandard ToneMappingMode = 1
	ToneMappingModeExtended ToneMappingMode = 2
)

// VertexFormat is a WebGPU enum.
type VertexFormat uint32

const (
	VertexFormatUint8        VertexFormat = 1
	VertexFormatUint8x2      VertexFormat = 2
	VertexFormatUint8x4      VertexFormat = 3
	VertexFormatSint8        VertexFormat = 4
	VertexFormatSint8x2      VertexFormat = 5
	VertexFormatSint8x4      VertexFormat = 6
	VertexFormatUnorm8       VertexFormat = 7
	VertexFormatUnorm8x2     VertexFormat = 8
	VertexFormatUnorm8x4     VertexFormat = 9
	VertexFormatSnorm8       VertexFormat = 10
	VertexFormatSnorm8x2     VertexFormat = 11
	VertexFormatSnorm8x4     VertexFormat = 12
	VertexFormatUint16       VertexFormat = 13
	VertexFormatUint16x2     VertexFormat = 14
	VertexFormatUint16x4     VertexFormat = 15
	VertexFormatSint16       VertexFormat = 16
	VertexFormatSint16x2     VertexFormat = 17
	VertexFormatSint16x4     VertexFormat = 18
	VertexFormatUnorm16      VertexFormat = 19
	VertexFormatUnorm16x2    VertexFormat = 20
	VertexFormatUnorm16x4    VertexFormat = 21
	VertexFormatSnorm16      VertexFormat = 22
	VertexFormatSnorm16x2    VertexFormat = 23
	VertexFormatSnorm16x4    VertexFormat = 24
	VertexFormatFloat16      VertexFormat = 25
	VertexFormatFloat16x2    VertexFormat = 26
	VertexFormatFloat16x4    VertexFormat = 27
	VertexFormatFloat32      VertexFormat = 28
	VertexFormatFloat32x2    VertexFormat = 29
	VertexFormatFloat32x3    VertexFormat = 30
	VertexFormatFloat32x4    VertexFormat = 31
	VertexFormatUint32       VertexFormat = 32
	VertexFormatUint32x2     VertexFormat = 33
	VertexFormatUint32x3     VertexFormat = 34
	VertexFormatUint32x4     VertexFormat = 35
	VertexFormatSint32       VertexFormat = 36
	VertexFormatSint32x2     VertexFormat = 37
	VertexFormatSint32x3     VertexFormat = 38
	VertexFormatSint32x4     VertexFormat = 39
	VertexFormatUnorm1010102 VertexFormat = 40
	VertexFormatUnorm8x4BGRA VertexFormat = 41
	VertexFormatSnorm1010102 VertexFormat = 42
)

// VertexStepMode is a WebGPU enum.
type VertexStepMode uint32

const (
	VertexStepModeUndefined VertexStepMode = 0
	VertexStepModeVertex    VertexStepMode = 1
	VertexStepModeInstance  VertexStepMode = 2
)

// WaitStatus is a WebGPU enum.
type WaitStatus uint32

const (
	WaitStatusSuccess  WaitStatus = 1
	WaitStatusTimedOut WaitStatus = 2
	WaitStatusError    WaitStatus = 3
)

// WGSLLanguageFeatureName is a WebGPU enum.
type WGSLLanguageFeatureName uint32

const (
	WGSLLanguageFeatureNameReadonlyAndReadwriteStorageTextures WGSLLanguageFeatureName = 1
	WGSLLanguageFeatureNamePacked4x8IntegerDotProduct          WGSLLanguageFeatureName = 2
	WGSLLanguageFeatureNameUnrestrictedPointerParameters       WGSLLanguageFeatureName = 3
	WGSLLanguageFeatureNamePointerCompositeAccess              WGSLLanguageFeatureName = 4
	WGSLLanguageFeatureNameUniformBufferStandardLayout         WGSLLanguageFeatureName = 5
	WGSLLanguageFeatureNameSubgroupId                          WGSLLanguageFeatureName = 6
	WGSLLanguageFeatureNameTextureAndSamplerLet                WGSLLanguageFeatureName = 7
	WGSLLanguageFeatureNameSubgroupUniformity                  WGSLLanguageFeatureName = 8
	WGSLLanguageFeatureNameTextureFormatsTier1                 WGSLLanguageFeatureName = 9
	WGSLLanguageFeatureNameLinearIndexing                      WGSLLanguageFeatureName = 10
	WGSLLanguageFeatureNameImmediateAddressSpace               WGSLLanguageFeatureName = 11
	WGSLLanguageFeatureNameBufferView                          WGSLLanguageFeatureName = 12
	WGSLLanguageFeatureNameSwizzleAssignment                   WGSLLanguageFeatureName = 13
	WGSLLanguageFeatureNameFragmentDepth                       WGSLLanguageFeatureName = 14
)

// ---------------------------------------------------------------------------
// Bitflag types
// ---------------------------------------------------------------------------

// BufferUsage is a WebGPU bitflag type.
type BufferUsage uint64

const (
	BufferUsageNone         BufferUsage = 0
	BufferUsageMapRead      BufferUsage = 1 << 0
	BufferUsageMapWrite     BufferUsage = 1 << 1
	BufferUsageCopySrc      BufferUsage = 1 << 2
	BufferUsageCopyDst      BufferUsage = 1 << 3
	BufferUsageIndex        BufferUsage = 1 << 4
	BufferUsageVertex       BufferUsage = 1 << 5
	BufferUsageUniform      BufferUsage = 1 << 6
	BufferUsageStorage      BufferUsage = 1 << 7
	BufferUsageIndirect     BufferUsage = 1 << 8
	BufferUsageQueryResolve BufferUsage = 1 << 9
)

// ColorWriteMask is a WebGPU bitflag type.
type ColorWriteMask uint64

const (
	ColorWriteMaskNone  ColorWriteMask = 0
	ColorWriteMaskRed   ColorWriteMask = 1 << 0
	ColorWriteMaskGreen ColorWriteMask = 1 << 1
	ColorWriteMaskBlue  ColorWriteMask = 1 << 2
	ColorWriteMaskAlpha ColorWriteMask = 1 << 3
	ColorWriteMaskAll   ColorWriteMask = ColorWriteMaskRed | ColorWriteMaskGreen | ColorWriteMaskBlue | ColorWriteMaskAlpha
)

// MapMode is a WebGPU bitflag type.
type MapMode uint64

const (
	MapModeNone  MapMode = 0
	MapModeRead  MapMode = 1 << 0
	MapModeWrite MapMode = 1 << 1
)

// ShaderStage is a WebGPU bitflag type.
type ShaderStage uint64

const (
	ShaderStageNone     ShaderStage = 0
	ShaderStageVertex   ShaderStage = 1 << 0
	ShaderStageFragment ShaderStage = 1 << 1
	ShaderStageCompute  ShaderStage = 1 << 2
)

// TextureUsage is a WebGPU bitflag type.
type TextureUsage uint64

const (
	TextureUsageNone                TextureUsage = 0
	TextureUsageCopySrc             TextureUsage = 1 << 0
	TextureUsageCopyDst             TextureUsage = 1 << 1
	TextureUsageTextureBinding      TextureUsage = 1 << 2
	TextureUsageStorageBinding      TextureUsage = 1 << 3
	TextureUsageRenderAttachment    TextureUsage = 1 << 4
	TextureUsageTransientAttachment TextureUsage = 1 << 5
)

// ---------------------------------------------------------------------------
// Struct types
// ---------------------------------------------------------------------------

// AdapterInfo is a WebGPU struct.
type AdapterInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Vendor string
	// TODO
	Architecture string
	// TODO
	Device string
	// TODO
	Description string
	// TODO
	BackendType BackendType
	// TODO
	AdapterType AdapterType
	// TODO
	VendorID uint32
	// TODO
	DeviceID uint32
	// TODO
	SubgroupMinSize uint32
	// TODO
	SubgroupMaxSize uint32
}

// BindGroupDescriptor is a WebGPU struct.
type BindGroupDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
	// TODO
	Layout       uintptr
	EntriesCount uintptr
	// TODO
	Entries *BindGroupEntry
}

// BindGroupEntry is a WebGPU struct.
type BindGroupEntry struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// Binding index in the bind group.
	Binding uint32
	// Set this if the binding is a buffer object.
	// Otherwise must be null.
	Buffer uintptr
	// If the binding is a buffer, this is the byte offset of the binding range.
	// Otherwise ignored.
	Offset uint64
	// If the binding is a buffer, this is the byte size of the binding range
	// (@ref WGPU_WHOLE_SIZE means the binding ends at the end of the buffer).
	// Otherwise ignored.
	Size uint64
	// Set this if the binding is a sampler object.
	// Otherwise must be null.
	Sampler uintptr
	// Set this if the binding is a texture view object.
	// Otherwise must be null.
	TextureView uintptr
}

// BindGroupLayoutDescriptor is a WebGPU struct.
type BindGroupLayoutDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label        string
	EntriesCount uintptr
	// TODO
	Entries *BindGroupLayoutEntry
}

// BindGroupLayoutEntry is a WebGPU struct.
type BindGroupLayoutEntry struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Binding uint32
	// TODO
	Visibility ShaderStage
	// If non-zero, this entry defines a binding array with this size.
	BindingArraySize uint32
	// TODO
	Buffer BufferBindingLayout
	// TODO
	Sampler SamplerBindingLayout
	// TODO
	Texture TextureBindingLayout
	// TODO
	StorageTexture StorageTextureBindingLayout
}

// BlendComponent is a WebGPU struct.
type BlendComponent struct {
	_ structs.HostLayout
	// If set to @ref WGPUBlendOperation_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUBlendOperation_Add.
	Operation BlendOperation
	// If set to @ref WGPUBlendFactor_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUBlendFactor_One.
	SrcFactor BlendFactor
	// If set to @ref WGPUBlendFactor_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUBlendFactor_Zero.
	DstFactor BlendFactor
}

// BlendState is a WebGPU struct.
type BlendState struct {
	_ structs.HostLayout
	// TODO
	Color BlendComponent
	// TODO
	Alpha BlendComponent
}

// BufferBindingLayout is a WebGPU struct.
type BufferBindingLayout struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// If set to @ref WGPUBufferBindingType_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUBufferBindingType_Uniform.
	Type BufferBindingType
	// TODO
	HasDynamicOffset uint32
	// TODO
	MinBindingSize uint64
}

// BufferDescriptor is a WebGPU struct.
type BufferDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
	// TODO
	Usage BufferUsage
	// TODO
	Size uint64
	// When true, the buffer is mapped in write mode at creation. It should thus be unmapped once its initial data has been written.
	//
	// @note Mapping at creation does **not** require the usage @ref WGPUBufferUsage_MapWrite.
	MappedAtCreation uint32
}

// Color is a WebGPU struct.
type Color struct {
	_ structs.HostLayout
	R float64
	G float64
	B float64
	A float64
}

// ColorTargetState is a WebGPU struct.
type ColorTargetState struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// The texture format of the target. If @ref WGPUTextureFormat_Undefined,
	// indicates a "hole" in the parent @ref WGPUFragmentState `targets` array:
	// the pipeline does not output a value at this `location`.
	Format TextureFormat
	// TODO
	Blend *BlendState
	// TODO
	WriteMask ColorWriteMask
}

// CommandBufferDescriptor is a WebGPU struct.
type CommandBufferDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
}

// CommandEncoderDescriptor is a WebGPU struct.
type CommandEncoderDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
}

// CompatibilityModeLimits is a WebGPU struct.
type CompatibilityModeLimits struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// TODO
	MaxStorageBuffersInVertexStage uint32
	// TODO
	MaxStorageTexturesInVertexStage uint32
	// TODO
	MaxStorageBuffersInFragmentStage uint32
	// TODO
	MaxStorageTexturesInFragmentStage uint32
}

// CompilationInfo is a WebGPU struct.
type CompilationInfo struct {
	_             structs.HostLayout
	NextInChain   unsafe.Pointer
	MessagesCount uintptr
	// TODO
	Messages *CompilationMessage
}

// CompilationMessage is a WebGPU struct.
type CompilationMessage struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// A @ref LocalizableHumanReadableMessageString.
	Message string
	// Severity level of the message.
	Type CompilationMessageType
	// Line number where the message is attached, starting at 1.
	LineNum uint64
	// Offset in UTF-8 code units (bytes) from the beginning of the line, starting at 1.
	LinePos uint64
	// Offset in UTF-8 code units (bytes) from the beginning of the shader code, starting at 0.
	Offset uint64
	// Length in UTF-8 code units (bytes) of the span the message corresponds to.
	Length uint64
}

// ComputePassDescriptor is a WebGPU struct.
type ComputePassDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
	// TODO
	TimestampWrites *PassTimestampWrites
}

// ComputePipelineDescriptor is a WebGPU struct.
type ComputePipelineDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
	// TODO
	Layout uintptr
	// TODO
	Compute ComputeState
}

// ComputeState is a WebGPU struct.
type ComputeState struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Module uintptr
	// TODO
	EntryPoint     string
	ConstantsCount uintptr
	// TODO
	Constants *ConstantEntry
}

// ConstantEntry is a WebGPU struct.
type ConstantEntry struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Key string
	// Represents a WGSL numeric or boolean value using @ref DoubleAsSupertype.
	//
	// If non-finite, produces a @ref NonFiniteFloatValueError.
	Value float64
}

// DepthStencilState is a WebGPU struct.
type DepthStencilState struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Format TextureFormat
	// TODO
	DepthWriteEnabled OptionalBool
	// TODO
	DepthCompare CompareFunction
	// TODO
	StencilFront StencilFaceState
	// TODO
	StencilBack StencilFaceState
	// TODO
	StencilReadMask uint32
	// TODO
	StencilWriteMask uint32
	// TODO
	DepthBias int32
	// TODO
	//
	// If non-finite, produces a @ref NonFiniteFloatValueError.
	DepthBiasSlopeScale float32
	// TODO
	//
	// If non-finite, produces a @ref NonFiniteFloatValueError.
	DepthBiasClamp float32
}

// DeviceDescriptor is a WebGPU struct.
type DeviceDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label                 string
	RequiredFeaturesCount uintptr
	// TODO
	RequiredFeatures *FeatureName
	// TODO
	RequiredLimits *Limits
	// TODO
	DefaultQueue QueueDescriptor
	// TODO
	DeviceLostCallbackInfo DeviceLostCallbackInfo
	// Called when there is an uncaptured error on this device, from any thread.
	// See @ref ErrorScopes.
	//
	// **Important:** This callback does not have a configurable @ref WGPUCallbackMode; it may be called at any time (like @ref WGPUCallbackMode_AllowSpontaneous). As such, calls into the `webgpu.h` API from this callback are unsafe. See @ref CallbackReentrancy.
	UncapturedErrorCallbackInfo UncapturedErrorCallbackInfo
}

// Extent3D is a WebGPU struct.
type Extent3D struct {
	_ structs.HostLayout
	// TODO
	Width uint32
	// TODO
	Height uint32
	// TODO
	DepthOrArrayLayers uint32
}

// ExternalTextureBindingEntry is a WebGPU struct.
type ExternalTextureBindingEntry struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// TODO
	ExternalTexture uintptr
}

// ExternalTextureBindingLayout is a WebGPU struct.
type ExternalTextureBindingLayout struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
}

// FragmentState is a WebGPU struct.
type FragmentState struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Module uintptr
	// TODO
	EntryPoint     string
	ConstantsCount uintptr
	// TODO
	Constants    *ConstantEntry
	TargetsCount uintptr
	// TODO
	Targets *ColorTargetState
}

// Future is a WebGPU struct.
type Future struct {
	_ structs.HostLayout
	// Opaque id of the @ref WGPUFuture
	Id uint64
}

// FutureWaitInfo is a WebGPU struct.
type FutureWaitInfo struct {
	_ structs.HostLayout
	// The future to wait on.
	Future Future
	// Whether or not the future completed.
	Completed uint32
}

// InstanceDescriptor is a WebGPU struct.
type InstanceDescriptor struct {
	_                     structs.HostLayout
	NextInChain           unsafe.Pointer
	RequiredFeaturesCount uintptr
	// TODO
	RequiredFeatures *InstanceFeatureName
	// TODO
	RequiredLimits *InstanceLimits
}

// InstanceLimits is a WebGPU struct.
type InstanceLimits struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// The maximum number @ref WGPUFutureWaitInfo supported in a call to ::wgpuInstanceWaitAny with `timeoutNS > 0`.
	TimedWaitAnyMaxCount uintptr
}

// Limits is a WebGPU struct.
type Limits struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	MaxTextureDimension1D uint32
	// TODO
	MaxTextureDimension2D uint32
	// TODO
	MaxTextureDimension3D uint32
	// TODO
	MaxTextureArrayLayers uint32
	// TODO
	MaxBindGroups uint32
	// TODO
	MaxBindGroupsPlusVertexBuffers uint32
	// TODO
	MaxBindingsPerBindGroup uint32
	// TODO
	MaxDynamicUniformBuffersPerPipelineLayout uint32
	// TODO
	MaxDynamicStorageBuffersPerPipelineLayout uint32
	// TODO
	MaxSampledTexturesPerShaderStage uint32
	// TODO
	MaxSamplersPerShaderStage uint32
	// TODO
	MaxStorageBuffersPerShaderStage uint32
	// TODO
	MaxStorageTexturesPerShaderStage uint32
	// TODO
	MaxUniformBuffersPerShaderStage uint32
	// TODO
	MaxUniformBufferBindingSize uint64
	// TODO
	MaxStorageBufferBindingSize uint64
	// TODO
	MinUniformBufferOffsetAlignment uint32
	// TODO
	MinStorageBufferOffsetAlignment uint32
	// TODO
	MaxVertexBuffers uint32
	// TODO
	MaxBufferSize uint64
	// TODO
	MaxVertexAttributes uint32
	// TODO
	MaxVertexBufferArrayStride uint32
	// TODO
	MaxInterStageShaderVariables uint32
	// TODO
	MaxColorAttachments uint32
	// TODO
	MaxColorAttachmentBytesPerSample uint32
	// TODO
	MaxComputeWorkgroupStorageSize uint32
	// TODO
	MaxComputeInvocationsPerWorkgroup uint32
	// TODO
	MaxComputeWorkgroupSizeX uint32
	// TODO
	MaxComputeWorkgroupSizeY uint32
	// TODO
	MaxComputeWorkgroupSizeZ uint32
	// TODO
	MaxComputeWorkgroupsPerDimension uint32
	// TODO
	MaxImmediateSize uint32
}

// MultisampleState is a WebGPU struct.
type MultisampleState struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Count uint32
	// TODO
	Mask uint32
	// TODO
	AlphaToCoverageEnabled uint32
}

// Origin3D is a WebGPU struct.
type Origin3D struct {
	_ structs.HostLayout
	// TODO
	X uint32
	// TODO
	Y uint32
	// TODO
	Z uint32
}

// PassTimestampWrites is a WebGPU struct.
type PassTimestampWrites struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// Query set to write timestamps to.
	QuerySet uintptr
	// TODO
	BeginningOfPassWriteIndex uint32
	// TODO
	EndOfPassWriteIndex uint32
}

// PipelineLayoutDescriptor is a WebGPU struct.
type PipelineLayoutDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label                 string
	BindGroupLayoutsCount uintptr
	// TODO
	BindGroupLayouts **BindGroupLayout
	// TODO
	ImmediateSize uint32
}

// PrimitiveState is a WebGPU struct.
type PrimitiveState struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// If set to @ref WGPUPrimitiveTopology_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUPrimitiveTopology_TriangleList.
	Topology PrimitiveTopology
	// TODO
	StripIndexFormat IndexFormat
	// If set to @ref WGPUFrontFace_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUFrontFace_CCW.
	FrontFace FrontFace
	// If set to @ref WGPUCullMode_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUCullMode_None.
	CullMode CullMode
	// TODO
	UnclippedDepth uint32
}

// QuerySetDescriptor is a WebGPU struct.
type QuerySetDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
	// TODO
	Type QueryType
	// TODO
	Count uint32
}

// QueueDescriptor is a WebGPU struct.
type QueueDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
}

// RenderBundleDescriptor is a WebGPU struct.
type RenderBundleDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
}

// RenderBundleEncoderDescriptor is a WebGPU struct.
type RenderBundleEncoderDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label             string
	ColorFormatsCount uintptr
	// TODO
	ColorFormats *TextureFormat
	// TODO
	DepthStencilFormat TextureFormat
	// TODO
	SampleCount uint32
	// TODO
	DepthReadOnly uint32
	// TODO
	StencilReadOnly uint32
}

// RenderPassColorAttachment is a WebGPU struct.
type RenderPassColorAttachment struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// If `NULL`, indicates a hole in the parent
	// @ref WGPURenderPassDescriptor::colorAttachments array.
	View uintptr
	// TODO
	DepthSlice uint32
	// TODO
	ResolveTarget uintptr
	// TODO
	LoadOp LoadOp
	// TODO
	StoreOp StoreOp
	// TODO
	ClearValue Color
}

// RenderPassDepthStencilAttachment is a WebGPU struct.
type RenderPassDepthStencilAttachment struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	View uintptr
	// TODO
	DepthLoadOp LoadOp
	// TODO
	DepthStoreOp StoreOp
	// This is a @ref NullableFloatingPointType.
	//
	// If `NaN`, indicates an `undefined` value (as defined by the JS spec).
	// Use @ref WGPU_DEPTH_CLEAR_VALUE_UNDEFINED to indicate this semantically.
	//
	// If infinite, produces a @ref NonFiniteFloatValueError.
	DepthClearValue *float32
	// TODO
	DepthReadOnly uint32
	// TODO
	StencilLoadOp LoadOp
	// TODO
	StencilStoreOp StoreOp
	// TODO
	StencilClearValue uint32
	// TODO
	StencilReadOnly uint32
}

// RenderPassDescriptor is a WebGPU struct.
type RenderPassDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label                 string
	ColorAttachmentsCount uintptr
	// TODO
	ColorAttachments *RenderPassColorAttachment
	// TODO
	DepthStencilAttachment *RenderPassDepthStencilAttachment
	// TODO
	OcclusionQuerySet uintptr
	// TODO
	TimestampWrites *PassTimestampWrites
}

// RenderPassMaxDrawCount is a WebGPU struct.
type RenderPassMaxDrawCount struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// TODO
	MaxDrawCount uint64
}

// RenderPipelineDescriptor is a WebGPU struct.
type RenderPipelineDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
	// TODO
	Layout uintptr
	// TODO
	Vertex VertexState
	// TODO
	Primitive PrimitiveState
	// TODO
	DepthStencil *DepthStencilState
	// TODO
	Multisample MultisampleState
	// TODO
	Fragment *FragmentState
}

// RequestAdapterOptions is a WebGPU struct.
type RequestAdapterOptions struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// "Feature level" for the adapter request. If an adapter is returned, it must support the features and limits in the requested feature level.
	//
	// If set to @ref WGPUFeatureLevel_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUFeatureLevel_Core.
	// Additionally, implementations may ignore @ref WGPUFeatureLevel_Compatibility
	// and provide @ref WGPUFeatureLevel_Core instead.
	FeatureLevel FeatureLevel
	// TODO
	PowerPreference PowerPreference
	// If true, requires the adapter to be a "fallback" adapter as defined by the JS spec.
	// If this is not possible, the request returns null.
	ForceFallbackAdapter uint32
	// If set, requires the adapter to have a particular backend type.
	// If this is not possible, the request returns null.
	BackendType BackendType
	// If set, requires the adapter to be able to output to a particular surface.
	// If this is not possible, the request returns null.
	CompatibleSurface uintptr
}

// RequestAdapterWebXROptions is a WebGPU struct.
type RequestAdapterWebXROptions struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// Sets the `xrCompatible` option in the JS API.
	XrCompatible uint32
}

// SamplerBindingLayout is a WebGPU struct.
type SamplerBindingLayout struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// If set to @ref WGPUSamplerBindingType_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUSamplerBindingType_Filtering.
	Type SamplerBindingType
}

// SamplerDescriptor is a WebGPU struct.
type SamplerDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
	// If set to @ref WGPUAddressMode_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUAddressMode_ClampToEdge.
	AddressModeU AddressMode
	// If set to @ref WGPUAddressMode_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUAddressMode_ClampToEdge.
	AddressModeV AddressMode
	// If set to @ref WGPUAddressMode_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUAddressMode_ClampToEdge.
	AddressModeW AddressMode
	// If set to @ref WGPUFilterMode_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUFilterMode_Nearest.
	MagFilter FilterMode
	// If set to @ref WGPUFilterMode_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUFilterMode_Nearest.
	MinFilter FilterMode
	// If set to @ref WGPUFilterMode_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUMipmapFilterMode_Nearest.
	MipmapFilter MipmapFilterMode
	// TODO
	//
	// If non-finite, produces a @ref NonFiniteFloatValueError.
	LodMinClamp float32
	// TODO
	//
	// If non-finite, produces a @ref NonFiniteFloatValueError.
	LodMaxClamp float32
	// TODO
	Compare CompareFunction
	// TODO
	MaxAnisotropy uint16
}

// ShaderModuleDescriptor is a WebGPU struct.
type ShaderModuleDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
}

// ShaderSourceSPIRV is a WebGPU struct.
type ShaderSourceSPIRV struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// TODO
	CodeSize uint32
	// TODO
	Code uint32
}

// ShaderSourceWGSL is a WebGPU struct.
type ShaderSourceWGSL struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// TODO
	Code string
}

// StencilFaceState is a WebGPU struct.
type StencilFaceState struct {
	_ structs.HostLayout
	// If set to @ref WGPUCompareFunction_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUCompareFunction_Always.
	Compare CompareFunction
	// If set to @ref WGPUStencilOperation_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUStencilOperation_Keep.
	FailOp StencilOperation
	// If set to @ref WGPUStencilOperation_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUStencilOperation_Keep.
	DepthFailOp StencilOperation
	// If set to @ref WGPUStencilOperation_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUStencilOperation_Keep.
	PassOp StencilOperation
}

// StorageTextureBindingLayout is a WebGPU struct.
type StorageTextureBindingLayout struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// If set to @ref WGPUStorageTextureAccess_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUStorageTextureAccess_WriteOnly.
	Access StorageTextureAccess
	// TODO
	Format TextureFormat
	// If set to @ref WGPUTextureViewDimension_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUTextureViewDimension_2D.
	ViewDimension TextureViewDimension
}

// SupportedFeatures is a WebGPU struct.
type SupportedFeatures struct {
	_             structs.HostLayout
	FeaturesCount uintptr
	// TODO
	Features *FeatureName
}

// SupportedInstanceFeatures is a WebGPU struct.
type SupportedInstanceFeatures struct {
	_             structs.HostLayout
	FeaturesCount uintptr
	// TODO
	Features *InstanceFeatureName
}

// SupportedWGSLLanguageFeatures is a WebGPU struct.
type SupportedWGSLLanguageFeatures struct {
	_             structs.HostLayout
	FeaturesCount uintptr
	// TODO
	Features *WGSLLanguageFeatureName
}

// SurfaceCapabilities is a WebGPU struct.
type SurfaceCapabilities struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// The bit set of supported @ref WGPUTextureUsage bits.
	// Guaranteed to contain @ref WGPUTextureUsage_RenderAttachment.
	Usages       TextureUsage
	FormatsCount uintptr
	// A list of supported @ref WGPUTextureFormat values, in order of preference.
	Formats           *TextureFormat
	PresentModesCount uintptr
	// A list of supported @ref WGPUPresentMode values.
	// Guaranteed to contain @ref WGPUPresentMode_Fifo.
	PresentModes    *PresentMode
	AlphaModesCount uintptr
	// A list of supported @ref WGPUCompositeAlphaMode values.
	// @ref WGPUCompositeAlphaMode_Auto will be an alias for the first element and will never be present in this array.
	AlphaModes *CompositeAlphaMode
}

// SurfaceColorManagement is a WebGPU struct.
type SurfaceColorManagement struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// TODO
	ColorSpace PredefinedColorSpace
	// TODO
	ToneMappingMode ToneMappingMode
}

// SurfaceConfiguration is a WebGPU struct.
type SurfaceConfiguration struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// The @ref WGPUDevice to use to render to surface's textures.
	Device uintptr
	// The @ref WGPUTextureFormat of the surface's textures.
	Format TextureFormat
	// The @ref WGPUTextureUsage of the surface's textures.
	Usage TextureUsage
	// The width of the surface's textures.
	Width uint32
	// The height of the surface's textures.
	Height           uint32
	ViewFormatsCount uintptr
	// The additional @ref WGPUTextureFormat for @ref WGPUTextureView format reinterpretation of the surface's textures.
	ViewFormats *TextureFormat
	// How the surface's frames will be composited on the screen.
	//
	// If set to @ref WGPUCompositeAlphaMode_Auto,
	// [defaults] to @ref WGPUCompositeAlphaMode_Inherit in native (allowing the mode
	// to be configured externally), and to @ref WGPUCompositeAlphaMode_Opaque in Wasm.
	AlphaMode CompositeAlphaMode
	// When and in which order the surface's frames will be shown on the screen.
	//
	// If set to @ref WGPUPresentMode_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUPresentMode_Fifo.
	PresentMode PresentMode
}

// SurfaceDescriptor is a WebGPU struct.
type SurfaceDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// Label used to refer to the object.
	Label string
}

// SurfaceSourceAndroidNativeWindow is a WebGPU struct.
type SurfaceSourceAndroidNativeWindow struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// The pointer to the [`ANativeWindow`](https://developer.android.com/ndk/reference/group/a-native-window) that will be wrapped by the @ref WGPUSurface.
	Window unsafe.Pointer
}

// SurfaceSourceMetalLayer is a WebGPU struct.
type SurfaceSourceMetalLayer struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// The pointer to the [`CAMetalLayer`](https://developer.apple.com/documentation/quartzcore/cametallayer?language=objc) that will be wrapped by the @ref WGPUSurface.
	Layer unsafe.Pointer
}

// SurfaceSourceWaylandSurface is a WebGPU struct.
type SurfaceSourceWaylandSurface struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// A [`wl_display`](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_display) for this Wayland instance.
	Display unsafe.Pointer
	// A [`wl_surface`](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_surface) that will be wrapped by the @ref WGPUSurface
	Surface unsafe.Pointer
}

// SurfaceSourceWindowsHWND is a WebGPU struct.
type SurfaceSourceWindowsHWND struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// The [`HINSTANCE`](https://learn.microsoft.com/en-us/windows/win32/learnwin32/winmain--the-application-entry-point) for this application.
	// Most commonly `GetModuleHandle(nullptr)`.
	Hinstance unsafe.Pointer
	// The [`HWND`](https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/retrieve-hwnd) that will be wrapped by the @ref WGPUSurface.
	Hwnd unsafe.Pointer
}

// SurfaceSourceXCBWindow is a WebGPU struct.
type SurfaceSourceXCBWindow struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// The `xcb_connection_t` for the connection to the X server.
	Connection unsafe.Pointer
	// The `xcb_window_t` for the window that will be wrapped by the @ref WGPUSurface.
	Window uint32
}

// SurfaceSourceXlibWindow is a WebGPU struct.
type SurfaceSourceXlibWindow struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// A pointer to the [`Display`](https://www.x.org/releases/current/doc/libX11/libX11/libX11.html#Opening_the_Display) connected to the X server.
	Display unsafe.Pointer
	// The [`Window`](https://www.x.org/releases/current/doc/libX11/libX11/libX11.html#Creating_Windows) that will be wrapped by the @ref WGPUSurface.
	Window uint64
}

// SurfaceTexture is a WebGPU struct.
type SurfaceTexture struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// The @ref WGPUTexture representing the frame that will be shown on the surface.
	// It is @ref ReturnedWithOwnership from @ref wgpuSurfaceGetCurrentTexture.
	Texture uintptr
	// Whether the call to @ref wgpuSurfaceGetCurrentTexture succeeded and a hint as to why it might not have.
	Status SurfaceGetCurrentTextureStatus
}

// TexelCopyBufferInfo is a WebGPU struct.
type TexelCopyBufferInfo struct {
	_ structs.HostLayout
	// TODO
	Layout TexelCopyBufferLayout
	// TODO
	Buffer uintptr
}

// TexelCopyBufferLayout is a WebGPU struct.
type TexelCopyBufferLayout struct {
	_ structs.HostLayout
	// TODO
	Offset uint64
	// TODO
	BytesPerRow uint32
	// TODO
	RowsPerImage uint32
}

// TexelCopyTextureInfo is a WebGPU struct.
type TexelCopyTextureInfo struct {
	_ structs.HostLayout
	// TODO
	Texture uintptr
	// TODO
	MipLevel uint32
	// TODO
	Origin Origin3D
	// If set to @ref WGPUTextureAspect_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUTextureAspect_All.
	Aspect TextureAspect
}

// TextureBindingLayout is a WebGPU struct.
type TextureBindingLayout struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// If set to @ref WGPUTextureSampleType_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUTextureSampleType_Float.
	SampleType TextureSampleType
	// If set to @ref WGPUTextureViewDimension_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUTextureViewDimension_2D.
	ViewDimension TextureViewDimension
	// TODO
	Multisampled uint32
}

// TextureBindingViewDimension is a WebGPU struct.
type TextureBindingViewDimension struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// TODO
	TextureBindingViewDimension TextureViewDimension
}

// TextureComponentSwizzle is a WebGPU struct.
type TextureComponentSwizzle struct {
	_ structs.HostLayout
	// The value that replaces the red channel in the shader.
	//
	// If set to @ref WGPUComponentSwizzle_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUComponentSwizzle_R.
	R ComponentSwizzle
	// The value that replaces the green channel in the shader.
	//
	// If set to @ref WGPUComponentSwizzle_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUComponentSwizzle_G.
	G ComponentSwizzle
	// The value that replaces the blue channel in the shader.
	//
	// If set to @ref WGPUComponentSwizzle_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUComponentSwizzle_B.
	B ComponentSwizzle
	// The value that replaces the alpha channel in the shader.
	//
	// If set to @ref WGPUComponentSwizzle_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUComponentSwizzle_A.
	A ComponentSwizzle
}

// TextureComponentSwizzleDescriptor is a WebGPU struct.
type TextureComponentSwizzleDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	SType       SType
	// TODO
	Swizzle TextureComponentSwizzle
}

// TextureDescriptor is a WebGPU struct.
type TextureDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
	// TODO
	Usage TextureUsage
	// If set to @ref WGPUTextureDimension_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUTextureDimension_2D.
	Dimension TextureDimension
	// TODO
	Size Extent3D
	// TODO
	Format TextureFormat
	// TODO
	MipLevelCount uint32
	// TODO
	SampleCount      uint32
	ViewFormatsCount uintptr
	// TODO
	ViewFormats *TextureFormat
}

// TextureViewDescriptor is a WebGPU struct.
type TextureViewDescriptor struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Label string
	// TODO
	Format TextureFormat
	// TODO
	Dimension TextureViewDimension
	// TODO
	BaseMipLevel uint32
	// TODO
	MipLevelCount uint32
	// TODO
	BaseArrayLayer uint32
	// TODO
	ArrayLayerCount uint32
	// If set to @ref WGPUTextureAspect_Undefined,
	// [defaults](@ref SentinelValues) to @ref WGPUTextureAspect_All.
	Aspect TextureAspect
	// TODO
	Usage TextureUsage
}

// VertexAttribute is a WebGPU struct.
type VertexAttribute struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Format VertexFormat
	// TODO
	Offset uint64
	// TODO
	ShaderLocation uint32
}

// VertexBufferLayout is a WebGPU struct.
type VertexBufferLayout struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	StepMode VertexStepMode
	// TODO
	ArrayStride     uint64
	AttributesCount uintptr
	// TODO
	Attributes *VertexAttribute
}

// VertexState is a WebGPU struct.
type VertexState struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	// TODO
	Module uintptr
	// TODO
	EntryPoint     string
	ConstantsCount uintptr
	// TODO
	Constants    *ConstantEntry
	BuffersCount uintptr
	// TODO
	Buffers *VertexBufferLayout
}

// ---------------------------------------------------------------------------
// Callback info records (embedded in descriptors / async calls)
// ---------------------------------------------------------------------------

// BufferMapCallbackInfo matches C.WGPUBufferMapCallbackInfo.
type BufferMapCallbackInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	Mode        CallbackMode
	Callback    uintptr
	Userdata1   unsafe.Pointer
	Userdata2   unsafe.Pointer
}

// CompilationInfoCallbackInfo matches C.WGPUCompilationInfoCallbackInfo.
type CompilationInfoCallbackInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	Mode        CallbackMode
	Callback    uintptr
	Userdata1   unsafe.Pointer
	Userdata2   unsafe.Pointer
}

// CreateComputePipelineAsyncCallbackInfo matches C.WGPUCreateComputePipelineAsyncCallbackInfo.
type CreateComputePipelineAsyncCallbackInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	Mode        CallbackMode
	Callback    uintptr
	Userdata1   unsafe.Pointer
	Userdata2   unsafe.Pointer
}

// CreateRenderPipelineAsyncCallbackInfo matches C.WGPUCreateRenderPipelineAsyncCallbackInfo.
type CreateRenderPipelineAsyncCallbackInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	Mode        CallbackMode
	Callback    uintptr
	Userdata1   unsafe.Pointer
	Userdata2   unsafe.Pointer
}

// DeviceLostCallbackInfo matches C.WGPUDeviceLostCallbackInfo.
type DeviceLostCallbackInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	Mode        CallbackMode
	Callback    uintptr
	Userdata1   unsafe.Pointer
	Userdata2   unsafe.Pointer
}

// PopErrorScopeCallbackInfo matches C.WGPUPopErrorScopeCallbackInfo.
type PopErrorScopeCallbackInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	Mode        CallbackMode
	Callback    uintptr
	Userdata1   unsafe.Pointer
	Userdata2   unsafe.Pointer
}

// QueueWorkDoneCallbackInfo matches C.WGPUQueueWorkDoneCallbackInfo.
type QueueWorkDoneCallbackInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	Mode        CallbackMode
	Callback    uintptr
	Userdata1   unsafe.Pointer
	Userdata2   unsafe.Pointer
}

// RequestAdapterCallbackInfo matches C.WGPURequestAdapterCallbackInfo.
type RequestAdapterCallbackInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	Mode        CallbackMode
	Callback    uintptr
	Userdata1   unsafe.Pointer
	Userdata2   unsafe.Pointer
}

// RequestDeviceCallbackInfo matches C.WGPURequestDeviceCallbackInfo.
type RequestDeviceCallbackInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	Mode        CallbackMode
	Callback    uintptr
	Userdata1   unsafe.Pointer
	Userdata2   unsafe.Pointer
}

// UncapturedErrorCallbackInfo matches C.WGPUUncapturedErrorCallbackInfo.
type UncapturedErrorCallbackInfo struct {
	_           structs.HostLayout
	NextInChain unsafe.Pointer
	Callback    uintptr
	Userdata1   unsafe.Pointer
	Userdata2   unsafe.Pointer
}

// ---------------------------------------------------------------------------
// Handle (object) types
// ---------------------------------------------------------------------------

// Adapter is a WebGPU object handle.
type Adapter struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *Adapter) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// BindGroup is a WebGPU object handle.
type BindGroup struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *BindGroup) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// BindGroupLayout is a WebGPU object handle.
type BindGroupLayout struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *BindGroupLayout) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// Buffer is a WebGPU object handle.
type Buffer struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *Buffer) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// CommandBuffer is a WebGPU object handle.
type CommandBuffer struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *CommandBuffer) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// CommandEncoder is a WebGPU object handle.
type CommandEncoder struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *CommandEncoder) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// ComputePassEncoder is a WebGPU object handle.
type ComputePassEncoder struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *ComputePassEncoder) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// ComputePipeline is a WebGPU object handle.
type ComputePipeline struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *ComputePipeline) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// Device is a WebGPU object handle.
type Device struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *Device) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// ExternalTexture is a WebGPU object handle.
type ExternalTexture struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *ExternalTexture) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// Instance is a WebGPU object handle.
type Instance struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *Instance) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// PipelineLayout is a WebGPU object handle.
type PipelineLayout struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *PipelineLayout) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// QuerySet is a WebGPU object handle.
type QuerySet struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *QuerySet) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// Queue is a WebGPU object handle.
type Queue struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *Queue) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// RenderBundle is a WebGPU object handle.
type RenderBundle struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *RenderBundle) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// RenderBundleEncoder is a WebGPU object handle.
type RenderBundleEncoder struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *RenderBundleEncoder) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// RenderPassEncoder is a WebGPU object handle.
type RenderPassEncoder struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *RenderPassEncoder) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// RenderPipeline is a WebGPU object handle.
type RenderPipeline struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *RenderPipeline) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// Sampler is a WebGPU object handle.
type Sampler struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *Sampler) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// ShaderModule is a WebGPU object handle.
type ShaderModule struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *ShaderModule) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// Surface is a WebGPU object handle.
type Surface struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *Surface) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// Texture is a WebGPU object handle.
type Texture struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *Texture) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// TextureView is a WebGPU object handle.
type TextureView struct {
	inner uintptr // native handle
}

// Handle returns the raw native handle.
func (h *TextureView) Handle() uintptr {
	if h == nil {
		return 0
	}
	return h.inner
}

// ---------------------------------------------------------------------------
// Callback types
// ---------------------------------------------------------------------------

// BufferMapFn is a callback function type.
type BufferMapFn func(status MapAsyncStatus, message string)

// CompilationInfoFn is a callback function type.
type CompilationInfoFn func(status CompilationInfoRequestStatus, compilationInfo CompilationInfo)

// CreateComputePipelineAsyncFn is a callback function type.
type CreateComputePipelineAsyncFn func(status CreatePipelineAsyncStatus, pipeline *ComputePipeline, message string)

// CreateRenderPipelineAsyncFn is a callback function type.
type CreateRenderPipelineAsyncFn func(status CreatePipelineAsyncStatus, pipeline *RenderPipeline, message string)

// DeviceLostFn is a callback function type.
type DeviceLostFn func(device *Device, reason DeviceLostReason, message string)

// PopErrorScopeFn is a callback function type.
type PopErrorScopeFn func(status PopErrorScopeStatus, typeVal ErrorType, message string)

// QueueWorkDoneFn is a callback function type.
type QueueWorkDoneFn func(status QueueWorkDoneStatus, message string)

// RequestAdapterFn is a callback function type.
type RequestAdapterFn func(status RequestAdapterStatus, adapter *Adapter, message string)

// RequestDeviceFn is a callback function type.
type RequestDeviceFn func(status RequestDeviceStatus, device *Device, message string)

// UncapturedErrorFn is a callback function type.
type UncapturedErrorFn func(device *Device, typeVal ErrorType, message string)
