// Code generated by gen; DO NOT EDIT.
//go:build cgo

package webgpu

/*
#cgo CFLAGS: -I${SRCDIR}/../third_party/webgpu-headers
#cgo darwin,arm64 LDFLAGS: -L${SRCDIR}/../third_party/wgpu-native/macos-aarch64/lib -lwgpu_native
#cgo darwin,amd64 LDFLAGS: -L${SRCDIR}/../third_party/wgpu-native/macos-x86_64/lib -lwgpu_native
#cgo linux,amd64 LDFLAGS: -L${SRCDIR}/../third_party/wgpu-native/linux-x86_64/lib -lwgpu_native
#cgo linux,arm64 LDFLAGS: -L${SRCDIR}/../third_party/wgpu-native/linux-aarch64/lib -lwgpu_native
#include "webgpu.h"
#include <stdlib.h>
extern void goBufferMapCB(WGPUMapAsyncStatus status, WGPUStringView message, void* userdata1, void* userdata2);
extern void goQueueWorkDoneCB(WGPUQueueWorkDoneStatus status, WGPUStringView message, void* userdata1, void* userdata2);
extern void goRequestAdapterCB(WGPURequestAdapterStatus status, WGPUAdapter adapter, WGPUStringView message, void* userdata1, void* userdata2);
extern void goRequestDeviceCB(WGPURequestDeviceStatus status, WGPUDevice device, WGPUStringView message, void* userdata1, void* userdata2);
*/
import "C"

import (
	"runtime"
	"runtime/cgo"
	"unsafe"
)

// ---------------------------------------------------------------------------
// CGO helpers
// ---------------------------------------------------------------------------

func cgoStringView(s string, pinner *runtime.Pinner) C.WGPUStringView {
	var v C.WGPUStringView
	if len(s) > 0 {
		p := (*C.char)(unsafe.Pointer(unsafe.StringData(s)))
		pinner.Pin(unsafe.StringData(s))
		v.data = p
		v.length = C.size_t(len(s))
	}
	return v
}

func cgoGoString(v C.WGPUStringView) string {
	if v.data == nil || v.length == 0 {
		return ""
	}
	return C.GoStringN(v.data, C.int(v.length))
}

// ---------------------------------------------------------------------------
// Callback trampolines
// ---------------------------------------------------------------------------

//export goBufferMapCB
func goBufferMapCB(status C.WGPUMapAsyncStatus, message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	h := cgo.Handle(uintptr(userdata1))
	defer h.Delete()
	cb := h.Value().(BufferMapFn)
	cb(MapAsyncStatus(status), cgoGoString(message))
}

//export goQueueWorkDoneCB
func goQueueWorkDoneCB(status C.WGPUQueueWorkDoneStatus, message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	h := cgo.Handle(uintptr(userdata1))
	defer h.Delete()
	cb := h.Value().(QueueWorkDoneFn)
	cb(QueueWorkDoneStatus(status), cgoGoString(message))
}

//export goRequestAdapterCB
func goRequestAdapterCB(status C.WGPURequestAdapterStatus, adapter C.WGPUAdapter, message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	h := cgo.Handle(uintptr(userdata1))
	defer h.Delete()
	cb := h.Value().(RequestAdapterFn)
	var a *Adapter
	if adapter != nil {
		a = &Adapter{inner: uintptr(unsafe.Pointer(adapter))}
	}
	cb(RequestAdapterStatus(status), a, cgoGoString(message))
}

//export goRequestDeviceCB
func goRequestDeviceCB(status C.WGPURequestDeviceStatus, device C.WGPUDevice, message C.WGPUStringView, userdata1, userdata2 unsafe.Pointer) {
	h := cgo.Handle(uintptr(userdata1))
	defer h.Delete()
	cb := h.Value().(RequestDeviceFn)
	var d *Device
	if device != nil {
		d = &Device{inner: uintptr(unsafe.Pointer(device))}
	}
	cb(RequestDeviceStatus(status), d, cgoGoString(message))
}

// ---------------------------------------------------------------------------
// CGO function implementations
// ---------------------------------------------------------------------------

// CreateInstance calls C.wgpuCreateInstance.
func CreateInstance(descriptor InstanceDescriptor) *Instance {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.RequiredFeatures != nil {
		pinner.Pin(descriptor.RequiredFeatures)
	}
	c_descriptor := (*C.WGPUInstanceDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuCreateInstance(c_descriptor)
	return &Instance{inner: uintptr(unsafe.Pointer(c_result))}
}

// GetInstanceFeatures calls C.wgpuGetInstanceFeatures.
func GetInstanceFeatures(features SupportedInstanceFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&features)
	if features.Features != nil {
		pinner.Pin(features.Features)
	}
	c_features := (*C.WGPUSupportedInstanceFeatures)(unsafe.Pointer(&features))
	C.wgpuGetInstanceFeatures(c_features)
}

// GetInstanceLimits calls C.wgpuGetInstanceLimits.
func GetInstanceLimits(limits InstanceLimits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&limits)
	c_limits := (*C.WGPUInstanceLimits)(unsafe.Pointer(&limits))
	c_result := C.wgpuGetInstanceLimits(c_limits)
	return (Status)(c_result)
}

// HasInstanceFeature calls C.wgpuHasInstanceFeature.
func HasInstanceFeature(feature InstanceFeatureName) bool {
	c_feature := (C.WGPUInstanceFeatureName)(feature)
	c_result := C.wgpuHasInstanceFeature(c_feature)
	return c_result != 0
}

// GetLimits calls C.wgpuAdapterGetLimits.
func (a *Adapter) GetLimits(limits Limits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&limits)
	c_a := (C.WGPUAdapter)(unsafe.Pointer(a.inner))
	c_limits := (*C.WGPULimits)(unsafe.Pointer(&limits))
	c_result := C.wgpuAdapterGetLimits(c_a, c_limits)
	return (Status)(c_result)
}

// HasFeature calls C.wgpuAdapterHasFeature.
func (a *Adapter) HasFeature(feature FeatureName) bool {
	c_a := (C.WGPUAdapter)(unsafe.Pointer(a.inner))
	c_feature := (C.WGPUFeatureName)(feature)
	c_result := C.wgpuAdapterHasFeature(c_a, c_feature)
	return c_result != 0
}

// GetFeatures calls C.wgpuAdapterGetFeatures.
func (a *Adapter) GetFeatures(features SupportedFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&features)
	if features.Features != nil {
		pinner.Pin(features.Features)
	}
	c_a := (C.WGPUAdapter)(unsafe.Pointer(a.inner))
	c_features := (*C.WGPUSupportedFeatures)(unsafe.Pointer(&features))
	C.wgpuAdapterGetFeatures(c_a, c_features)
}

// GetInfo calls C.wgpuAdapterGetInfo.
func (a *Adapter) GetInfo(info AdapterInfo) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&info)
	c_a := (C.WGPUAdapter)(unsafe.Pointer(a.inner))
	c_info := (*C.WGPUAdapterInfo)(unsafe.Pointer(&info))
	c_result := C.wgpuAdapterGetInfo(c_a, c_info)
	return (Status)(c_result)
}

// RequestDevice calls C.wgpuAdapterRequestDevice.
func (a *Adapter) RequestDevice(descriptor DeviceDescriptor, callback RequestDeviceFn) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.RequiredFeatures != nil {
		pinner.Pin(descriptor.RequiredFeatures)
	}
	c_a := (C.WGPUAdapter)(unsafe.Pointer(a.inner))
	c_descriptor := (*C.WGPUDeviceDescriptor)(unsafe.Pointer(&descriptor))
	_cbHandle := cgo.NewHandle(callback)
	var _cbInfo C.WGPURequestDeviceCallbackInfo
	_cbInfo.mode = C.WGPUCallbackMode_AllowProcessEvents
	// cgo.Handle is an opaque uintptr key; cast through uintptr for userdata.
	_cbInfo.userdata1 = *(*unsafe.Pointer)(unsafe.Pointer(&_cbHandle))
	_cbInfo.callback = C.WGPURequestDeviceCallback(C.goRequestDeviceCB)
	c_result := C.wgpuAdapterRequestDevice(c_a, c_descriptor, _cbInfo)
	return Future{Id: uint64(c_result.id)}
}

// SetLabel calls C.wgpuBindGroupSetLabel.
func (b *BindGroup) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_b := (C.WGPUBindGroup)(unsafe.Pointer(b.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuBindGroupSetLabel(c_b, c_label)
}

// SetLabel calls C.wgpuBindGroupLayoutSetLabel.
func (b *BindGroupLayout) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_b := (C.WGPUBindGroupLayout)(unsafe.Pointer(b.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuBindGroupLayoutSetLabel(c_b, c_label)
}

// MapAsync calls C.wgpuBufferMapAsync.
func (b *Buffer) MapAsync(mode MapMode, offset uintptr, size uintptr, callback BufferMapFn) Future {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	c_mode := (C.WGPUMapMode)(mode)
	c_offset := (C.size_t)(offset)
	c_size := (C.size_t)(size)
	_cbHandle := cgo.NewHandle(callback)
	var _cbInfo C.WGPUBufferMapCallbackInfo
	_cbInfo.mode = C.WGPUCallbackMode_AllowProcessEvents
	// cgo.Handle is an opaque uintptr key; cast through uintptr for userdata.
	_cbInfo.userdata1 = *(*unsafe.Pointer)(unsafe.Pointer(&_cbHandle))
	_cbInfo.callback = C.WGPUBufferMapCallback(C.goBufferMapCB)
	c_result := C.wgpuBufferMapAsync(c_b, c_mode, c_offset, c_size, _cbInfo)
	return Future{Id: uint64(c_result.id)}
}

// GetMappedRange calls C.wgpuBufferGetMappedRange.
func (b *Buffer) GetMappedRange(offset uintptr, size uintptr) unsafe.Pointer {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	c_offset := (C.size_t)(offset)
	c_size := (C.size_t)(size)
	c_result := C.wgpuBufferGetMappedRange(c_b, c_offset, c_size)
	return (unsafe.Pointer)(c_result)
}

// GetConstMappedRange calls C.wgpuBufferGetConstMappedRange.
func (b *Buffer) GetConstMappedRange(offset uintptr, size uintptr) unsafe.Pointer {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	c_offset := (C.size_t)(offset)
	c_size := (C.size_t)(size)
	c_result := C.wgpuBufferGetConstMappedRange(c_b, c_offset, c_size)
	return (unsafe.Pointer)(c_result)
}

// ReadMappedRange calls C.wgpuBufferReadMappedRange.
func (b *Buffer) ReadMappedRange(offset uintptr, data unsafe.Pointer, size uintptr) Status {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	c_offset := (C.size_t)(offset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	c_result := C.wgpuBufferReadMappedRange(c_b, c_offset, c_data, c_size)
	return (Status)(c_result)
}

// WriteMappedRange calls C.wgpuBufferWriteMappedRange.
func (b *Buffer) WriteMappedRange(offset uintptr, data unsafe.Pointer, size uintptr) Status {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	c_offset := (C.size_t)(offset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	c_result := C.wgpuBufferWriteMappedRange(c_b, c_offset, c_data, c_size)
	return (Status)(c_result)
}

// SetLabel calls C.wgpuBufferSetLabel.
func (b *Buffer) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuBufferSetLabel(c_b, c_label)
}

// GetUsage calls C.wgpuBufferGetUsage.
func (b *Buffer) GetUsage() BufferUsage {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	c_result := C.wgpuBufferGetUsage(c_b)
	return (BufferUsage)(c_result)
}

// GetSize calls C.wgpuBufferGetSize.
func (b *Buffer) GetSize() uint64 {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	c_result := C.wgpuBufferGetSize(c_b)
	return (uint64)(c_result)
}

// GetMapState calls C.wgpuBufferGetMapState.
func (b *Buffer) GetMapState() BufferMapState {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	c_result := C.wgpuBufferGetMapState(c_b)
	return (BufferMapState)(c_result)
}

// Unmap calls C.wgpuBufferUnmap.
func (b *Buffer) Unmap() {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	C.wgpuBufferUnmap(c_b)
}

// Destroy calls C.wgpuBufferDestroy.
func (b *Buffer) Destroy() {
	c_b := (C.WGPUBuffer)(unsafe.Pointer(b.inner))
	C.wgpuBufferDestroy(c_b)
}

// SetLabel calls C.wgpuCommandBufferSetLabel.
func (c *CommandBuffer) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_c := (C.WGPUCommandBuffer)(unsafe.Pointer(c.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuCommandBufferSetLabel(c_c, c_label)
}

// Finish calls C.wgpuCommandEncoderFinish.
func (c *CommandEncoder) Finish(descriptor CommandBufferDescriptor) *CommandBuffer {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_descriptor := (*C.WGPUCommandBufferDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuCommandEncoderFinish(c_c, c_descriptor)
	return &CommandBuffer{inner: uintptr(unsafe.Pointer(c_result))}
}

// BeginComputePass calls C.wgpuCommandEncoderBeginComputePass.
func (c *CommandEncoder) BeginComputePass(descriptor ComputePassDescriptor) *ComputePassEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_descriptor := (*C.WGPUComputePassDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuCommandEncoderBeginComputePass(c_c, c_descriptor)
	return &ComputePassEncoder{inner: uintptr(unsafe.Pointer(c_result))}
}

// BeginRenderPass calls C.wgpuCommandEncoderBeginRenderPass.
func (c *CommandEncoder) BeginRenderPass(descriptor RenderPassDescriptor) *RenderPassEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.ColorAttachments != nil {
		pinner.Pin(descriptor.ColorAttachments)
	}
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_descriptor := (*C.WGPURenderPassDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuCommandEncoderBeginRenderPass(c_c, c_descriptor)
	return &RenderPassEncoder{inner: uintptr(unsafe.Pointer(c_result))}
}

// CopyBufferToBuffer calls C.wgpuCommandEncoderCopyBufferToBuffer.
func (c *CommandEncoder) CopyBufferToBuffer(source *Buffer, sourceOffset uint64, destination *Buffer, destinationOffset uint64, size uint64) {
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_source := (C.WGPUBuffer)(unsafe.Pointer(source.inner))
	c_sourceOffset := (C.uint64_t)(sourceOffset)
	c_destination := (C.WGPUBuffer)(unsafe.Pointer(destination.inner))
	c_destinationOffset := (C.uint64_t)(destinationOffset)
	c_size := (C.uint64_t)(size)
	C.wgpuCommandEncoderCopyBufferToBuffer(c_c, c_source, c_sourceOffset, c_destination, c_destinationOffset, c_size)
}

// CopyBufferToTexture calls C.wgpuCommandEncoderCopyBufferToTexture.
func (c *CommandEncoder) CopyBufferToTexture(source TexelCopyBufferInfo, destination TexelCopyTextureInfo, copySize Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&source)
	pinner.Pin(&destination)
	pinner.Pin(&copySize)
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_source := (*C.WGPUTexelCopyBufferInfo)(unsafe.Pointer(&source))
	c_destination := (*C.WGPUTexelCopyTextureInfo)(unsafe.Pointer(&destination))
	c_copySize := (*C.WGPUExtent3D)(unsafe.Pointer(&copySize))
	C.wgpuCommandEncoderCopyBufferToTexture(c_c, c_source, c_destination, c_copySize)
}

// CopyTextureToBuffer calls C.wgpuCommandEncoderCopyTextureToBuffer.
func (c *CommandEncoder) CopyTextureToBuffer(source TexelCopyTextureInfo, destination TexelCopyBufferInfo, copySize Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&source)
	pinner.Pin(&destination)
	pinner.Pin(&copySize)
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_source := (*C.WGPUTexelCopyTextureInfo)(unsafe.Pointer(&source))
	c_destination := (*C.WGPUTexelCopyBufferInfo)(unsafe.Pointer(&destination))
	c_copySize := (*C.WGPUExtent3D)(unsafe.Pointer(&copySize))
	C.wgpuCommandEncoderCopyTextureToBuffer(c_c, c_source, c_destination, c_copySize)
}

// CopyTextureToTexture calls C.wgpuCommandEncoderCopyTextureToTexture.
func (c *CommandEncoder) CopyTextureToTexture(source TexelCopyTextureInfo, destination TexelCopyTextureInfo, copySize Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&source)
	pinner.Pin(&destination)
	pinner.Pin(&copySize)
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_source := (*C.WGPUTexelCopyTextureInfo)(unsafe.Pointer(&source))
	c_destination := (*C.WGPUTexelCopyTextureInfo)(unsafe.Pointer(&destination))
	c_copySize := (*C.WGPUExtent3D)(unsafe.Pointer(&copySize))
	C.wgpuCommandEncoderCopyTextureToTexture(c_c, c_source, c_destination, c_copySize)
}

// ClearBuffer calls C.wgpuCommandEncoderClearBuffer.
func (c *CommandEncoder) ClearBuffer(buffer *Buffer, offset uint64, size uint64) {
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer.inner))
	c_offset := (C.uint64_t)(offset)
	c_size := (C.uint64_t)(size)
	C.wgpuCommandEncoderClearBuffer(c_c, c_buffer, c_offset, c_size)
}

// InsertDebugMarker calls C.wgpuCommandEncoderInsertDebugMarker.
func (c *CommandEncoder) InsertDebugMarker(markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_markerLabel := cgoStringView(markerLabel, &pinner)
	C.wgpuCommandEncoderInsertDebugMarker(c_c, c_markerLabel)
}

// PopDebugGroup calls C.wgpuCommandEncoderPopDebugGroup.
func (c *CommandEncoder) PopDebugGroup() {
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	C.wgpuCommandEncoderPopDebugGroup(c_c)
}

// PushDebugGroup calls C.wgpuCommandEncoderPushDebugGroup.
func (c *CommandEncoder) PushDebugGroup(groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_groupLabel := cgoStringView(groupLabel, &pinner)
	C.wgpuCommandEncoderPushDebugGroup(c_c, c_groupLabel)
}

// ResolveQuerySet calls C.wgpuCommandEncoderResolveQuerySet.
func (c *CommandEncoder) ResolveQuerySet(querySet *QuerySet, firstQuery uint32, queryCount uint32, destination *Buffer, destinationOffset uint64) {
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_querySet := (C.WGPUQuerySet)(unsafe.Pointer(querySet.inner))
	c_firstQuery := (C.uint32_t)(firstQuery)
	c_queryCount := (C.uint32_t)(queryCount)
	c_destination := (C.WGPUBuffer)(unsafe.Pointer(destination.inner))
	c_destinationOffset := (C.uint64_t)(destinationOffset)
	C.wgpuCommandEncoderResolveQuerySet(c_c, c_querySet, c_firstQuery, c_queryCount, c_destination, c_destinationOffset)
}

// WriteTimestamp calls C.wgpuCommandEncoderWriteTimestamp.
func (c *CommandEncoder) WriteTimestamp(querySet *QuerySet, queryIndex uint32) {
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_querySet := (C.WGPUQuerySet)(unsafe.Pointer(querySet.inner))
	c_queryIndex := (C.uint32_t)(queryIndex)
	C.wgpuCommandEncoderWriteTimestamp(c_c, c_querySet, c_queryIndex)
}

// SetLabel calls C.wgpuCommandEncoderSetLabel.
func (c *CommandEncoder) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_c := (C.WGPUCommandEncoder)(unsafe.Pointer(c.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuCommandEncoderSetLabel(c_c, c_label)
}

// InsertDebugMarker calls C.wgpuComputePassEncoderInsertDebugMarker.
func (c *ComputePassEncoder) InsertDebugMarker(markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c.inner))
	c_markerLabel := cgoStringView(markerLabel, &pinner)
	C.wgpuComputePassEncoderInsertDebugMarker(c_c, c_markerLabel)
}

// PopDebugGroup calls C.wgpuComputePassEncoderPopDebugGroup.
func (c *ComputePassEncoder) PopDebugGroup() {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c.inner))
	C.wgpuComputePassEncoderPopDebugGroup(c_c)
}

// PushDebugGroup calls C.wgpuComputePassEncoderPushDebugGroup.
func (c *ComputePassEncoder) PushDebugGroup(groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c.inner))
	c_groupLabel := cgoStringView(groupLabel, &pinner)
	C.wgpuComputePassEncoderPushDebugGroup(c_c, c_groupLabel)
}

// SetPipeline calls C.wgpuComputePassEncoderSetPipeline.
func (c *ComputePassEncoder) SetPipeline(pipeline *ComputePipeline) {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c.inner))
	c_pipeline := (C.WGPUComputePipeline)(unsafe.Pointer(pipeline.inner))
	C.wgpuComputePassEncoderSetPipeline(c_c, c_pipeline)
}

// SetBindGroup calls C.wgpuComputePassEncoderSetBindGroup.
func (c *ComputePassEncoder) SetBindGroup(groupIndex uint32, group *BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c.inner))
	c_groupIndex := (C.uint32_t)(groupIndex)
	c_group := (C.WGPUBindGroup)(unsafe.Pointer(group.inner))
	var c_dynamicOffsets_ptr *C.uint32_t
	if len(dynamicOffsets) > 0 {
		c_dynamicOffsets_ptr = (*C.uint32_t)(unsafe.Pointer(&dynamicOffsets[0]))
	}
	c_dynamicOffsets_count := (C.size_t)(len(dynamicOffsets))
	C.wgpuComputePassEncoderSetBindGroup(c_c, c_groupIndex, c_group, c_dynamicOffsets_count, c_dynamicOffsets_ptr)
}

// SetImmediates calls C.wgpuComputePassEncoderSetImmediates.
func (c *ComputePassEncoder) SetImmediates(offset uint32, data unsafe.Pointer, size uintptr) {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c.inner))
	c_offset := (C.uint32_t)(offset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	C.wgpuComputePassEncoderSetImmediates(c_c, c_offset, c_data, c_size)
}

// DispatchWorkgroups calls C.wgpuComputePassEncoderDispatchWorkgroups.
func (c *ComputePassEncoder) DispatchWorkgroups(workgroupCountX uint32, workgroupCountY uint32, workgroupCountZ uint32) {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c.inner))
	c_workgroupCountX := (C.uint32_t)(workgroupCountX)
	c_workgroupCountY := (C.uint32_t)(workgroupCountY)
	c_workgroupCountZ := (C.uint32_t)(workgroupCountZ)
	C.wgpuComputePassEncoderDispatchWorkgroups(c_c, c_workgroupCountX, c_workgroupCountY, c_workgroupCountZ)
}

// DispatchWorkgroupsIndirect calls C.wgpuComputePassEncoderDispatchWorkgroupsIndirect.
func (c *ComputePassEncoder) DispatchWorkgroupsIndirect(indirectBuffer *Buffer, indirectOffset uint64) {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c.inner))
	c_indirectBuffer := (C.WGPUBuffer)(unsafe.Pointer(indirectBuffer.inner))
	c_indirectOffset := (C.uint64_t)(indirectOffset)
	C.wgpuComputePassEncoderDispatchWorkgroupsIndirect(c_c, c_indirectBuffer, c_indirectOffset)
}

// End calls C.wgpuComputePassEncoderEnd.
func (c *ComputePassEncoder) End() {
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c.inner))
	C.wgpuComputePassEncoderEnd(c_c)
}

// SetLabel calls C.wgpuComputePassEncoderSetLabel.
func (c *ComputePassEncoder) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_c := (C.WGPUComputePassEncoder)(unsafe.Pointer(c.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuComputePassEncoderSetLabel(c_c, c_label)
}

// GetBindGroupLayout calls C.wgpuComputePipelineGetBindGroupLayout.
func (c *ComputePipeline) GetBindGroupLayout(groupIndex uint32) *BindGroupLayout {
	c_c := (C.WGPUComputePipeline)(unsafe.Pointer(c.inner))
	c_groupIndex := (C.uint32_t)(groupIndex)
	c_result := C.wgpuComputePipelineGetBindGroupLayout(c_c, c_groupIndex)
	return &BindGroupLayout{inner: uintptr(unsafe.Pointer(c_result))}
}

// SetLabel calls C.wgpuComputePipelineSetLabel.
func (c *ComputePipeline) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_c := (C.WGPUComputePipeline)(unsafe.Pointer(c.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuComputePipelineSetLabel(c_c, c_label)
}

// CreateBindGroup calls C.wgpuDeviceCreateBindGroup.
func (d *Device) CreateBindGroup(descriptor BindGroupDescriptor) *BindGroup {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.Entries != nil {
		pinner.Pin(descriptor.Entries)
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUBindGroupDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateBindGroup(c_d, c_descriptor)
	return &BindGroup{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateBindGroupLayout calls C.wgpuDeviceCreateBindGroupLayout.
func (d *Device) CreateBindGroupLayout(descriptor BindGroupLayoutDescriptor) *BindGroupLayout {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.Entries != nil {
		pinner.Pin(descriptor.Entries)
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUBindGroupLayoutDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateBindGroupLayout(c_d, c_descriptor)
	return &BindGroupLayout{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateBuffer calls C.wgpuDeviceCreateBuffer.
func (d *Device) CreateBuffer(descriptor BufferDescriptor) *Buffer {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUBufferDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateBuffer(c_d, c_descriptor)
	return &Buffer{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateCommandEncoder calls C.wgpuDeviceCreateCommandEncoder.
func (d *Device) CreateCommandEncoder(descriptor CommandEncoderDescriptor) *CommandEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUCommandEncoderDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateCommandEncoder(c_d, c_descriptor)
	return &CommandEncoder{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateComputePipeline calls C.wgpuDeviceCreateComputePipeline.
func (d *Device) CreateComputePipeline(descriptor ComputePipelineDescriptor) *ComputePipeline {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUComputePipelineDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateComputePipeline(c_d, c_descriptor)
	return &ComputePipeline{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateComputePipelineAsync calls C.wgpuDeviceCreateComputePipelineAsync.
func (d *Device) CreateComputePipelineAsync(descriptor ComputePipelineDescriptor, callback CreateComputePipelineAsyncFn) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUComputePipelineDescriptor)(unsafe.Pointer(&descriptor))
	_cbHandle := cgo.NewHandle(callback)
	var _cbInfo C.WGPUCreateComputePipelineAsyncCallbackInfo
	_cbInfo.mode = C.WGPUCallbackMode_AllowProcessEvents
	// cgo.Handle is an opaque uintptr key; cast through uintptr for userdata.
	_cbInfo.userdata1 = *(*unsafe.Pointer)(unsafe.Pointer(&_cbHandle))
	c_result := C.wgpuDeviceCreateComputePipelineAsync(c_d, c_descriptor, _cbInfo)
	return Future{Id: uint64(c_result.id)}
}

// CreatePipelineLayout calls C.wgpuDeviceCreatePipelineLayout.
func (d *Device) CreatePipelineLayout(descriptor PipelineLayoutDescriptor) *PipelineLayout {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.BindGroupLayouts != nil {
		pinner.Pin(descriptor.BindGroupLayouts)
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUPipelineLayoutDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreatePipelineLayout(c_d, c_descriptor)
	return &PipelineLayout{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateQuerySet calls C.wgpuDeviceCreateQuerySet.
func (d *Device) CreateQuerySet(descriptor QuerySetDescriptor) *QuerySet {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUQuerySetDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateQuerySet(c_d, c_descriptor)
	return &QuerySet{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateRenderPipelineAsync calls C.wgpuDeviceCreateRenderPipelineAsync.
func (d *Device) CreateRenderPipelineAsync(descriptor RenderPipelineDescriptor, callback CreateRenderPipelineAsyncFn) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPURenderPipelineDescriptor)(unsafe.Pointer(&descriptor))
	_cbHandle := cgo.NewHandle(callback)
	var _cbInfo C.WGPUCreateRenderPipelineAsyncCallbackInfo
	_cbInfo.mode = C.WGPUCallbackMode_AllowProcessEvents
	// cgo.Handle is an opaque uintptr key; cast through uintptr for userdata.
	_cbInfo.userdata1 = *(*unsafe.Pointer)(unsafe.Pointer(&_cbHandle))
	c_result := C.wgpuDeviceCreateRenderPipelineAsync(c_d, c_descriptor, _cbInfo)
	return Future{Id: uint64(c_result.id)}
}

// CreateRenderBundleEncoder calls C.wgpuDeviceCreateRenderBundleEncoder.
func (d *Device) CreateRenderBundleEncoder(descriptor RenderBundleEncoderDescriptor) *RenderBundleEncoder {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.ColorFormats != nil {
		pinner.Pin(descriptor.ColorFormats)
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPURenderBundleEncoderDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateRenderBundleEncoder(c_d, c_descriptor)
	return &RenderBundleEncoder{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateRenderPipeline calls C.wgpuDeviceCreateRenderPipeline.
func (d *Device) CreateRenderPipeline(descriptor RenderPipelineDescriptor) *RenderPipeline {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPURenderPipelineDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateRenderPipeline(c_d, c_descriptor)
	return &RenderPipeline{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateSampler calls C.wgpuDeviceCreateSampler.
func (d *Device) CreateSampler(descriptor SamplerDescriptor) *Sampler {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUSamplerDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateSampler(c_d, c_descriptor)
	return &Sampler{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateShaderModule calls C.wgpuDeviceCreateShaderModule.
func (d *Device) CreateShaderModule(descriptor ShaderModuleDescriptor) *ShaderModule {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUShaderModuleDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateShaderModule(c_d, c_descriptor)
	return &ShaderModule{inner: uintptr(unsafe.Pointer(c_result))}
}

// CreateTexture calls C.wgpuDeviceCreateTexture.
func (d *Device) CreateTexture(descriptor TextureDescriptor) *Texture {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	if descriptor.ViewFormats != nil {
		pinner.Pin(descriptor.ViewFormats)
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_descriptor := (*C.WGPUTextureDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuDeviceCreateTexture(c_d, c_descriptor)
	return &Texture{inner: uintptr(unsafe.Pointer(c_result))}
}

// Destroy calls C.wgpuDeviceDestroy.
func (d *Device) Destroy() {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	C.wgpuDeviceDestroy(c_d)
}

// GetLostFuture calls C.wgpuDeviceGetLostFuture.
func (d *Device) GetLostFuture() Future {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_result := C.wgpuDeviceGetLostFuture(c_d)
	return Future{Id: uint64(c_result.id)}
}

// GetLimits calls C.wgpuDeviceGetLimits.
func (d *Device) GetLimits(limits Limits) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&limits)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_limits := (*C.WGPULimits)(unsafe.Pointer(&limits))
	c_result := C.wgpuDeviceGetLimits(c_d, c_limits)
	return (Status)(c_result)
}

// HasFeature calls C.wgpuDeviceHasFeature.
func (d *Device) HasFeature(feature FeatureName) bool {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_feature := (C.WGPUFeatureName)(feature)
	c_result := C.wgpuDeviceHasFeature(c_d, c_feature)
	return c_result != 0
}

// GetFeatures calls C.wgpuDeviceGetFeatures.
func (d *Device) GetFeatures(features SupportedFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&features)
	if features.Features != nil {
		pinner.Pin(features.Features)
	}
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_features := (*C.WGPUSupportedFeatures)(unsafe.Pointer(&features))
	C.wgpuDeviceGetFeatures(c_d, c_features)
}

// GetAdapterInfo calls C.wgpuDeviceGetAdapterInfo.
func (d *Device) GetAdapterInfo(adapterInfo AdapterInfo) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&adapterInfo)
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_adapterInfo := (*C.WGPUAdapterInfo)(unsafe.Pointer(&adapterInfo))
	c_result := C.wgpuDeviceGetAdapterInfo(c_d, c_adapterInfo)
	return (Status)(c_result)
}

// GetQueue calls C.wgpuDeviceGetQueue.
func (d *Device) GetQueue() *Queue {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_result := C.wgpuDeviceGetQueue(c_d)
	return &Queue{inner: uintptr(unsafe.Pointer(c_result))}
}

// PushErrorScope calls C.wgpuDevicePushErrorScope.
func (d *Device) PushErrorScope(filter ErrorFilter) {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_filter := (C.WGPUErrorFilter)(filter)
	C.wgpuDevicePushErrorScope(c_d, c_filter)
}

// PopErrorScope calls C.wgpuDevicePopErrorScope.
func (d *Device) PopErrorScope(callback PopErrorScopeFn) Future {
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	_cbHandle := cgo.NewHandle(callback)
	var _cbInfo C.WGPUPopErrorScopeCallbackInfo
	_cbInfo.mode = C.WGPUCallbackMode_AllowProcessEvents
	// cgo.Handle is an opaque uintptr key; cast through uintptr for userdata.
	_cbInfo.userdata1 = *(*unsafe.Pointer)(unsafe.Pointer(&_cbHandle))
	c_result := C.wgpuDevicePopErrorScope(c_d, _cbInfo)
	return Future{Id: uint64(c_result.id)}
}

// SetLabel calls C.wgpuDeviceSetLabel.
func (d *Device) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_d := (C.WGPUDevice)(unsafe.Pointer(d.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuDeviceSetLabel(c_d, c_label)
}

// SetLabel calls C.wgpuExternalTextureSetLabel.
func (e *ExternalTexture) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_e := (C.WGPUExternalTexture)(unsafe.Pointer(e.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuExternalTextureSetLabel(c_e, c_label)
}

// CreateSurface calls C.wgpuInstanceCreateSurface.
func (i *Instance) CreateSurface(descriptor SurfaceDescriptor) *Surface {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_i := (C.WGPUInstance)(unsafe.Pointer(i.inner))
	c_descriptor := (*C.WGPUSurfaceDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuInstanceCreateSurface(c_i, c_descriptor)
	return &Surface{inner: uintptr(unsafe.Pointer(c_result))}
}

// GetWGSLLanguageFeatures calls C.wgpuInstanceGetWGSLLanguageFeatures.
func (i *Instance) GetWGSLLanguageFeatures(features SupportedWGSLLanguageFeatures) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&features)
	if features.Features != nil {
		pinner.Pin(features.Features)
	}
	c_i := (C.WGPUInstance)(unsafe.Pointer(i.inner))
	c_features := (*C.WGPUSupportedWGSLLanguageFeatures)(unsafe.Pointer(&features))
	C.wgpuInstanceGetWGSLLanguageFeatures(c_i, c_features)
}

// HasWGSLLanguageFeature calls C.wgpuInstanceHasWGSLLanguageFeature.
func (i *Instance) HasWGSLLanguageFeature(feature WGSLLanguageFeatureName) bool {
	c_i := (C.WGPUInstance)(unsafe.Pointer(i.inner))
	c_feature := (C.WGPUWGSLLanguageFeatureName)(feature)
	c_result := C.wgpuInstanceHasWGSLLanguageFeature(c_i, c_feature)
	return c_result != 0
}

// ProcessEvents calls C.wgpuInstanceProcessEvents.
func (i *Instance) ProcessEvents() {
	c_i := (C.WGPUInstance)(unsafe.Pointer(i.inner))
	C.wgpuInstanceProcessEvents(c_i)
}

// RequestAdapter calls C.wgpuInstanceRequestAdapter.
func (i *Instance) RequestAdapter(options RequestAdapterOptions, callback RequestAdapterFn) Future {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&options)
	c_i := (C.WGPUInstance)(unsafe.Pointer(i.inner))
	c_options := (*C.WGPURequestAdapterOptions)(unsafe.Pointer(&options))
	_cbHandle := cgo.NewHandle(callback)
	var _cbInfo C.WGPURequestAdapterCallbackInfo
	_cbInfo.mode = C.WGPUCallbackMode_AllowProcessEvents
	// cgo.Handle is an opaque uintptr key; cast through uintptr for userdata.
	_cbInfo.userdata1 = *(*unsafe.Pointer)(unsafe.Pointer(&_cbHandle))
	_cbInfo.callback = C.WGPURequestAdapterCallback(C.goRequestAdapterCB)
	c_result := C.wgpuInstanceRequestAdapter(c_i, c_options, _cbInfo)
	return Future{Id: uint64(c_result.id)}
}

// WaitAny calls C.wgpuInstanceWaitAny.
func (i *Instance) WaitAny(futureCount uintptr, futures FutureWaitInfo, timeoutNS uint64) WaitStatus {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&futures)
	c_i := (C.WGPUInstance)(unsafe.Pointer(i.inner))
	c_futureCount := (C.size_t)(futureCount)
	c_futures := (*C.WGPUFutureWaitInfo)(unsafe.Pointer(&futures))
	c_timeoutNS := (C.uint64_t)(timeoutNS)
	c_result := C.wgpuInstanceWaitAny(c_i, c_futureCount, c_futures, c_timeoutNS)
	return (WaitStatus)(c_result)
}

// SetLabel calls C.wgpuPipelineLayoutSetLabel.
func (p *PipelineLayout) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_p := (C.WGPUPipelineLayout)(unsafe.Pointer(p.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuPipelineLayoutSetLabel(c_p, c_label)
}

// SetLabel calls C.wgpuQuerySetSetLabel.
func (q *QuerySet) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_q := (C.WGPUQuerySet)(unsafe.Pointer(q.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuQuerySetSetLabel(c_q, c_label)
}

// GetType calls C.wgpuQuerySetGetType.
func (q *QuerySet) GetType() QueryType {
	c_q := (C.WGPUQuerySet)(unsafe.Pointer(q.inner))
	c_result := C.wgpuQuerySetGetType(c_q)
	return (QueryType)(c_result)
}

// GetCount calls C.wgpuQuerySetGetCount.
func (q *QuerySet) GetCount() uint32 {
	c_q := (C.WGPUQuerySet)(unsafe.Pointer(q.inner))
	c_result := C.wgpuQuerySetGetCount(c_q)
	return (uint32)(c_result)
}

// Destroy calls C.wgpuQuerySetDestroy.
func (q *QuerySet) Destroy() {
	c_q := (C.WGPUQuerySet)(unsafe.Pointer(q.inner))
	C.wgpuQuerySetDestroy(c_q)
}

// Submit calls C.wgpuQueueSubmit.
func (q *Queue) Submit(commands []*CommandBuffer) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(commands) > 0 {
		pinner.Pin(&commands[0])
	}
	c_q := (C.WGPUQueue)(unsafe.Pointer(q.inner))
	commands_handles := make([]uintptr, len(commands))
	for i, v := range commands {
		commands_handles[i] = v.inner
	}
	var c_commands_ptr *C.WGPUCommandBuffer
	if len(commands) > 0 {
		c_commands_ptr = (*C.WGPUCommandBuffer)(unsafe.Pointer(&commands_handles[0]))
	}
	c_commands_count := (C.size_t)(len(commands))
	C.wgpuQueueSubmit(c_q, c_commands_count, c_commands_ptr)
}

// OnSubmittedWorkDone calls C.wgpuQueueOnSubmittedWorkDone.
func (q *Queue) OnSubmittedWorkDone(callback QueueWorkDoneFn) Future {
	c_q := (C.WGPUQueue)(unsafe.Pointer(q.inner))
	_cbHandle := cgo.NewHandle(callback)
	var _cbInfo C.WGPUQueueWorkDoneCallbackInfo
	_cbInfo.mode = C.WGPUCallbackMode_AllowProcessEvents
	// cgo.Handle is an opaque uintptr key; cast through uintptr for userdata.
	_cbInfo.userdata1 = *(*unsafe.Pointer)(unsafe.Pointer(&_cbHandle))
	_cbInfo.callback = C.WGPUQueueWorkDoneCallback(C.goQueueWorkDoneCB)
	c_result := C.wgpuQueueOnSubmittedWorkDone(c_q, _cbInfo)
	return Future{Id: uint64(c_result.id)}
}

// WriteBuffer calls C.wgpuQueueWriteBuffer.
func (q *Queue) WriteBuffer(buffer *Buffer, bufferOffset uint64, data unsafe.Pointer, size uintptr) {
	c_q := (C.WGPUQueue)(unsafe.Pointer(q.inner))
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer.inner))
	c_bufferOffset := (C.uint64_t)(bufferOffset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	C.wgpuQueueWriteBuffer(c_q, c_buffer, c_bufferOffset, c_data, c_size)
}

// WriteTexture calls C.wgpuQueueWriteTexture.
func (q *Queue) WriteTexture(destination TexelCopyTextureInfo, data unsafe.Pointer, dataSize uintptr, dataLayout TexelCopyBufferLayout, writeSize Extent3D) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&destination)
	pinner.Pin(&dataLayout)
	pinner.Pin(&writeSize)
	c_q := (C.WGPUQueue)(unsafe.Pointer(q.inner))
	c_destination := (*C.WGPUTexelCopyTextureInfo)(unsafe.Pointer(&destination))
	c_data := (unsafe.Pointer)(data)
	c_dataSize := (C.size_t)(dataSize)
	c_dataLayout := (*C.WGPUTexelCopyBufferLayout)(unsafe.Pointer(&dataLayout))
	c_writeSize := (*C.WGPUExtent3D)(unsafe.Pointer(&writeSize))
	C.wgpuQueueWriteTexture(c_q, c_destination, c_data, c_dataSize, c_dataLayout, c_writeSize)
}

// SetLabel calls C.wgpuQueueSetLabel.
func (q *Queue) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_q := (C.WGPUQueue)(unsafe.Pointer(q.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuQueueSetLabel(c_q, c_label)
}

// SetLabel calls C.wgpuRenderBundleSetLabel.
func (r *RenderBundle) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_r := (C.WGPURenderBundle)(unsafe.Pointer(r.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuRenderBundleSetLabel(c_r, c_label)
}

// SetPipeline calls C.wgpuRenderBundleEncoderSetPipeline.
func (r *RenderBundleEncoder) SetPipeline(pipeline *RenderPipeline) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_pipeline := (C.WGPURenderPipeline)(unsafe.Pointer(pipeline.inner))
	C.wgpuRenderBundleEncoderSetPipeline(c_r, c_pipeline)
}

// SetBindGroup calls C.wgpuRenderBundleEncoderSetBindGroup.
func (r *RenderBundleEncoder) SetBindGroup(groupIndex uint32, group *BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_groupIndex := (C.uint32_t)(groupIndex)
	c_group := (C.WGPUBindGroup)(unsafe.Pointer(group.inner))
	var c_dynamicOffsets_ptr *C.uint32_t
	if len(dynamicOffsets) > 0 {
		c_dynamicOffsets_ptr = (*C.uint32_t)(unsafe.Pointer(&dynamicOffsets[0]))
	}
	c_dynamicOffsets_count := (C.size_t)(len(dynamicOffsets))
	C.wgpuRenderBundleEncoderSetBindGroup(c_r, c_groupIndex, c_group, c_dynamicOffsets_count, c_dynamicOffsets_ptr)
}

// SetImmediates calls C.wgpuRenderBundleEncoderSetImmediates.
func (r *RenderBundleEncoder) SetImmediates(offset uint32, data unsafe.Pointer, size uintptr) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_offset := (C.uint32_t)(offset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	C.wgpuRenderBundleEncoderSetImmediates(c_r, c_offset, c_data, c_size)
}

// Draw calls C.wgpuRenderBundleEncoderDraw.
func (r *RenderBundleEncoder) Draw(vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_vertexCount := (C.uint32_t)(vertexCount)
	c_instanceCount := (C.uint32_t)(instanceCount)
	c_firstVertex := (C.uint32_t)(firstVertex)
	c_firstInstance := (C.uint32_t)(firstInstance)
	C.wgpuRenderBundleEncoderDraw(c_r, c_vertexCount, c_instanceCount, c_firstVertex, c_firstInstance)
}

// DrawIndexed calls C.wgpuRenderBundleEncoderDrawIndexed.
func (r *RenderBundleEncoder) DrawIndexed(indexCount uint32, instanceCount uint32, firstIndex uint32, baseVertex int32, firstInstance uint32) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_indexCount := (C.uint32_t)(indexCount)
	c_instanceCount := (C.uint32_t)(instanceCount)
	c_firstIndex := (C.uint32_t)(firstIndex)
	c_baseVertex := (C.int32_t)(baseVertex)
	c_firstInstance := (C.uint32_t)(firstInstance)
	C.wgpuRenderBundleEncoderDrawIndexed(c_r, c_indexCount, c_instanceCount, c_firstIndex, c_baseVertex, c_firstInstance)
}

// DrawIndirect calls C.wgpuRenderBundleEncoderDrawIndirect.
func (r *RenderBundleEncoder) DrawIndirect(indirectBuffer *Buffer, indirectOffset uint64) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_indirectBuffer := (C.WGPUBuffer)(unsafe.Pointer(indirectBuffer.inner))
	c_indirectOffset := (C.uint64_t)(indirectOffset)
	C.wgpuRenderBundleEncoderDrawIndirect(c_r, c_indirectBuffer, c_indirectOffset)
}

// DrawIndexedIndirect calls C.wgpuRenderBundleEncoderDrawIndexedIndirect.
func (r *RenderBundleEncoder) DrawIndexedIndirect(indirectBuffer *Buffer, indirectOffset uint64) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_indirectBuffer := (C.WGPUBuffer)(unsafe.Pointer(indirectBuffer.inner))
	c_indirectOffset := (C.uint64_t)(indirectOffset)
	C.wgpuRenderBundleEncoderDrawIndexedIndirect(c_r, c_indirectBuffer, c_indirectOffset)
}

// InsertDebugMarker calls C.wgpuRenderBundleEncoderInsertDebugMarker.
func (r *RenderBundleEncoder) InsertDebugMarker(markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_markerLabel := cgoStringView(markerLabel, &pinner)
	C.wgpuRenderBundleEncoderInsertDebugMarker(c_r, c_markerLabel)
}

// PopDebugGroup calls C.wgpuRenderBundleEncoderPopDebugGroup.
func (r *RenderBundleEncoder) PopDebugGroup() {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	C.wgpuRenderBundleEncoderPopDebugGroup(c_r)
}

// PushDebugGroup calls C.wgpuRenderBundleEncoderPushDebugGroup.
func (r *RenderBundleEncoder) PushDebugGroup(groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_groupLabel := cgoStringView(groupLabel, &pinner)
	C.wgpuRenderBundleEncoderPushDebugGroup(c_r, c_groupLabel)
}

// SetVertexBuffer calls C.wgpuRenderBundleEncoderSetVertexBuffer.
func (r *RenderBundleEncoder) SetVertexBuffer(slot uint32, buffer *Buffer, offset uint64, size uint64) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_slot := (C.uint32_t)(slot)
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer.inner))
	c_offset := (C.uint64_t)(offset)
	c_size := (C.uint64_t)(size)
	C.wgpuRenderBundleEncoderSetVertexBuffer(c_r, c_slot, c_buffer, c_offset, c_size)
}

// SetIndexBuffer calls C.wgpuRenderBundleEncoderSetIndexBuffer.
func (r *RenderBundleEncoder) SetIndexBuffer(buffer *Buffer, format IndexFormat, offset uint64, size uint64) {
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer.inner))
	c_format := (C.WGPUIndexFormat)(format)
	c_offset := (C.uint64_t)(offset)
	c_size := (C.uint64_t)(size)
	C.wgpuRenderBundleEncoderSetIndexBuffer(c_r, c_buffer, c_format, c_offset, c_size)
}

// Finish calls C.wgpuRenderBundleEncoderFinish.
func (r *RenderBundleEncoder) Finish(descriptor RenderBundleDescriptor) *RenderBundle {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_descriptor := (*C.WGPURenderBundleDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuRenderBundleEncoderFinish(c_r, c_descriptor)
	return &RenderBundle{inner: uintptr(unsafe.Pointer(c_result))}
}

// SetLabel calls C.wgpuRenderBundleEncoderSetLabel.
func (r *RenderBundleEncoder) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_r := (C.WGPURenderBundleEncoder)(unsafe.Pointer(r.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuRenderBundleEncoderSetLabel(c_r, c_label)
}

// SetPipeline calls C.wgpuRenderPassEncoderSetPipeline.
func (r *RenderPassEncoder) SetPipeline(pipeline *RenderPipeline) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_pipeline := (C.WGPURenderPipeline)(unsafe.Pointer(pipeline.inner))
	C.wgpuRenderPassEncoderSetPipeline(c_r, c_pipeline)
}

// SetBindGroup calls C.wgpuRenderPassEncoderSetBindGroup.
func (r *RenderPassEncoder) SetBindGroup(groupIndex uint32, group *BindGroup, dynamicOffsets []uint32) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(dynamicOffsets) > 0 {
		pinner.Pin(&dynamicOffsets[0])
	}
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_groupIndex := (C.uint32_t)(groupIndex)
	c_group := (C.WGPUBindGroup)(unsafe.Pointer(group.inner))
	var c_dynamicOffsets_ptr *C.uint32_t
	if len(dynamicOffsets) > 0 {
		c_dynamicOffsets_ptr = (*C.uint32_t)(unsafe.Pointer(&dynamicOffsets[0]))
	}
	c_dynamicOffsets_count := (C.size_t)(len(dynamicOffsets))
	C.wgpuRenderPassEncoderSetBindGroup(c_r, c_groupIndex, c_group, c_dynamicOffsets_count, c_dynamicOffsets_ptr)
}

// SetImmediates calls C.wgpuRenderPassEncoderSetImmediates.
func (r *RenderPassEncoder) SetImmediates(offset uint32, data unsafe.Pointer, size uintptr) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_offset := (C.uint32_t)(offset)
	c_data := (unsafe.Pointer)(data)
	c_size := (C.size_t)(size)
	C.wgpuRenderPassEncoderSetImmediates(c_r, c_offset, c_data, c_size)
}

// Draw calls C.wgpuRenderPassEncoderDraw.
func (r *RenderPassEncoder) Draw(vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_vertexCount := (C.uint32_t)(vertexCount)
	c_instanceCount := (C.uint32_t)(instanceCount)
	c_firstVertex := (C.uint32_t)(firstVertex)
	c_firstInstance := (C.uint32_t)(firstInstance)
	C.wgpuRenderPassEncoderDraw(c_r, c_vertexCount, c_instanceCount, c_firstVertex, c_firstInstance)
}

// DrawIndexed calls C.wgpuRenderPassEncoderDrawIndexed.
func (r *RenderPassEncoder) DrawIndexed(indexCount uint32, instanceCount uint32, firstIndex uint32, baseVertex int32, firstInstance uint32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_indexCount := (C.uint32_t)(indexCount)
	c_instanceCount := (C.uint32_t)(instanceCount)
	c_firstIndex := (C.uint32_t)(firstIndex)
	c_baseVertex := (C.int32_t)(baseVertex)
	c_firstInstance := (C.uint32_t)(firstInstance)
	C.wgpuRenderPassEncoderDrawIndexed(c_r, c_indexCount, c_instanceCount, c_firstIndex, c_baseVertex, c_firstInstance)
}

// DrawIndirect calls C.wgpuRenderPassEncoderDrawIndirect.
func (r *RenderPassEncoder) DrawIndirect(indirectBuffer *Buffer, indirectOffset uint64) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_indirectBuffer := (C.WGPUBuffer)(unsafe.Pointer(indirectBuffer.inner))
	c_indirectOffset := (C.uint64_t)(indirectOffset)
	C.wgpuRenderPassEncoderDrawIndirect(c_r, c_indirectBuffer, c_indirectOffset)
}

// DrawIndexedIndirect calls C.wgpuRenderPassEncoderDrawIndexedIndirect.
func (r *RenderPassEncoder) DrawIndexedIndirect(indirectBuffer *Buffer, indirectOffset uint64) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_indirectBuffer := (C.WGPUBuffer)(unsafe.Pointer(indirectBuffer.inner))
	c_indirectOffset := (C.uint64_t)(indirectOffset)
	C.wgpuRenderPassEncoderDrawIndexedIndirect(c_r, c_indirectBuffer, c_indirectOffset)
}

// ExecuteBundles calls C.wgpuRenderPassEncoderExecuteBundles.
func (r *RenderPassEncoder) ExecuteBundles(bundles []*RenderBundle) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	if len(bundles) > 0 {
		pinner.Pin(&bundles[0])
	}
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	bundles_handles := make([]uintptr, len(bundles))
	for i, v := range bundles {
		bundles_handles[i] = v.inner
	}
	var c_bundles_ptr *C.WGPURenderBundle
	if len(bundles) > 0 {
		c_bundles_ptr = (*C.WGPURenderBundle)(unsafe.Pointer(&bundles_handles[0]))
	}
	c_bundles_count := (C.size_t)(len(bundles))
	C.wgpuRenderPassEncoderExecuteBundles(c_r, c_bundles_count, c_bundles_ptr)
}

// InsertDebugMarker calls C.wgpuRenderPassEncoderInsertDebugMarker.
func (r *RenderPassEncoder) InsertDebugMarker(markerLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_markerLabel := cgoStringView(markerLabel, &pinner)
	C.wgpuRenderPassEncoderInsertDebugMarker(c_r, c_markerLabel)
}

// PopDebugGroup calls C.wgpuRenderPassEncoderPopDebugGroup.
func (r *RenderPassEncoder) PopDebugGroup() {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	C.wgpuRenderPassEncoderPopDebugGroup(c_r)
}

// PushDebugGroup calls C.wgpuRenderPassEncoderPushDebugGroup.
func (r *RenderPassEncoder) PushDebugGroup(groupLabel string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_groupLabel := cgoStringView(groupLabel, &pinner)
	C.wgpuRenderPassEncoderPushDebugGroup(c_r, c_groupLabel)
}

// SetStencilReference calls C.wgpuRenderPassEncoderSetStencilReference.
func (r *RenderPassEncoder) SetStencilReference(reference uint32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_reference := (C.uint32_t)(reference)
	C.wgpuRenderPassEncoderSetStencilReference(c_r, c_reference)
}

// SetBlendConstant calls C.wgpuRenderPassEncoderSetBlendConstant.
func (r *RenderPassEncoder) SetBlendConstant(color Color) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&color)
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_color := (*C.WGPUColor)(unsafe.Pointer(&color))
	C.wgpuRenderPassEncoderSetBlendConstant(c_r, c_color)
}

// SetViewport calls C.wgpuRenderPassEncoderSetViewport.
func (r *RenderPassEncoder) SetViewport(x float32, y float32, width float32, height float32, minDepth float32, maxDepth float32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_x := (C.float)(x)
	c_y := (C.float)(y)
	c_width := (C.float)(width)
	c_height := (C.float)(height)
	c_minDepth := (C.float)(minDepth)
	c_maxDepth := (C.float)(maxDepth)
	C.wgpuRenderPassEncoderSetViewport(c_r, c_x, c_y, c_width, c_height, c_minDepth, c_maxDepth)
}

// SetScissorRect calls C.wgpuRenderPassEncoderSetScissorRect.
func (r *RenderPassEncoder) SetScissorRect(x uint32, y uint32, width uint32, height uint32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_x := (C.uint32_t)(x)
	c_y := (C.uint32_t)(y)
	c_width := (C.uint32_t)(width)
	c_height := (C.uint32_t)(height)
	C.wgpuRenderPassEncoderSetScissorRect(c_r, c_x, c_y, c_width, c_height)
}

// SetVertexBuffer calls C.wgpuRenderPassEncoderSetVertexBuffer.
func (r *RenderPassEncoder) SetVertexBuffer(slot uint32, buffer *Buffer, offset uint64, size uint64) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_slot := (C.uint32_t)(slot)
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer.inner))
	c_offset := (C.uint64_t)(offset)
	c_size := (C.uint64_t)(size)
	C.wgpuRenderPassEncoderSetVertexBuffer(c_r, c_slot, c_buffer, c_offset, c_size)
}

// SetIndexBuffer calls C.wgpuRenderPassEncoderSetIndexBuffer.
func (r *RenderPassEncoder) SetIndexBuffer(buffer *Buffer, format IndexFormat, offset uint64, size uint64) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_buffer := (C.WGPUBuffer)(unsafe.Pointer(buffer.inner))
	c_format := (C.WGPUIndexFormat)(format)
	c_offset := (C.uint64_t)(offset)
	c_size := (C.uint64_t)(size)
	C.wgpuRenderPassEncoderSetIndexBuffer(c_r, c_buffer, c_format, c_offset, c_size)
}

// BeginOcclusionQuery calls C.wgpuRenderPassEncoderBeginOcclusionQuery.
func (r *RenderPassEncoder) BeginOcclusionQuery(queryIndex uint32) {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_queryIndex := (C.uint32_t)(queryIndex)
	C.wgpuRenderPassEncoderBeginOcclusionQuery(c_r, c_queryIndex)
}

// EndOcclusionQuery calls C.wgpuRenderPassEncoderEndOcclusionQuery.
func (r *RenderPassEncoder) EndOcclusionQuery() {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	C.wgpuRenderPassEncoderEndOcclusionQuery(c_r)
}

// End calls C.wgpuRenderPassEncoderEnd.
func (r *RenderPassEncoder) End() {
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	C.wgpuRenderPassEncoderEnd(c_r)
}

// SetLabel calls C.wgpuRenderPassEncoderSetLabel.
func (r *RenderPassEncoder) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_r := (C.WGPURenderPassEncoder)(unsafe.Pointer(r.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuRenderPassEncoderSetLabel(c_r, c_label)
}

// GetBindGroupLayout calls C.wgpuRenderPipelineGetBindGroupLayout.
func (r *RenderPipeline) GetBindGroupLayout(groupIndex uint32) *BindGroupLayout {
	c_r := (C.WGPURenderPipeline)(unsafe.Pointer(r.inner))
	c_groupIndex := (C.uint32_t)(groupIndex)
	c_result := C.wgpuRenderPipelineGetBindGroupLayout(c_r, c_groupIndex)
	return &BindGroupLayout{inner: uintptr(unsafe.Pointer(c_result))}
}

// SetLabel calls C.wgpuRenderPipelineSetLabel.
func (r *RenderPipeline) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_r := (C.WGPURenderPipeline)(unsafe.Pointer(r.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuRenderPipelineSetLabel(c_r, c_label)
}

// SetLabel calls C.wgpuSamplerSetLabel.
func (s *Sampler) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_s := (C.WGPUSampler)(unsafe.Pointer(s.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuSamplerSetLabel(c_s, c_label)
}

// GetCompilationInfo calls C.wgpuShaderModuleGetCompilationInfo.
func (s *ShaderModule) GetCompilationInfo(callback CompilationInfoFn) Future {
	c_s := (C.WGPUShaderModule)(unsafe.Pointer(s.inner))
	_cbHandle := cgo.NewHandle(callback)
	var _cbInfo C.WGPUCompilationInfoCallbackInfo
	_cbInfo.mode = C.WGPUCallbackMode_AllowProcessEvents
	// cgo.Handle is an opaque uintptr key; cast through uintptr for userdata.
	_cbInfo.userdata1 = *(*unsafe.Pointer)(unsafe.Pointer(&_cbHandle))
	c_result := C.wgpuShaderModuleGetCompilationInfo(c_s, _cbInfo)
	return Future{Id: uint64(c_result.id)}
}

// SetLabel calls C.wgpuShaderModuleSetLabel.
func (s *ShaderModule) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_s := (C.WGPUShaderModule)(unsafe.Pointer(s.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuShaderModuleSetLabel(c_s, c_label)
}

// Configure calls C.wgpuSurfaceConfigure.
func (s *Surface) Configure(config SurfaceConfiguration) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&config)
	if config.ViewFormats != nil {
		pinner.Pin(config.ViewFormats)
	}
	c_s := (C.WGPUSurface)(unsafe.Pointer(s.inner))
	c_config := (*C.WGPUSurfaceConfiguration)(unsafe.Pointer(&config))
	C.wgpuSurfaceConfigure(c_s, c_config)
}

// GetCapabilities calls C.wgpuSurfaceGetCapabilities.
func (s *Surface) GetCapabilities(adapter *Adapter, capabilities SurfaceCapabilities) Status {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&capabilities)
	if capabilities.Formats != nil {
		pinner.Pin(capabilities.Formats)
	}
	if capabilities.PresentModes != nil {
		pinner.Pin(capabilities.PresentModes)
	}
	if capabilities.AlphaModes != nil {
		pinner.Pin(capabilities.AlphaModes)
	}
	c_s := (C.WGPUSurface)(unsafe.Pointer(s.inner))
	c_adapter := (C.WGPUAdapter)(unsafe.Pointer(adapter.inner))
	c_capabilities := (*C.WGPUSurfaceCapabilities)(unsafe.Pointer(&capabilities))
	c_result := C.wgpuSurfaceGetCapabilities(c_s, c_adapter, c_capabilities)
	return (Status)(c_result)
}

// GetCurrentTexture calls C.wgpuSurfaceGetCurrentTexture.
func (s *Surface) GetCurrentTexture(surfaceTexture SurfaceTexture) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&surfaceTexture)
	c_s := (C.WGPUSurface)(unsafe.Pointer(s.inner))
	c_surfaceTexture := (*C.WGPUSurfaceTexture)(unsafe.Pointer(&surfaceTexture))
	C.wgpuSurfaceGetCurrentTexture(c_s, c_surfaceTexture)
}

// Present calls C.wgpuSurfacePresent.
func (s *Surface) Present() Status {
	c_s := (C.WGPUSurface)(unsafe.Pointer(s.inner))
	c_result := C.wgpuSurfacePresent(c_s)
	return (Status)(c_result)
}

// Unconfigure calls C.wgpuSurfaceUnconfigure.
func (s *Surface) Unconfigure() {
	c_s := (C.WGPUSurface)(unsafe.Pointer(s.inner))
	C.wgpuSurfaceUnconfigure(c_s)
}

// SetLabel calls C.wgpuSurfaceSetLabel.
func (s *Surface) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_s := (C.WGPUSurface)(unsafe.Pointer(s.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuSurfaceSetLabel(c_s, c_label)
}

// CreateView calls C.wgpuTextureCreateView.
func (t *Texture) CreateView(descriptor TextureViewDescriptor) *TextureView {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	pinner.Pin(&descriptor)
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_descriptor := (*C.WGPUTextureViewDescriptor)(unsafe.Pointer(&descriptor))
	c_result := C.wgpuTextureCreateView(c_t, c_descriptor)
	return &TextureView{inner: uintptr(unsafe.Pointer(c_result))}
}

// SetLabel calls C.wgpuTextureSetLabel.
func (t *Texture) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuTextureSetLabel(c_t, c_label)
}

// GetWidth calls C.wgpuTextureGetWidth.
func (t *Texture) GetWidth() uint32 {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_result := C.wgpuTextureGetWidth(c_t)
	return (uint32)(c_result)
}

// GetHeight calls C.wgpuTextureGetHeight.
func (t *Texture) GetHeight() uint32 {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_result := C.wgpuTextureGetHeight(c_t)
	return (uint32)(c_result)
}

// GetDepthOrArrayLayers calls C.wgpuTextureGetDepthOrArrayLayers.
func (t *Texture) GetDepthOrArrayLayers() uint32 {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_result := C.wgpuTextureGetDepthOrArrayLayers(c_t)
	return (uint32)(c_result)
}

// GetMipLevelCount calls C.wgpuTextureGetMipLevelCount.
func (t *Texture) GetMipLevelCount() uint32 {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_result := C.wgpuTextureGetMipLevelCount(c_t)
	return (uint32)(c_result)
}

// GetSampleCount calls C.wgpuTextureGetSampleCount.
func (t *Texture) GetSampleCount() uint32 {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_result := C.wgpuTextureGetSampleCount(c_t)
	return (uint32)(c_result)
}

// GetDimension calls C.wgpuTextureGetDimension.
func (t *Texture) GetDimension() TextureDimension {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_result := C.wgpuTextureGetDimension(c_t)
	return (TextureDimension)(c_result)
}

// GetTextureBindingViewDimension calls C.wgpuTextureGetTextureBindingViewDimension.
func (t *Texture) GetTextureBindingViewDimension() TextureViewDimension {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_result := C.wgpuTextureGetTextureBindingViewDimension(c_t)
	return (TextureViewDimension)(c_result)
}

// GetFormat calls C.wgpuTextureGetFormat.
func (t *Texture) GetFormat() TextureFormat {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_result := C.wgpuTextureGetFormat(c_t)
	return (TextureFormat)(c_result)
}

// GetUsage calls C.wgpuTextureGetUsage.
func (t *Texture) GetUsage() TextureUsage {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	c_result := C.wgpuTextureGetUsage(c_t)
	return (TextureUsage)(c_result)
}

// Destroy calls C.wgpuTextureDestroy.
func (t *Texture) Destroy() {
	c_t := (C.WGPUTexture)(unsafe.Pointer(t.inner))
	C.wgpuTextureDestroy(c_t)
}

// SetLabel calls C.wgpuTextureViewSetLabel.
func (t *TextureView) SetLabel(label string) {
	var pinner runtime.Pinner
	defer pinner.Unpin()
	c_t := (C.WGPUTextureView)(unsafe.Pointer(t.inner))
	c_label := cgoStringView(label, &pinner)
	C.wgpuTextureViewSetLabel(c_t, c_label)
}
